// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: category/category_query.proto

package category

import (
	_ "github.com/MamangRust/monolith-graphql-pointofsale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_category_category_query_proto protoreflect.FileDescriptor

const file_category_category_query_proto_rawDesc = "" +
	"\n" +
	"\x1dcategory/category_query.proto\x12\vpb.category\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1ecategory/category_common.proto2\xb1\x02\n" +
	"\x14CategoryQueryService\x12i\n" +
	"\fFindByActive\x12#.pb.category.FindAllCategoryRequest\x1a2.pb.category.ApiResponsePaginationCategoryDeleteAt\"\x00\x12Z\n" +
	"\aFindAll\x12#.pb.category.FindAllCategoryRequest\x1a*.pb.category.ApiResponsePaginationCategory\x12R\n" +
	"\bFindById\x12$.pb.category.FindByIdCategoryRequest\x1a .pb.category.ApiResponseCategoryB@Z>github.com/MamangRust/monolith-graphql-pointofsale-pb/categoryb\x06proto3"

var file_category_category_query_proto_goTypes = []any{
	(*FindAllCategoryRequest)(nil),                // 0: pb.category.FindAllCategoryRequest
	(*FindByIdCategoryRequest)(nil),               // 1: pb.category.FindByIdCategoryRequest
	(*ApiResponsePaginationCategoryDeleteAt)(nil), // 2: pb.category.ApiResponsePaginationCategoryDeleteAt
	(*ApiResponsePaginationCategory)(nil),         // 3: pb.category.ApiResponsePaginationCategory
	(*ApiResponseCategory)(nil),                   // 4: pb.category.ApiResponseCategory
}
var file_category_category_query_proto_depIdxs = []int32{
	0, // 0: pb.category.CategoryQueryService.FindByActive:input_type -> pb.category.FindAllCategoryRequest
	0, // 1: pb.category.CategoryQueryService.FindAll:input_type -> pb.category.FindAllCategoryRequest
	1, // 2: pb.category.CategoryQueryService.FindById:input_type -> pb.category.FindByIdCategoryRequest
	2, // 3: pb.category.CategoryQueryService.FindByActive:output_type -> pb.category.ApiResponsePaginationCategoryDeleteAt
	3, // 4: pb.category.CategoryQueryService.FindAll:output_type -> pb.category.ApiResponsePaginationCategory
	4, // 5: pb.category.CategoryQueryService.FindById:output_type -> pb.category.ApiResponseCategory
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_category_category_query_proto_init() }
func file_category_category_query_proto_init() {
	if File_category_category_query_proto != nil {
		return
	}
	file_category_category_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_category_query_proto_rawDesc), len(file_category_category_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_category_query_proto_goTypes,
		DependencyIndexes: file_category_category_query_proto_depIdxs,
	}.Build()
	File_category_category_query_proto = out.File
	file_category_category_query_proto_goTypes = nil
	file_category_category_query_proto_depIdxs = nil
}
