// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: category/category_stats.proto

package category

import (
	_ "github.com/MamangRust/monolith-graphql-pointofsale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_category_category_stats_proto protoreflect.FileDescriptor

const file_category_category_stats_proto_rawDesc = "" +
	"\n" +
	"\x1dcategory/category_stats.proto\x12\vpb.category\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1ecategory/category_common.proto2\xdb\n" +
	"\n" +
	"\x14CategoryStatsService\x12t\n" +
	"\x16FindMonthlyTotalPrices\x12%.pb.category.FindYearMonthTotalPrices\x1a1.pb.category.ApiResponseCategoryMonthlyTotalPrice\"\x00\x12m\n" +
	"\x15FindYearlyTotalPrices\x12 .pb.category.FindYearTotalPrices\x1a0.pb.category.ApiResponseCategoryYearlyTotalPrice\"\x00\x12{\n" +
	"\x1aFindMonthlyTotalPricesById\x12(.pb.category.FindYearMonthTotalPriceById\x1a1.pb.category.ApiResponseCategoryMonthlyTotalPrice\"\x00\x12t\n" +
	"\x19FindYearlyTotalPricesById\x12#.pb.category.FindYearTotalPriceById\x1a0.pb.category.ApiResponseCategoryYearlyTotalPrice\"\x00\x12\x87\x01\n" +
	" FindMonthlyTotalPricesByMerchant\x12..pb.category.FindYearMonthTotalPriceByMerchant\x1a1.pb.category.ApiResponseCategoryMonthlyTotalPrice\"\x00\x12\x80\x01\n" +
	"\x1fFindYearlyTotalPricesByMerchant\x12).pb.category.FindYearTotalPriceByMerchant\x1a0.pb.category.ApiResponseCategoryYearlyTotalPrice\"\x00\x12[\n" +
	"\x0eFindMonthPrice\x12\x1d.pb.category.FindYearCategory\x1a*.pb.category.ApiResponseCategoryMonthPrice\x12Y\n" +
	"\rFindYearPrice\x12\x1d.pb.category.FindYearCategory\x1a).pb.category.ApiResponseCategoryYearPrice\x12o\n" +
	"\x18FindMonthPriceByMerchant\x12'.pb.category.FindYearCategoryByMerchant\x1a*.pb.category.ApiResponseCategoryMonthPrice\x12m\n" +
	"\x17FindYearPriceByMerchant\x12'.pb.category.FindYearCategoryByMerchant\x1a).pb.category.ApiResponseCategoryYearPrice\x12c\n" +
	"\x12FindMonthPriceById\x12!.pb.category.FindYearCategoryById\x1a*.pb.category.ApiResponseCategoryMonthPrice\x12a\n" +
	"\x11FindYearPriceById\x12!.pb.category.FindYearCategoryById\x1a).pb.category.ApiResponseCategoryYearPriceB@Z>github.com/MamangRust/monolith-graphql-pointofsale-pb/categoryb\x06proto3"

var file_category_category_stats_proto_goTypes = []any{
	(*FindYearMonthTotalPrices)(nil),             // 0: pb.category.FindYearMonthTotalPrices
	(*FindYearTotalPrices)(nil),                  // 1: pb.category.FindYearTotalPrices
	(*FindYearMonthTotalPriceById)(nil),          // 2: pb.category.FindYearMonthTotalPriceById
	(*FindYearTotalPriceById)(nil),               // 3: pb.category.FindYearTotalPriceById
	(*FindYearMonthTotalPriceByMerchant)(nil),    // 4: pb.category.FindYearMonthTotalPriceByMerchant
	(*FindYearTotalPriceByMerchant)(nil),         // 5: pb.category.FindYearTotalPriceByMerchant
	(*FindYearCategory)(nil),                     // 6: pb.category.FindYearCategory
	(*FindYearCategoryByMerchant)(nil),           // 7: pb.category.FindYearCategoryByMerchant
	(*FindYearCategoryById)(nil),                 // 8: pb.category.FindYearCategoryById
	(*ApiResponseCategoryMonthlyTotalPrice)(nil), // 9: pb.category.ApiResponseCategoryMonthlyTotalPrice
	(*ApiResponseCategoryYearlyTotalPrice)(nil),  // 10: pb.category.ApiResponseCategoryYearlyTotalPrice
	(*ApiResponseCategoryMonthPrice)(nil),        // 11: pb.category.ApiResponseCategoryMonthPrice
	(*ApiResponseCategoryYearPrice)(nil),         // 12: pb.category.ApiResponseCategoryYearPrice
}
var file_category_category_stats_proto_depIdxs = []int32{
	0,  // 0: pb.category.CategoryStatsService.FindMonthlyTotalPrices:input_type -> pb.category.FindYearMonthTotalPrices
	1,  // 1: pb.category.CategoryStatsService.FindYearlyTotalPrices:input_type -> pb.category.FindYearTotalPrices
	2,  // 2: pb.category.CategoryStatsService.FindMonthlyTotalPricesById:input_type -> pb.category.FindYearMonthTotalPriceById
	3,  // 3: pb.category.CategoryStatsService.FindYearlyTotalPricesById:input_type -> pb.category.FindYearTotalPriceById
	4,  // 4: pb.category.CategoryStatsService.FindMonthlyTotalPricesByMerchant:input_type -> pb.category.FindYearMonthTotalPriceByMerchant
	5,  // 5: pb.category.CategoryStatsService.FindYearlyTotalPricesByMerchant:input_type -> pb.category.FindYearTotalPriceByMerchant
	6,  // 6: pb.category.CategoryStatsService.FindMonthPrice:input_type -> pb.category.FindYearCategory
	6,  // 7: pb.category.CategoryStatsService.FindYearPrice:input_type -> pb.category.FindYearCategory
	7,  // 8: pb.category.CategoryStatsService.FindMonthPriceByMerchant:input_type -> pb.category.FindYearCategoryByMerchant
	7,  // 9: pb.category.CategoryStatsService.FindYearPriceByMerchant:input_type -> pb.category.FindYearCategoryByMerchant
	8,  // 10: pb.category.CategoryStatsService.FindMonthPriceById:input_type -> pb.category.FindYearCategoryById
	8,  // 11: pb.category.CategoryStatsService.FindYearPriceById:input_type -> pb.category.FindYearCategoryById
	9,  // 12: pb.category.CategoryStatsService.FindMonthlyTotalPrices:output_type -> pb.category.ApiResponseCategoryMonthlyTotalPrice
	10, // 13: pb.category.CategoryStatsService.FindYearlyTotalPrices:output_type -> pb.category.ApiResponseCategoryYearlyTotalPrice
	9,  // 14: pb.category.CategoryStatsService.FindMonthlyTotalPricesById:output_type -> pb.category.ApiResponseCategoryMonthlyTotalPrice
	10, // 15: pb.category.CategoryStatsService.FindYearlyTotalPricesById:output_type -> pb.category.ApiResponseCategoryYearlyTotalPrice
	9,  // 16: pb.category.CategoryStatsService.FindMonthlyTotalPricesByMerchant:output_type -> pb.category.ApiResponseCategoryMonthlyTotalPrice
	10, // 17: pb.category.CategoryStatsService.FindYearlyTotalPricesByMerchant:output_type -> pb.category.ApiResponseCategoryYearlyTotalPrice
	11, // 18: pb.category.CategoryStatsService.FindMonthPrice:output_type -> pb.category.ApiResponseCategoryMonthPrice
	12, // 19: pb.category.CategoryStatsService.FindYearPrice:output_type -> pb.category.ApiResponseCategoryYearPrice
	11, // 20: pb.category.CategoryStatsService.FindMonthPriceByMerchant:output_type -> pb.category.ApiResponseCategoryMonthPrice
	12, // 21: pb.category.CategoryStatsService.FindYearPriceByMerchant:output_type -> pb.category.ApiResponseCategoryYearPrice
	11, // 22: pb.category.CategoryStatsService.FindMonthPriceById:output_type -> pb.category.ApiResponseCategoryMonthPrice
	12, // 23: pb.category.CategoryStatsService.FindYearPriceById:output_type -> pb.category.ApiResponseCategoryYearPrice
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_category_category_stats_proto_init() }
func file_category_category_stats_proto_init() {
	if File_category_category_stats_proto != nil {
		return
	}
	file_category_category_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_category_stats_proto_rawDesc), len(file_category_category_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_category_stats_proto_goTypes,
		DependencyIndexes: file_category_category_stats_proto_depIdxs,
	}.Build()
	File_category_category_stats_proto = out.File
	file_category_category_stats_proto_goTypes = nil
	file_category_category_stats_proto_depIdxs = nil
}
