// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: category/query.proto

package category

import (
	api "github.com/MamangRust/monolith-graphql-pointofsale-pb/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllCategoryRequest) Reset() {
	*x = FindAllCategoryRequest{}
	mi := &file_category_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllCategoryRequest) ProtoMessage() {}

func (x *FindAllCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllCategoryRequest.ProtoReflect.Descriptor instead.
func (*FindAllCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllCategoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllCategoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllCategoryRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdCategoryRequest) Reset() {
	*x = FindByIdCategoryRequest{}
	mi := &file_category_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdCategoryRequest) ProtoMessage() {}

func (x *FindByIdCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdCategoryRequest.ProtoReflect.Descriptor instead.
func (*FindByIdCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindByIdCategoryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SlugCategory  string                 `protobuf:"bytes,4,opt,name=slug_category,json=slugCategory,proto3" json:"slug_category,omitempty"`
	ImageCategory string                 `protobuf:"bytes,5,opt,name=image_category,json=imageCategory,proto3" json:"image_category,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	mi := &file_category_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_category_query_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryResponse) GetSlugCategory() string {
	if x != nil {
		return x.SlugCategory
	}
	return ""
}

func (x *CategoryResponse) GetImageCategory() string {
	if x != nil {
		return x.ImageCategory
	}
	return ""
}

func (x *CategoryResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CategoryResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CategoryResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SlugCategory  string                  `protobuf:"bytes,4,opt,name=slug_category,json=slugCategory,proto3" json:"slug_category,omitempty"`
	ImageCategory string                  `protobuf:"bytes,5,opt,name=image_category,json=imageCategory,proto3" json:"image_category,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryResponseDeleteAt) Reset() {
	*x = CategoryResponseDeleteAt{}
	mi := &file_category_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponseDeleteAt) ProtoMessage() {}

func (x *CategoryResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_category_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*CategoryResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_category_query_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryResponseDeleteAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryResponseDeleteAt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryResponseDeleteAt) GetSlugCategory() string {
	if x != nil {
		return x.SlugCategory
	}
	return ""
}

func (x *CategoryResponseDeleteAt) GetImageCategory() string {
	if x != nil {
		return x.ImageCategory
	}
	return ""
}

func (x *CategoryResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CategoryResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CategoryResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CategoryResponse      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCategory) Reset() {
	*x = ApiResponseCategory{}
	mi := &file_category_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCategory) ProtoMessage() {}

func (x *ApiResponseCategory) ProtoReflect() protoreflect.Message {
	mi := &file_category_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCategory.ProtoReflect.Descriptor instead.
func (*ApiResponseCategory) Descriptor() ([]byte, []int) {
	return file_category_query_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponseCategory) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCategory) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCategory) GetData() *CategoryResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCategoryDeleteAt struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        string                    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CategoryResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCategoryDeleteAt) Reset() {
	*x = ApiResponseCategoryDeleteAt{}
	mi := &file_category_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCategoryDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCategoryDeleteAt) ProtoMessage() {}

func (x *ApiResponseCategoryDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_category_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCategoryDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseCategoryDeleteAt) Descriptor() ([]byte, []int) {
	return file_category_query_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponseCategoryDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCategoryDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCategoryDeleteAt) GetData() *CategoryResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CategoryResponse    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesCategory) Reset() {
	*x = ApiResponsesCategory{}
	mi := &file_category_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesCategory) ProtoMessage() {}

func (x *ApiResponsesCategory) ProtoReflect() protoreflect.Message {
	mi := &file_category_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesCategory.ProtoReflect.Descriptor instead.
func (*ApiResponsesCategory) Descriptor() ([]byte, []int) {
	return file_category_query_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponsesCategory) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesCategory) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesCategory) GetData() []*CategoryResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCategoryDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCategoryDelete) Reset() {
	*x = ApiResponseCategoryDelete{}
	mi := &file_category_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCategoryDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCategoryDelete) ProtoMessage() {}

func (x *ApiResponseCategoryDelete) ProtoReflect() protoreflect.Message {
	mi := &file_category_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCategoryDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseCategoryDelete) Descriptor() ([]byte, []int) {
	return file_category_query_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponseCategoryDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCategoryDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseCategoryAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCategoryAll) Reset() {
	*x = ApiResponseCategoryAll{}
	mi := &file_category_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCategoryAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCategoryAll) ProtoMessage() {}

func (x *ApiResponseCategoryAll) ProtoReflect() protoreflect.Message {
	mi := &file_category_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCategoryAll.ProtoReflect.Descriptor instead.
func (*ApiResponseCategoryAll) Descriptor() ([]byte, []int) {
	return file_category_query_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponseCategoryAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCategoryAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationCategoryDeleteAt struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CategoryResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *api.PaginationMeta         `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationCategoryDeleteAt) Reset() {
	*x = ApiResponsePaginationCategoryDeleteAt{}
	mi := &file_category_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationCategoryDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationCategoryDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationCategoryDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_category_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationCategoryDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationCategoryDeleteAt) Descriptor() ([]byte, []int) {
	return file_category_query_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponsePaginationCategoryDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationCategoryDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationCategoryDeleteAt) GetData() []*CategoryResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationCategoryDeleteAt) GetPagination() *api.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CategoryResponse    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *api.PaginationMeta    `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationCategory) Reset() {
	*x = ApiResponsePaginationCategory{}
	mi := &file_category_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationCategory) ProtoMessage() {}

func (x *ApiResponsePaginationCategory) ProtoReflect() protoreflect.Message {
	mi := &file_category_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationCategory.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationCategory) Descriptor() ([]byte, []int) {
	return file_category_query_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponsePaginationCategory) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationCategory) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationCategory) GetData() []*CategoryResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationCategory) GetPagination() *api.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_category_query_proto protoreflect.FileDescriptor

const file_category_query_proto_rawDesc = "" +
	"\n" +
	"\x14category/query.proto\x12\vpb.category\x1a\rapi/api.proto\x1a\x1egoogle/protobuf/wrappers.proto\"a\n" +
	"\x16FindAllCategoryRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\")\n" +
	"\x17FindByIdCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xe2\x01\n" +
	"\x10CategoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rslug_category\x18\x04 \x01(\tR\fslugCategory\x12%\n" +
	"\x0eimage_category\x18\x05 \x01(\tR\rimageCategory\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xa7\x02\n" +
	"\x18CategoryResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rslug_category\x18\x04 \x01(\tR\fslugCategory\x12%\n" +
	"\x0eimage_category\x18\x05 \x01(\tR\rimageCategory\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"z\n" +
	"\x13ApiResponseCategory\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x01(\v2\x1d.pb.category.CategoryResponseR\x04data\"\x8a\x01\n" +
	"\x1bApiResponseCategoryDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x01(\v2%.pb.category.CategoryResponseDeleteAtR\x04data\"{\n" +
	"\x14ApiResponsesCategory\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.category.CategoryResponseR\x04data\"M\n" +
	"\x19ApiResponseCategoryDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x16ApiResponseCategoryAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcc\x01\n" +
	"%ApiResponsePaginationCategoryDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x03(\v2%.pb.category.CategoryResponseDeleteAtR\x04data\x126\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x16.pb.api.PaginationMetaR\n" +
	"pagination\"\xbc\x01\n" +
	"\x1dApiResponsePaginationCategory\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.category.CategoryResponseR\x04data\x126\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x16.pb.api.PaginationMetaR\n" +
	"pagination2\x99\x03\n" +
	"\x14CategoryQueryService\x12Z\n" +
	"\aFindAll\x12#.pb.category.FindAllCategoryRequest\x1a*.pb.category.ApiResponsePaginationCategory\x12R\n" +
	"\bFindById\x12$.pb.category.FindByIdCategoryRequest\x1a .pb.category.ApiResponseCategory\x12g\n" +
	"\fFindByActive\x12#.pb.category.FindAllCategoryRequest\x1a2.pb.category.ApiResponsePaginationCategoryDeleteAt\x12h\n" +
	"\rFindByTrashed\x12#.pb.category.FindAllCategoryRequest\x1a2.pb.category.ApiResponsePaginationCategoryDeleteAtB@Z>github.com/MamangRust/monolith-graphql-pointofsale-pb/categoryb\x06proto3"

var (
	file_category_query_proto_rawDescOnce sync.Once
	file_category_query_proto_rawDescData []byte
)

func file_category_query_proto_rawDescGZIP() []byte {
	file_category_query_proto_rawDescOnce.Do(func() {
		file_category_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_query_proto_rawDesc), len(file_category_query_proto_rawDesc)))
	})
	return file_category_query_proto_rawDescData
}

var file_category_query_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_category_query_proto_goTypes = []any{
	(*FindAllCategoryRequest)(nil),                // 0: pb.category.FindAllCategoryRequest
	(*FindByIdCategoryRequest)(nil),               // 1: pb.category.FindByIdCategoryRequest
	(*CategoryResponse)(nil),                      // 2: pb.category.CategoryResponse
	(*CategoryResponseDeleteAt)(nil),              // 3: pb.category.CategoryResponseDeleteAt
	(*ApiResponseCategory)(nil),                   // 4: pb.category.ApiResponseCategory
	(*ApiResponseCategoryDeleteAt)(nil),           // 5: pb.category.ApiResponseCategoryDeleteAt
	(*ApiResponsesCategory)(nil),                  // 6: pb.category.ApiResponsesCategory
	(*ApiResponseCategoryDelete)(nil),             // 7: pb.category.ApiResponseCategoryDelete
	(*ApiResponseCategoryAll)(nil),                // 8: pb.category.ApiResponseCategoryAll
	(*ApiResponsePaginationCategoryDeleteAt)(nil), // 9: pb.category.ApiResponsePaginationCategoryDeleteAt
	(*ApiResponsePaginationCategory)(nil),         // 10: pb.category.ApiResponsePaginationCategory
	(*wrapperspb.StringValue)(nil),                // 11: google.protobuf.StringValue
	(*api.PaginationMeta)(nil),                    // 12: pb.api.PaginationMeta
}
var file_category_query_proto_depIdxs = []int32{
	11, // 0: pb.category.CategoryResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	2,  // 1: pb.category.ApiResponseCategory.data:type_name -> pb.category.CategoryResponse
	3,  // 2: pb.category.ApiResponseCategoryDeleteAt.data:type_name -> pb.category.CategoryResponseDeleteAt
	2,  // 3: pb.category.ApiResponsesCategory.data:type_name -> pb.category.CategoryResponse
	3,  // 4: pb.category.ApiResponsePaginationCategoryDeleteAt.data:type_name -> pb.category.CategoryResponseDeleteAt
	12, // 5: pb.category.ApiResponsePaginationCategoryDeleteAt.pagination:type_name -> pb.api.PaginationMeta
	2,  // 6: pb.category.ApiResponsePaginationCategory.data:type_name -> pb.category.CategoryResponse
	12, // 7: pb.category.ApiResponsePaginationCategory.pagination:type_name -> pb.api.PaginationMeta
	0,  // 8: pb.category.CategoryQueryService.FindAll:input_type -> pb.category.FindAllCategoryRequest
	1,  // 9: pb.category.CategoryQueryService.FindById:input_type -> pb.category.FindByIdCategoryRequest
	0,  // 10: pb.category.CategoryQueryService.FindByActive:input_type -> pb.category.FindAllCategoryRequest
	0,  // 11: pb.category.CategoryQueryService.FindByTrashed:input_type -> pb.category.FindAllCategoryRequest
	10, // 12: pb.category.CategoryQueryService.FindAll:output_type -> pb.category.ApiResponsePaginationCategory
	4,  // 13: pb.category.CategoryQueryService.FindById:output_type -> pb.category.ApiResponseCategory
	9,  // 14: pb.category.CategoryQueryService.FindByActive:output_type -> pb.category.ApiResponsePaginationCategoryDeleteAt
	9,  // 15: pb.category.CategoryQueryService.FindByTrashed:output_type -> pb.category.ApiResponsePaginationCategoryDeleteAt
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_category_query_proto_init() }
func file_category_query_proto_init() {
	if File_category_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_query_proto_rawDesc), len(file_category_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_query_proto_goTypes,
		DependencyIndexes: file_category_query_proto_depIdxs,
		MessageInfos:      file_category_query_proto_msgTypes,
	}.Build()
	File_category_query_proto = out.File
	file_category_query_proto_goTypes = nil
	file_category_query_proto_depIdxs = nil
}
