// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: category/stats.proto

package category

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CategoryStatsService_FindMonthlyTotalPrices_FullMethodName           = "/pb.category.CategoryStatsService/FindMonthlyTotalPrices"
	CategoryStatsService_FindYearlyTotalPrices_FullMethodName            = "/pb.category.CategoryStatsService/FindYearlyTotalPrices"
	CategoryStatsService_FindMonthlyTotalPricesById_FullMethodName       = "/pb.category.CategoryStatsService/FindMonthlyTotalPricesById"
	CategoryStatsService_FindYearlyTotalPricesById_FullMethodName        = "/pb.category.CategoryStatsService/FindYearlyTotalPricesById"
	CategoryStatsService_FindMonthlyTotalPricesByMerchant_FullMethodName = "/pb.category.CategoryStatsService/FindMonthlyTotalPricesByMerchant"
	CategoryStatsService_FindYearlyTotalPricesByMerchant_FullMethodName  = "/pb.category.CategoryStatsService/FindYearlyTotalPricesByMerchant"
	CategoryStatsService_FindMonthPrice_FullMethodName                   = "/pb.category.CategoryStatsService/FindMonthPrice"
	CategoryStatsService_FindYearPrice_FullMethodName                    = "/pb.category.CategoryStatsService/FindYearPrice"
	CategoryStatsService_FindMonthPriceByMerchant_FullMethodName         = "/pb.category.CategoryStatsService/FindMonthPriceByMerchant"
	CategoryStatsService_FindYearPriceByMerchant_FullMethodName          = "/pb.category.CategoryStatsService/FindYearPriceByMerchant"
	CategoryStatsService_FindMonthPriceById_FullMethodName               = "/pb.category.CategoryStatsService/FindMonthPriceById"
	CategoryStatsService_FindYearPriceById_FullMethodName                = "/pb.category.CategoryStatsService/FindYearPriceById"
)

// CategoryStatsServiceClient is the client API for CategoryStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CategoryStatsServiceClient interface {
	FindMonthlyTotalPrices(ctx context.Context, in *FindYearMonthTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPrices(ctx context.Context, in *FindYearTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthlyTotalPricesById(ctx context.Context, in *FindYearMonthTotalPriceById, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesById(ctx context.Context, in *FindYearTotalPriceById, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthlyTotalPricesByMerchant(ctx context.Context, in *FindYearMonthTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesByMerchant(ctx context.Context, in *FindYearTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error)
	FindYearPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error)
	FindMonthPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error)
	FindMonthPriceById(ctx context.Context, in *FindYearCategoryById, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceById(ctx context.Context, in *FindYearCategoryById, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error)
}

type categoryStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCategoryStatsServiceClient(cc grpc.ClientConnInterface) CategoryStatsServiceClient {
	return &categoryStatsServiceClient{cc}
}

func (c *categoryStatsServiceClient) FindMonthlyTotalPrices(ctx context.Context, in *FindYearMonthTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthlyTotalPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindYearlyTotalPrices(ctx context.Context, in *FindYearTotalPrices, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindYearlyTotalPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindMonthlyTotalPricesById(ctx context.Context, in *FindYearMonthTotalPriceById, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthlyTotalPricesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindYearlyTotalPricesById(ctx context.Context, in *FindYearTotalPriceById, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindYearlyTotalPricesById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindMonthlyTotalPricesByMerchant(ctx context.Context, in *FindYearMonthTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthlyTotalPricesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindYearlyTotalPricesByMerchant(ctx context.Context, in *FindYearTotalPriceByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearlyTotalPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearlyTotalPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindYearlyTotalPricesByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindMonthPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindYearPrice(ctx context.Context, in *FindYearCategory, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindYearPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindMonthPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindYearPriceByMerchant(ctx context.Context, in *FindYearCategoryByMerchant, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindYearPriceByMerchant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindMonthPriceById(ctx context.Context, in *FindYearCategoryById, opts ...grpc.CallOption) (*ApiResponseCategoryMonthPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryMonthPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindMonthPriceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryStatsServiceClient) FindYearPriceById(ctx context.Context, in *FindYearCategoryById, opts ...grpc.CallOption) (*ApiResponseCategoryYearPrice, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseCategoryYearPrice)
	err := c.cc.Invoke(ctx, CategoryStatsService_FindYearPriceById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryStatsServiceServer is the server API for CategoryStatsService service.
// All implementations must embed UnimplementedCategoryStatsServiceServer
// for forward compatibility.
type CategoryStatsServiceServer interface {
	FindMonthlyTotalPrices(context.Context, *FindYearMonthTotalPrices) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPrices(context.Context, *FindYearTotalPrices) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthlyTotalPricesById(context.Context, *FindYearMonthTotalPriceById) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesById(context.Context, *FindYearTotalPriceById) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthlyTotalPricesByMerchant(context.Context, *FindYearMonthTotalPriceByMerchant) (*ApiResponseCategoryMonthlyTotalPrice, error)
	FindYearlyTotalPricesByMerchant(context.Context, *FindYearTotalPriceByMerchant) (*ApiResponseCategoryYearlyTotalPrice, error)
	FindMonthPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryMonthPrice, error)
	FindYearPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryYearPrice, error)
	FindMonthPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryYearPrice, error)
	FindMonthPriceById(context.Context, *FindYearCategoryById) (*ApiResponseCategoryMonthPrice, error)
	FindYearPriceById(context.Context, *FindYearCategoryById) (*ApiResponseCategoryYearPrice, error)
	mustEmbedUnimplementedCategoryStatsServiceServer()
}

// UnimplementedCategoryStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCategoryStatsServiceServer struct{}

func (UnimplementedCategoryStatsServiceServer) FindMonthlyTotalPrices(context.Context, *FindYearMonthTotalPrices) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthlyTotalPrices not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindYearlyTotalPrices(context.Context, *FindYearTotalPrices) (*ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearlyTotalPrices not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindMonthlyTotalPricesById(context.Context, *FindYearMonthTotalPriceById) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthlyTotalPricesById not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindYearlyTotalPricesById(context.Context, *FindYearTotalPriceById) (*ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearlyTotalPricesById not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindMonthlyTotalPricesByMerchant(context.Context, *FindYearMonthTotalPriceByMerchant) (*ApiResponseCategoryMonthlyTotalPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthlyTotalPricesByMerchant not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindYearlyTotalPricesByMerchant(context.Context, *FindYearTotalPriceByMerchant) (*ApiResponseCategoryYearlyTotalPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearlyTotalPricesByMerchant not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindMonthPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryMonthPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthPrice not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindYearPrice(context.Context, *FindYearCategory) (*ApiResponseCategoryYearPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearPrice not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindMonthPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryMonthPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthPriceByMerchant not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindYearPriceByMerchant(context.Context, *FindYearCategoryByMerchant) (*ApiResponseCategoryYearPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearPriceByMerchant not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindMonthPriceById(context.Context, *FindYearCategoryById) (*ApiResponseCategoryMonthPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMonthPriceById not implemented")
}
func (UnimplementedCategoryStatsServiceServer) FindYearPriceById(context.Context, *FindYearCategoryById) (*ApiResponseCategoryYearPrice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindYearPriceById not implemented")
}
func (UnimplementedCategoryStatsServiceServer) mustEmbedUnimplementedCategoryStatsServiceServer() {}
func (UnimplementedCategoryStatsServiceServer) testEmbeddedByValue()                              {}

// UnsafeCategoryStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CategoryStatsServiceServer will
// result in compilation errors.
type UnsafeCategoryStatsServiceServer interface {
	mustEmbedUnimplementedCategoryStatsServiceServer()
}

func RegisterCategoryStatsServiceServer(s grpc.ServiceRegistrar, srv CategoryStatsServiceServer) {
	// If the following call pancis, it indicates UnimplementedCategoryStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CategoryStatsService_ServiceDesc, srv)
}

func _CategoryStatsService_FindMonthlyTotalPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthlyTotalPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthlyTotalPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthlyTotalPrices(ctx, req.(*FindYearMonthTotalPrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindYearlyTotalPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalPrices)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindYearlyTotalPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindYearlyTotalPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindYearlyTotalPrices(ctx, req.(*FindYearTotalPrices))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindMonthlyTotalPricesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalPriceById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthlyTotalPricesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthlyTotalPricesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthlyTotalPricesById(ctx, req.(*FindYearMonthTotalPriceById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindYearlyTotalPricesById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalPriceById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindYearlyTotalPricesById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindYearlyTotalPricesById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindYearlyTotalPricesById(ctx, req.(*FindYearTotalPriceById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindMonthlyTotalPricesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearMonthTotalPriceByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthlyTotalPricesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthlyTotalPricesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthlyTotalPricesByMerchant(ctx, req.(*FindYearMonthTotalPriceByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindYearlyTotalPricesByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearTotalPriceByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindYearlyTotalPricesByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindYearlyTotalPricesByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindYearlyTotalPricesByMerchant(ctx, req.(*FindYearTotalPriceByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindMonthPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthPrice(ctx, req.(*FindYearCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindYearPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindYearPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindYearPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindYearPrice(ctx, req.(*FindYearCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindMonthPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthPriceByMerchant(ctx, req.(*FindYearCategoryByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindYearPriceByMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryByMerchant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindYearPriceByMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindYearPriceByMerchant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindYearPriceByMerchant(ctx, req.(*FindYearCategoryByMerchant))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindMonthPriceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindMonthPriceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindMonthPriceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindMonthPriceById(ctx, req.(*FindYearCategoryById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CategoryStatsService_FindYearPriceById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindYearCategoryById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryStatsServiceServer).FindYearPriceById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CategoryStatsService_FindYearPriceById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryStatsServiceServer).FindYearPriceById(ctx, req.(*FindYearCategoryById))
	}
	return interceptor(ctx, in, info, handler)
}

// CategoryStatsService_ServiceDesc is the grpc.ServiceDesc for CategoryStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CategoryStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.category.CategoryStatsService",
	HandlerType: (*CategoryStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindMonthlyTotalPrices",
			Handler:    _CategoryStatsService_FindMonthlyTotalPrices_Handler,
		},
		{
			MethodName: "FindYearlyTotalPrices",
			Handler:    _CategoryStatsService_FindYearlyTotalPrices_Handler,
		},
		{
			MethodName: "FindMonthlyTotalPricesById",
			Handler:    _CategoryStatsService_FindMonthlyTotalPricesById_Handler,
		},
		{
			MethodName: "FindYearlyTotalPricesById",
			Handler:    _CategoryStatsService_FindYearlyTotalPricesById_Handler,
		},
		{
			MethodName: "FindMonthlyTotalPricesByMerchant",
			Handler:    _CategoryStatsService_FindMonthlyTotalPricesByMerchant_Handler,
		},
		{
			MethodName: "FindYearlyTotalPricesByMerchant",
			Handler:    _CategoryStatsService_FindYearlyTotalPricesByMerchant_Handler,
		},
		{
			MethodName: "FindMonthPrice",
			Handler:    _CategoryStatsService_FindMonthPrice_Handler,
		},
		{
			MethodName: "FindYearPrice",
			Handler:    _CategoryStatsService_FindYearPrice_Handler,
		},
		{
			MethodName: "FindMonthPriceByMerchant",
			Handler:    _CategoryStatsService_FindMonthPriceByMerchant_Handler,
		},
		{
			MethodName: "FindYearPriceByMerchant",
			Handler:    _CategoryStatsService_FindYearPriceByMerchant_Handler,
		},
		{
			MethodName: "FindMonthPriceById",
			Handler:    _CategoryStatsService_FindMonthPriceById_Handler,
		},
		{
			MethodName: "FindYearPriceById",
			Handler:    _CategoryStatsService_FindYearPriceById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "category/stats.proto",
}
