syntax = "proto3";

package pb.merchant_document;

option go_package = "github.com/MamangRust/monolith-graphql-pointofsale-pb/merchant_document";

import "google/protobuf/empty.proto";
import "merchant_document/query.proto";

message CreateMerchantDocumentRequest {
  int32 merchant_id = 1;
  string document_type = 2;
  string document_url = 3;
}

message UpdateMerchantDocumentRequest {
  int32 document_id = 1;
  int32 merchant_id = 2;
  string document_type = 3;
  string document_url = 4;
  string note = 5;
  string status = 6;
}

message UpdateMerchantDocumentStatusRequest {
  int32 document_id = 1;
  int32 merchant_id = 2;
  string note = 3;
  string status = 4;
}

message TrashedMerchantDocumentRequest {
  int32 document_id = 1;
}

message RestoreMerchantDocumentRequest {
  int32 document_id = 1;
}

message DeleteMerchantDocumentPermanentRequest {
  int32 document_id = 1;
}

service MerchantDocumentCommandService {
  rpc Create(CreateMerchantDocumentRequest) returns (ApiResponseMerchantDocument);
  rpc Update(UpdateMerchantDocumentRequest) returns (ApiResponseMerchantDocument);
  rpc UpdateStatus(UpdateMerchantDocumentStatusRequest) returns (ApiResponseMerchantDocument);

  rpc Trashed(TrashedMerchantDocumentRequest) returns (ApiResponseMerchantDocument);
  rpc Restore(RestoreMerchantDocumentRequest) returns (ApiResponseMerchantDocument);
  rpc DeletePermanent(DeleteMerchantDocumentPermanentRequest) returns (ApiResponseMerchantDocumentDelete);

  rpc RestoreAll(google.protobuf.Empty) returns (ApiResponseMerchantDocumentAll);
  rpc DeleteAllPermanent(google.protobuf.Empty) returns (ApiResponseMerchantDocumentAll);
}
