syntax = "proto3";

package pb.category;

option go_package = "github.com/MamangRust/monolith-graphql-pointofsale-pb/category";

message FindYearCategory {
  int32 year = 1;
}

message FindYearCategoryByMerchant {
  int32 merchant_id = 1;
  int32 year = 2;
}

message FindYearCategoryById {
  int32 category_id = 1;
  int32 year = 2;
}

message FindYearMonthTotalPrices {
  int32 year = 1;
  int32 month = 2;
}

message FindYearTotalPrices {
  int32 year = 1;
}

message FindYearMonthTotalPriceById {
  int32 year = 1;
  int32 month = 2;
  int32 category_id = 3;
}

message FindYearTotalPriceById {
  int32 year = 1;
  int32 category_id = 2;
}

message FindYearMonthTotalPriceByMerchant {
  int32 year = 1;
  int32 month = 2;
  int32 merchant_id = 3;
}

message FindYearTotalPriceByMerchant {
  int32 year = 1;
  int32 merchant_id = 2;
}

message CategoryMonthPriceResponse {
  string month = 1;
  int32 category_id = 2;
  string category_name = 3;
  int32 order_count = 4;
  int32 items_sold = 5;
  int32 total_revenue = 6;
}

message CategoryYearPriceResponse {
  string year = 1;
  int32 category_id = 2;
  string category_name = 3;
  int32 order_count = 4;
  int32 items_sold = 5;
  int32 total_revenue = 6;
  int32 unique_products_sold = 7;
}

message CategoriesMonthlyTotalPriceResponse {
  string year = 1;
  string month = 2;
  int32 total_revenue = 3;
}

message CategoriesYearlyTotalPriceResponse {
  string year = 1;
  int32 total_revenue = 2;
}

message ApiResponseCategoryMonthPrice {
  string status = 1;
  string message = 2;
  repeated CategoryMonthPriceResponse data = 3;
}

message ApiResponseCategoryYearPrice {
  string status = 1;
  string message = 2;
  repeated CategoryYearPriceResponse data = 3;
}

message ApiResponseCategoryMonthlyTotalPrice {
  string status = 1;
  string message = 2;
  repeated CategoriesMonthlyTotalPriceResponse data = 3;
}

message ApiResponseCategoryYearlyTotalPrice {
  string status = 1;
  string message = 2;
  repeated CategoriesYearlyTotalPriceResponse data = 3;
}

service CategoryStatsService {
  rpc FindMonthlyTotalPrices(FindYearMonthTotalPrices) returns (ApiResponseCategoryMonthlyTotalPrice);
  rpc FindYearlyTotalPrices(FindYearTotalPrices) returns (ApiResponseCategoryYearlyTotalPrice);

  rpc FindMonthlyTotalPricesById(FindYearMonthTotalPriceById) returns (ApiResponseCategoryMonthlyTotalPrice);
  rpc FindYearlyTotalPricesById(FindYearTotalPriceById) returns (ApiResponseCategoryYearlyTotalPrice);

  rpc FindMonthlyTotalPricesByMerchant(FindYearMonthTotalPriceByMerchant) returns (ApiResponseCategoryMonthlyTotalPrice);
  rpc FindYearlyTotalPricesByMerchant(FindYearTotalPriceByMerchant) returns (ApiResponseCategoryYearlyTotalPrice);

  rpc FindMonthPrice(FindYearCategory) returns (ApiResponseCategoryMonthPrice);
  rpc FindYearPrice(FindYearCategory) returns (ApiResponseCategoryYearPrice);
  rpc FindMonthPriceByMerchant(FindYearCategoryByMerchant) returns (ApiResponseCategoryMonthPrice);
  rpc FindYearPriceByMerchant(FindYearCategoryByMerchant) returns (ApiResponseCategoryYearPrice);

  rpc FindMonthPriceById(FindYearCategoryById) returns (ApiResponseCategoryMonthPrice);
  rpc FindYearPriceById(FindYearCategoryById) returns (ApiResponseCategoryYearPrice);
}
