// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: order/order_stats.proto

package order

import (
	_ "github.com/MamangRust/monolith-graphql-pointofsale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_order_order_stats_proto protoreflect.FileDescriptor

const file_order_order_stats_proto_rawDesc = "" +
	"\n" +
	"\x17order/order_stats.proto\x12\bpb.order\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18order/order_common.proto2\xc9\b\n" +
	"\x11OrderStatsService\x12o\n" +
	"\x17FindMonthlyTotalRevenue\x12#.pb.order.FindYearMonthTotalRevenue\x1a-.pb.order.ApiResponseOrderMonthlyTotalRevenue\"\x00\x12h\n" +
	"\x16FindYearlyTotalRevenue\x12\x1e.pb.order.FindYearTotalRevenue\x1a,.pb.order.ApiResponseOrderYearlyTotalRevenue\"\x00\x12w\n" +
	"\x1bFindMonthlyTotalRevenueById\x12'.pb.order.FindYearMonthTotalRevenueById\x1a-.pb.order.ApiResponseOrderMonthlyTotalRevenue\"\x00\x12p\n" +
	"\x1aFindYearlyTotalRevenueById\x12\".pb.order.FindYearTotalRevenueById\x1a,.pb.order.ApiResponseOrderYearlyTotalRevenue\"\x00\x12\x83\x01\n" +
	"!FindMonthlyTotalRevenueByMerchant\x12-.pb.order.FindYearMonthTotalRevenueByMerchant\x1a-.pb.order.ApiResponseOrderMonthlyTotalRevenue\"\x00\x12|\n" +
	" FindYearlyTotalRevenueByMerchant\x12(.pb.order.FindYearTotalRevenueByMerchant\x1a,.pb.order.ApiResponseOrderYearlyTotalRevenue\"\x00\x12P\n" +
	"\x12FindMonthlyRevenue\x12\x17.pb.order.FindYearOrder\x1a!.pb.order.ApiResponseOrderMonthly\x12N\n" +
	"\x11FindYearlyRevenue\x12\x17.pb.order.FindYearOrder\x1a .pb.order.ApiResponseOrderYearly\x12d\n" +
	"\x1cFindMonthlyRevenueByMerchant\x12!.pb.order.FindYearOrderByMerchant\x1a!.pb.order.ApiResponseOrderMonthly\x12b\n" +
	"\x1bFindYearlyRevenueByMerchant\x12!.pb.order.FindYearOrderByMerchant\x1a .pb.order.ApiResponseOrderYearlyB=Z;github.com/MamangRust/monolith-graphql-pointofsale-pb/orderb\x06proto3"

var file_order_order_stats_proto_goTypes = []any{
	(*FindYearMonthTotalRevenue)(nil),           // 0: pb.order.FindYearMonthTotalRevenue
	(*FindYearTotalRevenue)(nil),                // 1: pb.order.FindYearTotalRevenue
	(*FindYearMonthTotalRevenueById)(nil),       // 2: pb.order.FindYearMonthTotalRevenueById
	(*FindYearTotalRevenueById)(nil),            // 3: pb.order.FindYearTotalRevenueById
	(*FindYearMonthTotalRevenueByMerchant)(nil), // 4: pb.order.FindYearMonthTotalRevenueByMerchant
	(*FindYearTotalRevenueByMerchant)(nil),      // 5: pb.order.FindYearTotalRevenueByMerchant
	(*FindYearOrder)(nil),                       // 6: pb.order.FindYearOrder
	(*FindYearOrderByMerchant)(nil),             // 7: pb.order.FindYearOrderByMerchant
	(*ApiResponseOrderMonthlyTotalRevenue)(nil), // 8: pb.order.ApiResponseOrderMonthlyTotalRevenue
	(*ApiResponseOrderYearlyTotalRevenue)(nil),  // 9: pb.order.ApiResponseOrderYearlyTotalRevenue
	(*ApiResponseOrderMonthly)(nil),             // 10: pb.order.ApiResponseOrderMonthly
	(*ApiResponseOrderYearly)(nil),              // 11: pb.order.ApiResponseOrderYearly
}
var file_order_order_stats_proto_depIdxs = []int32{
	0,  // 0: pb.order.OrderStatsService.FindMonthlyTotalRevenue:input_type -> pb.order.FindYearMonthTotalRevenue
	1,  // 1: pb.order.OrderStatsService.FindYearlyTotalRevenue:input_type -> pb.order.FindYearTotalRevenue
	2,  // 2: pb.order.OrderStatsService.FindMonthlyTotalRevenueById:input_type -> pb.order.FindYearMonthTotalRevenueById
	3,  // 3: pb.order.OrderStatsService.FindYearlyTotalRevenueById:input_type -> pb.order.FindYearTotalRevenueById
	4,  // 4: pb.order.OrderStatsService.FindMonthlyTotalRevenueByMerchant:input_type -> pb.order.FindYearMonthTotalRevenueByMerchant
	5,  // 5: pb.order.OrderStatsService.FindYearlyTotalRevenueByMerchant:input_type -> pb.order.FindYearTotalRevenueByMerchant
	6,  // 6: pb.order.OrderStatsService.FindMonthlyRevenue:input_type -> pb.order.FindYearOrder
	6,  // 7: pb.order.OrderStatsService.FindYearlyRevenue:input_type -> pb.order.FindYearOrder
	7,  // 8: pb.order.OrderStatsService.FindMonthlyRevenueByMerchant:input_type -> pb.order.FindYearOrderByMerchant
	7,  // 9: pb.order.OrderStatsService.FindYearlyRevenueByMerchant:input_type -> pb.order.FindYearOrderByMerchant
	8,  // 10: pb.order.OrderStatsService.FindMonthlyTotalRevenue:output_type -> pb.order.ApiResponseOrderMonthlyTotalRevenue
	9,  // 11: pb.order.OrderStatsService.FindYearlyTotalRevenue:output_type -> pb.order.ApiResponseOrderYearlyTotalRevenue
	8,  // 12: pb.order.OrderStatsService.FindMonthlyTotalRevenueById:output_type -> pb.order.ApiResponseOrderMonthlyTotalRevenue
	9,  // 13: pb.order.OrderStatsService.FindYearlyTotalRevenueById:output_type -> pb.order.ApiResponseOrderYearlyTotalRevenue
	8,  // 14: pb.order.OrderStatsService.FindMonthlyTotalRevenueByMerchant:output_type -> pb.order.ApiResponseOrderMonthlyTotalRevenue
	9,  // 15: pb.order.OrderStatsService.FindYearlyTotalRevenueByMerchant:output_type -> pb.order.ApiResponseOrderYearlyTotalRevenue
	10, // 16: pb.order.OrderStatsService.FindMonthlyRevenue:output_type -> pb.order.ApiResponseOrderMonthly
	11, // 17: pb.order.OrderStatsService.FindYearlyRevenue:output_type -> pb.order.ApiResponseOrderYearly
	10, // 18: pb.order.OrderStatsService.FindMonthlyRevenueByMerchant:output_type -> pb.order.ApiResponseOrderMonthly
	11, // 19: pb.order.OrderStatsService.FindYearlyRevenueByMerchant:output_type -> pb.order.ApiResponseOrderYearly
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_order_order_stats_proto_init() }
func file_order_order_stats_proto_init() {
	if File_order_order_stats_proto != nil {
		return
	}
	file_order_order_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_stats_proto_rawDesc), len(file_order_order_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_order_stats_proto_goTypes,
		DependencyIndexes: file_order_order_stats_proto_depIdxs,
	}.Build()
	File_order_order_stats_proto = out.File
	file_order_order_stats_proto_goTypes = nil
	file_order_order_stats_proto_depIdxs = nil
}
