// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: order/query.proto

package order

import (
	api "github.com/MamangRust/monolith-graphql-pointofsale-pb/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllOrderRequest) Reset() {
	*x = FindAllOrderRequest{}
	mi := &file_order_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllOrderRequest) ProtoMessage() {}

func (x *FindAllOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllOrderRequest.ProtoReflect.Descriptor instead.
func (*FindAllOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllOrderRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllOrderRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllOrderRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindAllOrderMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	MerchantId    int32                  `protobuf:"varint,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllOrderMerchantRequest) Reset() {
	*x = FindAllOrderMerchantRequest{}
	mi := &file_order_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllOrderMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllOrderMerchantRequest) ProtoMessage() {}

func (x *FindAllOrderMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllOrderMerchantRequest.ProtoReflect.Descriptor instead.
func (*FindAllOrderMerchantRequest) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllOrderMerchantRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllOrderMerchantRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllOrderMerchantRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *FindAllOrderMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type FindByIdOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdOrderRequest) Reset() {
	*x = FindByIdOrderRequest{}
	mi := &file_order_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdOrderRequest) ProtoMessage() {}

func (x *FindByIdOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdOrderRequest.ProtoReflect.Descriptor instead.
func (*FindByIdOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{2}
}

func (x *FindByIdOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CashierId     int32                  `protobuf:"varint,3,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	TotalPrice    int32                  `protobuf:"varint,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_order_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{3}
}

func (x *OrderResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderResponse) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *OrderResponse) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *OrderResponse) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type OrderResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    int32                   `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CashierId     int32                   `protobuf:"varint,3,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	TotalPrice    int32                   `protobuf:"varint,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponseDeleteAt) Reset() {
	*x = OrderResponseDeleteAt{}
	mi := &file_order_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponseDeleteAt) ProtoMessage() {}

func (x *OrderResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*OrderResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{4}
}

func (x *OrderResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderResponseDeleteAt) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *OrderResponseDeleteAt) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *OrderResponseDeleteAt) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *OrderResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *OrderResponse         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrder) Reset() {
	*x = ApiResponseOrder{}
	mi := &file_order_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrder) ProtoMessage() {}

func (x *ApiResponseOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrder.ProtoReflect.Descriptor instead.
func (*ApiResponseOrder) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponseOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrder) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseOrder) GetData() *OrderResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseOrderDeleteAt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *OrderResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderDeleteAt) Reset() {
	*x = ApiResponseOrderDeleteAt{}
	mi := &file_order_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderDeleteAt) ProtoMessage() {}

func (x *ApiResponseOrderDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderDeleteAt) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseOrderDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseOrderDeleteAt) GetData() *OrderResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderResponse       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesOrder) Reset() {
	*x = ApiResponsesOrder{}
	mi := &file_order_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesOrder) ProtoMessage() {}

func (x *ApiResponsesOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesOrder.ProtoReflect.Descriptor instead.
func (*ApiResponsesOrder) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponsesOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesOrder) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesOrder) GetData() []*OrderResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseOrderDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderDelete) Reset() {
	*x = ApiResponseOrderDelete{}
	mi := &file_order_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderDelete) ProtoMessage() {}

func (x *ApiResponseOrderDelete) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderDelete) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponseOrderDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseOrderAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderAll) Reset() {
	*x = ApiResponseOrderAll{}
	mi := &file_order_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderAll) ProtoMessage() {}

func (x *ApiResponseOrderAll) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderAll.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderAll) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponseOrderAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationOrderDeleteAt struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *api.PaginationMeta      `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationOrderDeleteAt) Reset() {
	*x = ApiResponsePaginationOrderDeleteAt{}
	mi := &file_order_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationOrderDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationOrderDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationOrderDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationOrderDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationOrderDeleteAt) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponsePaginationOrderDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationOrderDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationOrderDeleteAt) GetData() []*OrderResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationOrderDeleteAt) GetPagination() *api.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderResponse       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *api.PaginationMeta    `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationOrder) Reset() {
	*x = ApiResponsePaginationOrder{}
	mi := &file_order_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationOrder) ProtoMessage() {}

func (x *ApiResponsePaginationOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationOrder.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationOrder) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponsePaginationOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationOrder) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationOrder) GetData() []*OrderResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationOrder) GetPagination() *api.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_order_query_proto protoreflect.FileDescriptor

const file_order_query_proto_rawDesc = "" +
	"\n" +
	"\x11order/query.proto\x12\bpb.order\x1a\rapi/api.proto\x1a\x1egoogle/protobuf/wrappers.proto\"^\n" +
	"\x13FindAllOrderRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x87\x01\n" +
	"\x1bFindAllOrderMerchantRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\x05R\n" +
	"merchantId\"&\n" +
	"\x14FindByIdOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xbe\x01\n" +
	"\rOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x03 \x01(\x05R\tcashierId\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x05R\n" +
	"totalPrice\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\x83\x02\n" +
	"\x15OrderResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x03 \x01(\x05R\tcashierId\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x05R\n" +
	"totalPrice\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"q\n" +
	"\x10ApiResponseOrder\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.pb.order.OrderResponseR\x04data\"\x81\x01\n" +
	"\x18ApiResponseOrderDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x01(\v2\x1f.pb.order.OrderResponseDeleteAtR\x04data\"r\n" +
	"\x11ApiResponsesOrder\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.pb.order.OrderResponseR\x04data\"J\n" +
	"\x16ApiResponseOrderDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x13ApiResponseOrderAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc3\x01\n" +
	"\"ApiResponsePaginationOrderDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x03(\v2\x1f.pb.order.OrderResponseDeleteAtR\x04data\x126\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x16.pb.api.PaginationMetaR\n" +
	"pagination\"\xb3\x01\n" +
	"\x1aApiResponsePaginationOrder\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.pb.order.OrderResponseR\x04data\x126\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x16.pb.api.PaginationMetaR\n" +
	"pagination2\xc5\x03\n" +
	"\x11OrderQueryService\x12N\n" +
	"\aFindAll\x12\x1d.pb.order.FindAllOrderRequest\x1a$.pb.order.ApiResponsePaginationOrder\x12]\n" +
	"\x0eFindByMerchant\x12%.pb.order.FindAllOrderMerchantRequest\x1a$.pb.order.ApiResponsePaginationOrder\x12F\n" +
	"\bFindById\x12\x1e.pb.order.FindByIdOrderRequest\x1a\x1a.pb.order.ApiResponseOrder\x12[\n" +
	"\fFindByActive\x12\x1d.pb.order.FindAllOrderRequest\x1a,.pb.order.ApiResponsePaginationOrderDeleteAt\x12\\\n" +
	"\rFindByTrashed\x12\x1d.pb.order.FindAllOrderRequest\x1a,.pb.order.ApiResponsePaginationOrderDeleteAtB=Z;github.com/MamangRust/monolith-graphql-pointofsale-pb/orderb\x06proto3"

var (
	file_order_query_proto_rawDescOnce sync.Once
	file_order_query_proto_rawDescData []byte
)

func file_order_query_proto_rawDescGZIP() []byte {
	file_order_query_proto_rawDescOnce.Do(func() {
		file_order_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_query_proto_rawDesc), len(file_order_query_proto_rawDesc)))
	})
	return file_order_query_proto_rawDescData
}

var file_order_query_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_order_query_proto_goTypes = []any{
	(*FindAllOrderRequest)(nil),                // 0: pb.order.FindAllOrderRequest
	(*FindAllOrderMerchantRequest)(nil),        // 1: pb.order.FindAllOrderMerchantRequest
	(*FindByIdOrderRequest)(nil),               // 2: pb.order.FindByIdOrderRequest
	(*OrderResponse)(nil),                      // 3: pb.order.OrderResponse
	(*OrderResponseDeleteAt)(nil),              // 4: pb.order.OrderResponseDeleteAt
	(*ApiResponseOrder)(nil),                   // 5: pb.order.ApiResponseOrder
	(*ApiResponseOrderDeleteAt)(nil),           // 6: pb.order.ApiResponseOrderDeleteAt
	(*ApiResponsesOrder)(nil),                  // 7: pb.order.ApiResponsesOrder
	(*ApiResponseOrderDelete)(nil),             // 8: pb.order.ApiResponseOrderDelete
	(*ApiResponseOrderAll)(nil),                // 9: pb.order.ApiResponseOrderAll
	(*ApiResponsePaginationOrderDeleteAt)(nil), // 10: pb.order.ApiResponsePaginationOrderDeleteAt
	(*ApiResponsePaginationOrder)(nil),         // 11: pb.order.ApiResponsePaginationOrder
	(*wrapperspb.StringValue)(nil),             // 12: google.protobuf.StringValue
	(*api.PaginationMeta)(nil),                 // 13: pb.api.PaginationMeta
}
var file_order_query_proto_depIdxs = []int32{
	12, // 0: pb.order.OrderResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	3,  // 1: pb.order.ApiResponseOrder.data:type_name -> pb.order.OrderResponse
	4,  // 2: pb.order.ApiResponseOrderDeleteAt.data:type_name -> pb.order.OrderResponseDeleteAt
	3,  // 3: pb.order.ApiResponsesOrder.data:type_name -> pb.order.OrderResponse
	4,  // 4: pb.order.ApiResponsePaginationOrderDeleteAt.data:type_name -> pb.order.OrderResponseDeleteAt
	13, // 5: pb.order.ApiResponsePaginationOrderDeleteAt.pagination:type_name -> pb.api.PaginationMeta
	3,  // 6: pb.order.ApiResponsePaginationOrder.data:type_name -> pb.order.OrderResponse
	13, // 7: pb.order.ApiResponsePaginationOrder.pagination:type_name -> pb.api.PaginationMeta
	0,  // 8: pb.order.OrderQueryService.FindAll:input_type -> pb.order.FindAllOrderRequest
	1,  // 9: pb.order.OrderQueryService.FindByMerchant:input_type -> pb.order.FindAllOrderMerchantRequest
	2,  // 10: pb.order.OrderQueryService.FindById:input_type -> pb.order.FindByIdOrderRequest
	0,  // 11: pb.order.OrderQueryService.FindByActive:input_type -> pb.order.FindAllOrderRequest
	0,  // 12: pb.order.OrderQueryService.FindByTrashed:input_type -> pb.order.FindAllOrderRequest
	11, // 13: pb.order.OrderQueryService.FindAll:output_type -> pb.order.ApiResponsePaginationOrder
	11, // 14: pb.order.OrderQueryService.FindByMerchant:output_type -> pb.order.ApiResponsePaginationOrder
	5,  // 15: pb.order.OrderQueryService.FindById:output_type -> pb.order.ApiResponseOrder
	10, // 16: pb.order.OrderQueryService.FindByActive:output_type -> pb.order.ApiResponsePaginationOrderDeleteAt
	10, // 17: pb.order.OrderQueryService.FindByTrashed:output_type -> pb.order.ApiResponsePaginationOrderDeleteAt
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_order_query_proto_init() }
func file_order_query_proto_init() {
	if File_order_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_query_proto_rawDesc), len(file_order_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_query_proto_goTypes,
		DependencyIndexes: file_order_query_proto_depIdxs,
		MessageInfos:      file_order_query_proto_msgTypes,
	}.Build()
	File_order_query_proto = out.File
	file_order_query_proto_goTypes = nil
	file_order_query_proto_depIdxs = nil
}
