// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: order/stats.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindYearOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearOrder) Reset() {
	*x = FindYearOrder{}
	mi := &file_order_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearOrder) ProtoMessage() {}

func (x *FindYearOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearOrder.ProtoReflect.Descriptor instead.
func (*FindYearOrder) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{0}
}

func (x *FindYearOrder) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearOrderByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearOrderByMerchant) Reset() {
	*x = FindYearOrderByMerchant{}
	mi := &file_order_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearOrderByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearOrderByMerchant) ProtoMessage() {}

func (x *FindYearOrderByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearOrderByMerchant.ProtoReflect.Descriptor instead.
func (*FindYearOrderByMerchant) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{1}
}

func (x *FindYearOrderByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FindYearOrderByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearMonthTotalRevenue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearMonthTotalRevenue) Reset() {
	*x = FindYearMonthTotalRevenue{}
	mi := &file_order_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearMonthTotalRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearMonthTotalRevenue) ProtoMessage() {}

func (x *FindYearMonthTotalRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearMonthTotalRevenue.ProtoReflect.Descriptor instead.
func (*FindYearMonthTotalRevenue) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{2}
}

func (x *FindYearMonthTotalRevenue) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearMonthTotalRevenue) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type FindYearTotalRevenue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTotalRevenue) Reset() {
	*x = FindYearTotalRevenue{}
	mi := &file_order_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTotalRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTotalRevenue) ProtoMessage() {}

func (x *FindYearTotalRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTotalRevenue.ProtoReflect.Descriptor instead.
func (*FindYearTotalRevenue) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{3}
}

func (x *FindYearTotalRevenue) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearMonthTotalRevenueById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	OrderId       int32                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearMonthTotalRevenueById) Reset() {
	*x = FindYearMonthTotalRevenueById{}
	mi := &file_order_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearMonthTotalRevenueById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearMonthTotalRevenueById) ProtoMessage() {}

func (x *FindYearMonthTotalRevenueById) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearMonthTotalRevenueById.ProtoReflect.Descriptor instead.
func (*FindYearMonthTotalRevenueById) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{4}
}

func (x *FindYearMonthTotalRevenueById) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearMonthTotalRevenueById) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *FindYearMonthTotalRevenueById) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type FindYearTotalRevenueById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTotalRevenueById) Reset() {
	*x = FindYearTotalRevenueById{}
	mi := &file_order_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTotalRevenueById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTotalRevenueById) ProtoMessage() {}

func (x *FindYearTotalRevenueById) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTotalRevenueById.ProtoReflect.Descriptor instead.
func (*FindYearTotalRevenueById) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{5}
}

func (x *FindYearTotalRevenueById) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearTotalRevenueById) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type FindYearMonthTotalRevenueByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	MerchantId    int32                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearMonthTotalRevenueByMerchant) Reset() {
	*x = FindYearMonthTotalRevenueByMerchant{}
	mi := &file_order_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearMonthTotalRevenueByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearMonthTotalRevenueByMerchant) ProtoMessage() {}

func (x *FindYearMonthTotalRevenueByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearMonthTotalRevenueByMerchant.ProtoReflect.Descriptor instead.
func (*FindYearMonthTotalRevenueByMerchant) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{6}
}

func (x *FindYearMonthTotalRevenueByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearMonthTotalRevenueByMerchant) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *FindYearMonthTotalRevenueByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type FindYearTotalRevenueByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTotalRevenueByMerchant) Reset() {
	*x = FindYearTotalRevenueByMerchant{}
	mi := &file_order_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTotalRevenueByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTotalRevenueByMerchant) ProtoMessage() {}

func (x *FindYearTotalRevenueByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTotalRevenueByMerchant.ProtoReflect.Descriptor instead.
func (*FindYearTotalRevenueByMerchant) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{7}
}

func (x *FindYearTotalRevenueByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearTotalRevenueByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type OrderMonthlyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Month          string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	OrderCount     int32                  `protobuf:"varint,2,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	TotalRevenue   int32                  `protobuf:"varint,3,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	TotalItemsSold int32                  `protobuf:"varint,4,opt,name=total_items_sold,json=totalItemsSold,proto3" json:"total_items_sold,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderMonthlyResponse) Reset() {
	*x = OrderMonthlyResponse{}
	mi := &file_order_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderMonthlyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMonthlyResponse) ProtoMessage() {}

func (x *OrderMonthlyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMonthlyResponse.ProtoReflect.Descriptor instead.
func (*OrderMonthlyResponse) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{8}
}

func (x *OrderMonthlyResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *OrderMonthlyResponse) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *OrderMonthlyResponse) GetTotalRevenue() int32 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *OrderMonthlyResponse) GetTotalItemsSold() int32 {
	if x != nil {
		return x.TotalItemsSold
	}
	return 0
}

type OrderYearlyResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Year               string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	OrderCount         int32                  `protobuf:"varint,2,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	TotalRevenue       int32                  `protobuf:"varint,3,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	TotalItemsSold     int32                  `protobuf:"varint,4,opt,name=total_items_sold,json=totalItemsSold,proto3" json:"total_items_sold,omitempty"`
	ActiveCashiers     int32                  `protobuf:"varint,5,opt,name=active_cashiers,json=activeCashiers,proto3" json:"active_cashiers,omitempty"`
	UniqueProductsSold int32                  `protobuf:"varint,6,opt,name=unique_products_sold,json=uniqueProductsSold,proto3" json:"unique_products_sold,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrderYearlyResponse) Reset() {
	*x = OrderYearlyResponse{}
	mi := &file_order_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderYearlyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderYearlyResponse) ProtoMessage() {}

func (x *OrderYearlyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderYearlyResponse.ProtoReflect.Descriptor instead.
func (*OrderYearlyResponse) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{9}
}

func (x *OrderYearlyResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *OrderYearlyResponse) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *OrderYearlyResponse) GetTotalRevenue() int32 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *OrderYearlyResponse) GetTotalItemsSold() int32 {
	if x != nil {
		return x.TotalItemsSold
	}
	return 0
}

func (x *OrderYearlyResponse) GetActiveCashiers() int32 {
	if x != nil {
		return x.ActiveCashiers
	}
	return 0
}

func (x *OrderYearlyResponse) GetUniqueProductsSold() int32 {
	if x != nil {
		return x.UniqueProductsSold
	}
	return 0
}

type OrderMonthlyTotalRevenueResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Year           string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month          string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	OrderCount     int32                  `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	TotalRevenue   int32                  `protobuf:"varint,4,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	TotalItemsSold int32                  `protobuf:"varint,5,opt,name=total_items_sold,json=totalItemsSold,proto3" json:"total_items_sold,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderMonthlyTotalRevenueResponse) Reset() {
	*x = OrderMonthlyTotalRevenueResponse{}
	mi := &file_order_stats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderMonthlyTotalRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMonthlyTotalRevenueResponse) ProtoMessage() {}

func (x *OrderMonthlyTotalRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMonthlyTotalRevenueResponse.ProtoReflect.Descriptor instead.
func (*OrderMonthlyTotalRevenueResponse) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{10}
}

func (x *OrderMonthlyTotalRevenueResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *OrderMonthlyTotalRevenueResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *OrderMonthlyTotalRevenueResponse) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *OrderMonthlyTotalRevenueResponse) GetTotalRevenue() int32 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *OrderMonthlyTotalRevenueResponse) GetTotalItemsSold() int32 {
	if x != nil {
		return x.TotalItemsSold
	}
	return 0
}

type OrderYearlyTotalRevenueResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Year               string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	OrderCount         int32                  `protobuf:"varint,2,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	TotalRevenue       int32                  `protobuf:"varint,3,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	TotalItemsSold     int32                  `protobuf:"varint,4,opt,name=total_items_sold,json=totalItemsSold,proto3" json:"total_items_sold,omitempty"`
	ActiveCashiers     int32                  `protobuf:"varint,5,opt,name=active_cashiers,json=activeCashiers,proto3" json:"active_cashiers,omitempty"`
	UniqueProductsSold int32                  `protobuf:"varint,6,opt,name=unique_products_sold,json=uniqueProductsSold,proto3" json:"unique_products_sold,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrderYearlyTotalRevenueResponse) Reset() {
	*x = OrderYearlyTotalRevenueResponse{}
	mi := &file_order_stats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderYearlyTotalRevenueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderYearlyTotalRevenueResponse) ProtoMessage() {}

func (x *OrderYearlyTotalRevenueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderYearlyTotalRevenueResponse.ProtoReflect.Descriptor instead.
func (*OrderYearlyTotalRevenueResponse) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{11}
}

func (x *OrderYearlyTotalRevenueResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *OrderYearlyTotalRevenueResponse) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *OrderYearlyTotalRevenueResponse) GetTotalRevenue() int32 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *OrderYearlyTotalRevenueResponse) GetTotalItemsSold() int32 {
	if x != nil {
		return x.TotalItemsSold
	}
	return 0
}

func (x *OrderYearlyTotalRevenueResponse) GetActiveCashiers() int32 {
	if x != nil {
		return x.ActiveCashiers
	}
	return 0
}

func (x *OrderYearlyTotalRevenueResponse) GetUniqueProductsSold() int32 {
	if x != nil {
		return x.UniqueProductsSold
	}
	return 0
}

type ApiResponseOrderMonthly struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderMonthlyResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderMonthly) Reset() {
	*x = ApiResponseOrderMonthly{}
	mi := &file_order_stats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderMonthly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderMonthly) ProtoMessage() {}

func (x *ApiResponseOrderMonthly) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderMonthly.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderMonthly) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{12}
}

func (x *ApiResponseOrderMonthly) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderMonthly) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseOrderMonthly) GetData() []*OrderMonthlyResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseOrderYearly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderYearlyResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderYearly) Reset() {
	*x = ApiResponseOrderYearly{}
	mi := &file_order_stats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderYearly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderYearly) ProtoMessage() {}

func (x *ApiResponseOrderYearly) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderYearly.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderYearly) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{13}
}

func (x *ApiResponseOrderYearly) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderYearly) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseOrderYearly) GetData() []*OrderYearlyResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseOrderMonthlyTotalRevenue struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Status        string                              `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderMonthlyTotalRevenueResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderMonthlyTotalRevenue) Reset() {
	*x = ApiResponseOrderMonthlyTotalRevenue{}
	mi := &file_order_stats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderMonthlyTotalRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderMonthlyTotalRevenue) ProtoMessage() {}

func (x *ApiResponseOrderMonthlyTotalRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderMonthlyTotalRevenue.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderMonthlyTotalRevenue) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{14}
}

func (x *ApiResponseOrderMonthlyTotalRevenue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderMonthlyTotalRevenue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseOrderMonthlyTotalRevenue) GetData() []*OrderMonthlyTotalRevenueResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseOrderYearlyTotalRevenue struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Status        string                             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderYearlyTotalRevenueResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderYearlyTotalRevenue) Reset() {
	*x = ApiResponseOrderYearlyTotalRevenue{}
	mi := &file_order_stats_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderYearlyTotalRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderYearlyTotalRevenue) ProtoMessage() {}

func (x *ApiResponseOrderYearlyTotalRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_order_stats_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderYearlyTotalRevenue.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderYearlyTotalRevenue) Descriptor() ([]byte, []int) {
	return file_order_stats_proto_rawDescGZIP(), []int{15}
}

func (x *ApiResponseOrderYearlyTotalRevenue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderYearlyTotalRevenue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseOrderYearlyTotalRevenue) GetData() []*OrderYearlyTotalRevenueResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_order_stats_proto protoreflect.FileDescriptor

const file_order_stats_proto_rawDesc = "" +
	"\n" +
	"\x11order/stats.proto\x12\bpb.order\"#\n" +
	"\rFindYearOrder\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"N\n" +
	"\x17FindYearOrderByMerchant\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"E\n" +
	"\x19FindYearMonthTotalRevenue\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"*\n" +
	"\x14FindYearTotalRevenue\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"d\n" +
	"\x1dFindYearMonthTotalRevenueById\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x05R\aorderId\"I\n" +
	"\x18FindYearTotalRevenueById\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\"p\n" +
	"#FindYearMonthTotalRevenueByMerchant\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x05R\n" +
	"merchantId\"U\n" +
	"\x1eFindYearTotalRevenueByMerchant\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\"\x9c\x01\n" +
	"\x14OrderMonthlyResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1f\n" +
	"\vorder_count\x18\x02 \x01(\x05R\n" +
	"orderCount\x12#\n" +
	"\rtotal_revenue\x18\x03 \x01(\x05R\ftotalRevenue\x12(\n" +
	"\x10total_items_sold\x18\x04 \x01(\x05R\x0etotalItemsSold\"\xf4\x01\n" +
	"\x13OrderYearlyResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x1f\n" +
	"\vorder_count\x18\x02 \x01(\x05R\n" +
	"orderCount\x12#\n" +
	"\rtotal_revenue\x18\x03 \x01(\x05R\ftotalRevenue\x12(\n" +
	"\x10total_items_sold\x18\x04 \x01(\x05R\x0etotalItemsSold\x12'\n" +
	"\x0factive_cashiers\x18\x05 \x01(\x05R\x0eactiveCashiers\x120\n" +
	"\x14unique_products_sold\x18\x06 \x01(\x05R\x12uniqueProductsSold\"\xbc\x01\n" +
	" OrderMonthlyTotalRevenueResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\x05R\n" +
	"orderCount\x12#\n" +
	"\rtotal_revenue\x18\x04 \x01(\x05R\ftotalRevenue\x12(\n" +
	"\x10total_items_sold\x18\x05 \x01(\x05R\x0etotalItemsSold\"\x80\x02\n" +
	"\x1fOrderYearlyTotalRevenueResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x1f\n" +
	"\vorder_count\x18\x02 \x01(\x05R\n" +
	"orderCount\x12#\n" +
	"\rtotal_revenue\x18\x03 \x01(\x05R\ftotalRevenue\x12(\n" +
	"\x10total_items_sold\x18\x04 \x01(\x05R\x0etotalItemsSold\x12'\n" +
	"\x0factive_cashiers\x18\x05 \x01(\x05R\x0eactiveCashiers\x120\n" +
	"\x14unique_products_sold\x18\x06 \x01(\x05R\x12uniqueProductsSold\"\x7f\n" +
	"\x17ApiResponseOrderMonthly\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x04data\x18\x03 \x03(\v2\x1e.pb.order.OrderMonthlyResponseR\x04data\"}\n" +
	"\x16ApiResponseOrderYearly\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.order.OrderYearlyResponseR\x04data\"\x97\x01\n" +
	"#ApiResponseOrderMonthlyTotalRevenue\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x04data\x18\x03 \x03(\v2*.pb.order.OrderMonthlyTotalRevenueResponseR\x04data\"\x95\x01\n" +
	"\"ApiResponseOrderYearlyTotalRevenue\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\x04data\x18\x03 \x03(\v2).pb.order.OrderYearlyTotalRevenueResponseR\x04data2\xbd\b\n" +
	"\x11OrderStatsService\x12m\n" +
	"\x17FindMonthlyTotalRevenue\x12#.pb.order.FindYearMonthTotalRevenue\x1a-.pb.order.ApiResponseOrderMonthlyTotalRevenue\x12f\n" +
	"\x16FindYearlyTotalRevenue\x12\x1e.pb.order.FindYearTotalRevenue\x1a,.pb.order.ApiResponseOrderYearlyTotalRevenue\x12u\n" +
	"\x1bFindMonthlyTotalRevenueById\x12'.pb.order.FindYearMonthTotalRevenueById\x1a-.pb.order.ApiResponseOrderMonthlyTotalRevenue\x12n\n" +
	"\x1aFindYearlyTotalRevenueById\x12\".pb.order.FindYearTotalRevenueById\x1a,.pb.order.ApiResponseOrderYearlyTotalRevenue\x12\x81\x01\n" +
	"!FindMonthlyTotalRevenueByMerchant\x12-.pb.order.FindYearMonthTotalRevenueByMerchant\x1a-.pb.order.ApiResponseOrderMonthlyTotalRevenue\x12z\n" +
	" FindYearlyTotalRevenueByMerchant\x12(.pb.order.FindYearTotalRevenueByMerchant\x1a,.pb.order.ApiResponseOrderYearlyTotalRevenue\x12P\n" +
	"\x12FindMonthlyRevenue\x12\x17.pb.order.FindYearOrder\x1a!.pb.order.ApiResponseOrderMonthly\x12N\n" +
	"\x11FindYearlyRevenue\x12\x17.pb.order.FindYearOrder\x1a .pb.order.ApiResponseOrderYearly\x12d\n" +
	"\x1cFindMonthlyRevenueByMerchant\x12!.pb.order.FindYearOrderByMerchant\x1a!.pb.order.ApiResponseOrderMonthly\x12b\n" +
	"\x1bFindYearlyRevenueByMerchant\x12!.pb.order.FindYearOrderByMerchant\x1a .pb.order.ApiResponseOrderYearlyB=Z;github.com/MamangRust/monolith-graphql-pointofsale-pb/orderb\x06proto3"

var (
	file_order_stats_proto_rawDescOnce sync.Once
	file_order_stats_proto_rawDescData []byte
)

func file_order_stats_proto_rawDescGZIP() []byte {
	file_order_stats_proto_rawDescOnce.Do(func() {
		file_order_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_stats_proto_rawDesc), len(file_order_stats_proto_rawDesc)))
	})
	return file_order_stats_proto_rawDescData
}

var file_order_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_order_stats_proto_goTypes = []any{
	(*FindYearOrder)(nil),                       // 0: pb.order.FindYearOrder
	(*FindYearOrderByMerchant)(nil),             // 1: pb.order.FindYearOrderByMerchant
	(*FindYearMonthTotalRevenue)(nil),           // 2: pb.order.FindYearMonthTotalRevenue
	(*FindYearTotalRevenue)(nil),                // 3: pb.order.FindYearTotalRevenue
	(*FindYearMonthTotalRevenueById)(nil),       // 4: pb.order.FindYearMonthTotalRevenueById
	(*FindYearTotalRevenueById)(nil),            // 5: pb.order.FindYearTotalRevenueById
	(*FindYearMonthTotalRevenueByMerchant)(nil), // 6: pb.order.FindYearMonthTotalRevenueByMerchant
	(*FindYearTotalRevenueByMerchant)(nil),      // 7: pb.order.FindYearTotalRevenueByMerchant
	(*OrderMonthlyResponse)(nil),                // 8: pb.order.OrderMonthlyResponse
	(*OrderYearlyResponse)(nil),                 // 9: pb.order.OrderYearlyResponse
	(*OrderMonthlyTotalRevenueResponse)(nil),    // 10: pb.order.OrderMonthlyTotalRevenueResponse
	(*OrderYearlyTotalRevenueResponse)(nil),     // 11: pb.order.OrderYearlyTotalRevenueResponse
	(*ApiResponseOrderMonthly)(nil),             // 12: pb.order.ApiResponseOrderMonthly
	(*ApiResponseOrderYearly)(nil),              // 13: pb.order.ApiResponseOrderYearly
	(*ApiResponseOrderMonthlyTotalRevenue)(nil), // 14: pb.order.ApiResponseOrderMonthlyTotalRevenue
	(*ApiResponseOrderYearlyTotalRevenue)(nil),  // 15: pb.order.ApiResponseOrderYearlyTotalRevenue
}
var file_order_stats_proto_depIdxs = []int32{
	8,  // 0: pb.order.ApiResponseOrderMonthly.data:type_name -> pb.order.OrderMonthlyResponse
	9,  // 1: pb.order.ApiResponseOrderYearly.data:type_name -> pb.order.OrderYearlyResponse
	10, // 2: pb.order.ApiResponseOrderMonthlyTotalRevenue.data:type_name -> pb.order.OrderMonthlyTotalRevenueResponse
	11, // 3: pb.order.ApiResponseOrderYearlyTotalRevenue.data:type_name -> pb.order.OrderYearlyTotalRevenueResponse
	2,  // 4: pb.order.OrderStatsService.FindMonthlyTotalRevenue:input_type -> pb.order.FindYearMonthTotalRevenue
	3,  // 5: pb.order.OrderStatsService.FindYearlyTotalRevenue:input_type -> pb.order.FindYearTotalRevenue
	4,  // 6: pb.order.OrderStatsService.FindMonthlyTotalRevenueById:input_type -> pb.order.FindYearMonthTotalRevenueById
	5,  // 7: pb.order.OrderStatsService.FindYearlyTotalRevenueById:input_type -> pb.order.FindYearTotalRevenueById
	6,  // 8: pb.order.OrderStatsService.FindMonthlyTotalRevenueByMerchant:input_type -> pb.order.FindYearMonthTotalRevenueByMerchant
	7,  // 9: pb.order.OrderStatsService.FindYearlyTotalRevenueByMerchant:input_type -> pb.order.FindYearTotalRevenueByMerchant
	0,  // 10: pb.order.OrderStatsService.FindMonthlyRevenue:input_type -> pb.order.FindYearOrder
	0,  // 11: pb.order.OrderStatsService.FindYearlyRevenue:input_type -> pb.order.FindYearOrder
	1,  // 12: pb.order.OrderStatsService.FindMonthlyRevenueByMerchant:input_type -> pb.order.FindYearOrderByMerchant
	1,  // 13: pb.order.OrderStatsService.FindYearlyRevenueByMerchant:input_type -> pb.order.FindYearOrderByMerchant
	14, // 14: pb.order.OrderStatsService.FindMonthlyTotalRevenue:output_type -> pb.order.ApiResponseOrderMonthlyTotalRevenue
	15, // 15: pb.order.OrderStatsService.FindYearlyTotalRevenue:output_type -> pb.order.ApiResponseOrderYearlyTotalRevenue
	14, // 16: pb.order.OrderStatsService.FindMonthlyTotalRevenueById:output_type -> pb.order.ApiResponseOrderMonthlyTotalRevenue
	15, // 17: pb.order.OrderStatsService.FindYearlyTotalRevenueById:output_type -> pb.order.ApiResponseOrderYearlyTotalRevenue
	14, // 18: pb.order.OrderStatsService.FindMonthlyTotalRevenueByMerchant:output_type -> pb.order.ApiResponseOrderMonthlyTotalRevenue
	15, // 19: pb.order.OrderStatsService.FindYearlyTotalRevenueByMerchant:output_type -> pb.order.ApiResponseOrderYearlyTotalRevenue
	12, // 20: pb.order.OrderStatsService.FindMonthlyRevenue:output_type -> pb.order.ApiResponseOrderMonthly
	13, // 21: pb.order.OrderStatsService.FindYearlyRevenue:output_type -> pb.order.ApiResponseOrderYearly
	12, // 22: pb.order.OrderStatsService.FindMonthlyRevenueByMerchant:output_type -> pb.order.ApiResponseOrderMonthly
	13, // 23: pb.order.OrderStatsService.FindYearlyRevenueByMerchant:output_type -> pb.order.ApiResponseOrderYearly
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_order_stats_proto_init() }
func file_order_stats_proto_init() {
	if File_order_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_stats_proto_rawDesc), len(file_order_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_stats_proto_goTypes,
		DependencyIndexes: file_order_stats_proto_depIdxs,
		MessageInfos:      file_order_stats_proto_msgTypes,
	}.Build()
	File_order_stats_proto = out.File
	file_order_stats_proto_goTypes = nil
	file_order_stats_proto_depIdxs = nil
}
