// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: product/command.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	CountInStock  int32                  `protobuf:"varint,6,opt,name=count_in_stock,json=countInStock,proto3" json:"count_in_stock,omitempty"`
	Brand         string                 `protobuf:"bytes,7,opt,name=brand,proto3" json:"brand,omitempty"`
	Weight        int32                  `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	ImageProduct  string                 `protobuf:"bytes,9,opt,name=image_product,json=imageProduct,proto3" json:"image_product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateProductRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetCountInStock() int32 {
	if x != nil {
		return x.CountInStock
	}
	return 0
}

func (x *CreateProductRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateProductRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateProductRequest) GetImageProduct() string {
	if x != nil {
		return x.ImageProduct
	}
	return ""
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price         int32                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	CountInStock  int32                  `protobuf:"varint,7,opt,name=count_in_stock,json=countInStock,proto3" json:"count_in_stock,omitempty"`
	Brand         string                 `protobuf:"bytes,8,opt,name=brand,proto3" json:"brand,omitempty"`
	Weight        int32                  `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	ImageProduct  string                 `protobuf:"bytes,10,opt,name=image_product,json=imageProduct,proto3" json:"image_product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_product_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProductRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *UpdateProductRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetCountInStock() int32 {
	if x != nil {
		return x.CountInStock
	}
	return 0
}

func (x *UpdateProductRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateProductRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdateProductRequest) GetImageProduct() string {
	if x != nil {
		return x.ImageProduct
	}
	return ""
}

var File_product_command_proto protoreflect.FileDescriptor

const file_product_command_proto_rawDesc = "" +
	"\n" +
	"\x15product/command.proto\x12\n" +
	"pb.product\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13product/query.proto\"\x9d\x02\n" +
	"\x14CreateProductRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12$\n" +
	"\x0ecount_in_stock\x18\x06 \x01(\x05R\fcountInStock\x12\x14\n" +
	"\x05brand\x18\a \x01(\tR\x05brand\x12\x16\n" +
	"\x06weight\x18\b \x01(\x05R\x06weight\x12#\n" +
	"\rimage_product\x18\t \x01(\tR\fimageProduct\"\xbc\x02\n" +
	"\x14UpdateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x05R\x05price\x12$\n" +
	"\x0ecount_in_stock\x18\a \x01(\x05R\fcountInStock\x12\x14\n" +
	"\x05brand\x18\b \x01(\tR\x05brand\x12\x16\n" +
	"\x06weight\x18\t \x01(\x05R\x06weight\x12#\n" +
	"\rimage_product\x18\n" +
	" \x01(\tR\fimageProduct2\xf7\x04\n" +
	"\x15ProductCommandService\x12J\n" +
	"\x06Create\x12 .pb.product.CreateProductRequest\x1a\x1e.pb.product.ApiResponseProduct\x12J\n" +
	"\x06Update\x12 .pb.product.UpdateProductRequest\x1a\x1e.pb.product.ApiResponseProduct\x12\\\n" +
	"\x0eTrashedProduct\x12\".pb.product.FindByIdProductRequest\x1a&.pb.product.ApiResponseProductDeleteAt\x12\\\n" +
	"\x0eRestoreProduct\x12\".pb.product.FindByIdProductRequest\x1a&.pb.product.ApiResponseProductDeleteAt\x12b\n" +
	"\x16DeleteProductPermanent\x12\".pb.product.FindByIdProductRequest\x1a$.pb.product.ApiResponseProductDelete\x12N\n" +
	"\x11RestoreAllProduct\x12\x16.google.protobuf.Empty\x1a!.pb.product.ApiResponseProductAll\x12V\n" +
	"\x19DeleteAllProductPermanent\x12\x16.google.protobuf.Empty\x1a!.pb.product.ApiResponseProductAllB?Z=github.com/MamangRust/monolith-graphql-pointofsale-pb/productb\x06proto3"

var (
	file_product_command_proto_rawDescOnce sync.Once
	file_product_command_proto_rawDescData []byte
)

func file_product_command_proto_rawDescGZIP() []byte {
	file_product_command_proto_rawDescOnce.Do(func() {
		file_product_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_command_proto_rawDesc), len(file_product_command_proto_rawDesc)))
	})
	return file_product_command_proto_rawDescData
}

var file_product_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_product_command_proto_goTypes = []any{
	(*CreateProductRequest)(nil),       // 0: pb.product.CreateProductRequest
	(*UpdateProductRequest)(nil),       // 1: pb.product.UpdateProductRequest
	(*FindByIdProductRequest)(nil),     // 2: pb.product.FindByIdProductRequest
	(*emptypb.Empty)(nil),              // 3: google.protobuf.Empty
	(*ApiResponseProduct)(nil),         // 4: pb.product.ApiResponseProduct
	(*ApiResponseProductDeleteAt)(nil), // 5: pb.product.ApiResponseProductDeleteAt
	(*ApiResponseProductDelete)(nil),   // 6: pb.product.ApiResponseProductDelete
	(*ApiResponseProductAll)(nil),      // 7: pb.product.ApiResponseProductAll
}
var file_product_command_proto_depIdxs = []int32{
	0, // 0: pb.product.ProductCommandService.Create:input_type -> pb.product.CreateProductRequest
	1, // 1: pb.product.ProductCommandService.Update:input_type -> pb.product.UpdateProductRequest
	2, // 2: pb.product.ProductCommandService.TrashedProduct:input_type -> pb.product.FindByIdProductRequest
	2, // 3: pb.product.ProductCommandService.RestoreProduct:input_type -> pb.product.FindByIdProductRequest
	2, // 4: pb.product.ProductCommandService.DeleteProductPermanent:input_type -> pb.product.FindByIdProductRequest
	3, // 5: pb.product.ProductCommandService.RestoreAllProduct:input_type -> google.protobuf.Empty
	3, // 6: pb.product.ProductCommandService.DeleteAllProductPermanent:input_type -> google.protobuf.Empty
	4, // 7: pb.product.ProductCommandService.Create:output_type -> pb.product.ApiResponseProduct
	4, // 8: pb.product.ProductCommandService.Update:output_type -> pb.product.ApiResponseProduct
	5, // 9: pb.product.ProductCommandService.TrashedProduct:output_type -> pb.product.ApiResponseProductDeleteAt
	5, // 10: pb.product.ProductCommandService.RestoreProduct:output_type -> pb.product.ApiResponseProductDeleteAt
	6, // 11: pb.product.ProductCommandService.DeleteProductPermanent:output_type -> pb.product.ApiResponseProductDelete
	7, // 12: pb.product.ProductCommandService.RestoreAllProduct:output_type -> pb.product.ApiResponseProductAll
	7, // 13: pb.product.ProductCommandService.DeleteAllProductPermanent:output_type -> pb.product.ApiResponseProductAll
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_command_proto_init() }
func file_product_command_proto_init() {
	if File_product_command_proto != nil {
		return
	}
	file_product_query_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_command_proto_rawDesc), len(file_product_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_command_proto_goTypes,
		DependencyIndexes: file_product_command_proto_depIdxs,
		MessageInfos:      file_product_command_proto_msgTypes,
	}.Build()
	File_product_command_proto = out.File
	file_product_command_proto_goTypes = nil
	file_product_command_proto_depIdxs = nil
}
