// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: product/query.proto

package product

import (
	api "github.com/MamangRust/monolith-graphql-pointofsale-pb/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllProductRequest) Reset() {
	*x = FindAllProductRequest{}
	mi := &file_product_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllProductRequest) ProtoMessage() {}

func (x *FindAllProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllProductRequest.ProtoReflect.Descriptor instead.
func (*FindAllProductRequest) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllProductRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllProductRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllProductRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindAllProductMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	CategoryId    int32                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	MinPrice      int32                  `protobuf:"varint,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      int32                  `protobuf:"varint,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllProductMerchantRequest) Reset() {
	*x = FindAllProductMerchantRequest{}
	mi := &file_product_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllProductMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllProductMerchantRequest) ProtoMessage() {}

func (x *FindAllProductMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllProductMerchantRequest.ProtoReflect.Descriptor instead.
func (*FindAllProductMerchantRequest) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllProductMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FindAllProductMerchantRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *FindAllProductMerchantRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *FindAllProductMerchantRequest) GetMinPrice() int32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *FindAllProductMerchantRequest) GetMaxPrice() int32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *FindAllProductMerchantRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllProductMerchantRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FindAllProductCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryName  string                 `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	Minprice      int32                  `protobuf:"varint,5,opt,name=minprice,proto3" json:"minprice,omitempty"`
	Maxprice      int32                  `protobuf:"varint,6,opt,name=maxprice,proto3" json:"maxprice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllProductCategoryRequest) Reset() {
	*x = FindAllProductCategoryRequest{}
	mi := &file_product_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllProductCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllProductCategoryRequest) ProtoMessage() {}

func (x *FindAllProductCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllProductCategoryRequest.ProtoReflect.Descriptor instead.
func (*FindAllProductCategoryRequest) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{2}
}

func (x *FindAllProductCategoryRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *FindAllProductCategoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllProductCategoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllProductCategoryRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *FindAllProductCategoryRequest) GetMinprice() int32 {
	if x != nil {
		return x.Minprice
	}
	return 0
}

func (x *FindAllProductCategoryRequest) GetMaxprice() int32 {
	if x != nil {
		return x.Maxprice
	}
	return 0
}

type FindByIdProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdProductRequest) Reset() {
	*x = FindByIdProductRequest{}
	mi := &file_product_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdProductRequest) ProtoMessage() {}

func (x *FindByIdProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdProductRequest.ProtoReflect.Descriptor instead.
func (*FindByIdProductRequest) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{3}
}

func (x *FindByIdProductRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price         int32                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	CountInStock  int32                  `protobuf:"varint,7,opt,name=count_in_stock,json=countInStock,proto3" json:"count_in_stock,omitempty"`
	Brand         string                 `protobuf:"bytes,8,opt,name=brand,proto3" json:"brand,omitempty"`
	Weight        int32                  `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Rating        float32                `protobuf:"fixed32,10,opt,name=rating,proto3" json:"rating,omitempty"`
	SlugProduct   string                 `protobuf:"bytes,11,opt,name=slug_product,json=slugProduct,proto3" json:"slug_product,omitempty"`
	ImageProduct  string                 `protobuf:"bytes,12,opt,name=image_product,json=imageProduct,proto3" json:"image_product,omitempty"`
	Barcode       string                 `protobuf:"bytes,13,opt,name=barcode,proto3" json:"barcode,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_product_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{4}
}

func (x *ProductResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductResponse) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *ProductResponse) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponse) GetCountInStock() int32 {
	if x != nil {
		return x.CountInStock
	}
	return 0
}

func (x *ProductResponse) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ProductResponse) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProductResponse) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ProductResponse) GetSlugProduct() string {
	if x != nil {
		return x.SlugProduct
	}
	return ""
}

func (x *ProductResponse) GetImageProduct() string {
	if x != nil {
		return x.ImageProduct
	}
	return ""
}

func (x *ProductResponse) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *ProductResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProductResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ProductResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    int32                   `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	CategoryId    int32                   `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                  `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price         int32                   `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	CountInStock  int32                   `protobuf:"varint,7,opt,name=count_in_stock,json=countInStock,proto3" json:"count_in_stock,omitempty"`
	Brand         string                  `protobuf:"bytes,8,opt,name=brand,proto3" json:"brand,omitempty"`
	Weight        int32                   `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	Rating        float32                 `protobuf:"fixed32,10,opt,name=rating,proto3" json:"rating,omitempty"`
	SlugProduct   string                  `protobuf:"bytes,11,opt,name=slug_product,json=slugProduct,proto3" json:"slug_product,omitempty"`
	ImageProduct  string                  `protobuf:"bytes,12,opt,name=image_product,json=imageProduct,proto3" json:"image_product,omitempty"`
	Barcode       string                  `protobuf:"bytes,13,opt,name=barcode,proto3" json:"barcode,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponseDeleteAt) Reset() {
	*x = ProductResponseDeleteAt{}
	mi := &file_product_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponseDeleteAt) ProtoMessage() {}

func (x *ProductResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*ProductResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{5}
}

func (x *ProductResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductResponseDeleteAt) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *ProductResponseDeleteAt) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductResponseDeleteAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponseDeleteAt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductResponseDeleteAt) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponseDeleteAt) GetCountInStock() int32 {
	if x != nil {
		return x.CountInStock
	}
	return 0
}

func (x *ProductResponseDeleteAt) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ProductResponseDeleteAt) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ProductResponseDeleteAt) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ProductResponseDeleteAt) GetSlugProduct() string {
	if x != nil {
		return x.SlugProduct
	}
	return ""
}

func (x *ProductResponseDeleteAt) GetImageProduct() string {
	if x != nil {
		return x.ImageProduct
	}
	return ""
}

func (x *ProductResponseDeleteAt) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *ProductResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProductResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ProductResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ProductResponse       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseProduct) Reset() {
	*x = ApiResponseProduct{}
	mi := &file_product_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseProduct) ProtoMessage() {}

func (x *ApiResponseProduct) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseProduct.ProtoReflect.Descriptor instead.
func (*ApiResponseProduct) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseProduct) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseProduct) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseProduct) GetData() *ProductResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseProductDeleteAt struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ProductResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseProductDeleteAt) Reset() {
	*x = ApiResponseProductDeleteAt{}
	mi := &file_product_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseProductDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseProductDeleteAt) ProtoMessage() {}

func (x *ApiResponseProductDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseProductDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseProductDeleteAt) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponseProductDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseProductDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseProductDeleteAt) GetData() *ProductResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ProductResponse     `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesProduct) Reset() {
	*x = ApiResponsesProduct{}
	mi := &file_product_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesProduct) ProtoMessage() {}

func (x *ApiResponsesProduct) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesProduct.ProtoReflect.Descriptor instead.
func (*ApiResponsesProduct) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponsesProduct) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesProduct) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesProduct) GetData() []*ProductResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseProductDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseProductDelete) Reset() {
	*x = ApiResponseProductDelete{}
	mi := &file_product_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseProductDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseProductDelete) ProtoMessage() {}

func (x *ApiResponseProductDelete) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseProductDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseProductDelete) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponseProductDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseProductDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseProductAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseProductAll) Reset() {
	*x = ApiResponseProductAll{}
	mi := &file_product_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseProductAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseProductAll) ProtoMessage() {}

func (x *ApiResponseProductAll) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseProductAll.ProtoReflect.Descriptor instead.
func (*ApiResponseProductAll) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponseProductAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseProductAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationProductDeleteAt struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        string                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ProductResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *api.PaginationMeta        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationProductDeleteAt) Reset() {
	*x = ApiResponsePaginationProductDeleteAt{}
	mi := &file_product_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationProductDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationProductDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationProductDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationProductDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationProductDeleteAt) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponsePaginationProductDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationProductDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationProductDeleteAt) GetData() []*ProductResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationProductDeleteAt) GetPagination() *api.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ProductResponse     `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *api.PaginationMeta    `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationProduct) Reset() {
	*x = ApiResponsePaginationProduct{}
	mi := &file_product_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationProduct) ProtoMessage() {}

func (x *ApiResponsePaginationProduct) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationProduct.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationProduct) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{12}
}

func (x *ApiResponsePaginationProduct) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationProduct) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationProduct) GetData() []*ProductResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationProduct) GetPagination() *api.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_product_query_proto protoreflect.FileDescriptor

const file_product_query_proto_rawDesc = "" +
	"\n" +
	"\x13product/query.proto\x12\n" +
	"pb.product\x1a\rapi/api.proto\x1a\x1egoogle/protobuf/wrappers.proto\"`\n" +
	"\x15FindAllProductRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\xe4\x01\n" +
	"\x1dFindAllProductMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x05R\n" +
	"categoryId\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x05R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\x05R\bmaxPrice\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"\xc5\x01\n" +
	"\x1dFindAllProductCategoryRequest\x12#\n" +
	"\rcategory_name\x18\x01 \x01(\tR\fcategoryName\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x1a\n" +
	"\bminprice\x18\x05 \x01(\x05R\bminprice\x12\x1a\n" +
	"\bmaxprice\x18\x06 \x01(\x05R\bmaxprice\"(\n" +
	"\x16FindByIdProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xbb\x03\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x05R\x05price\x12$\n" +
	"\x0ecount_in_stock\x18\a \x01(\x05R\fcountInStock\x12\x14\n" +
	"\x05brand\x18\b \x01(\tR\x05brand\x12\x16\n" +
	"\x06weight\x18\t \x01(\x05R\x06weight\x12\x16\n" +
	"\x06rating\x18\n" +
	" \x01(\x02R\x06rating\x12!\n" +
	"\fslug_product\x18\v \x01(\tR\vslugProduct\x12#\n" +
	"\rimage_product\x18\f \x01(\tR\fimageProduct\x12\x18\n" +
	"\abarcode\x18\r \x01(\tR\abarcode\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"\x80\x04\n" +
	"\x17ProductResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x05R\x05price\x12$\n" +
	"\x0ecount_in_stock\x18\a \x01(\x05R\fcountInStock\x12\x14\n" +
	"\x05brand\x18\b \x01(\tR\x05brand\x12\x16\n" +
	"\x06weight\x18\t \x01(\x05R\x06weight\x12\x16\n" +
	"\x06rating\x18\n" +
	" \x01(\x02R\x06rating\x12!\n" +
	"\fslug_product\x18\v \x01(\tR\vslugProduct\x12#\n" +
	"\rimage_product\x18\f \x01(\tR\fimageProduct\x12\x18\n" +
	"\abarcode\x18\r \x01(\tR\abarcode\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"w\n" +
	"\x12ApiResponseProduct\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.pb.product.ProductResponseR\x04data\"\x87\x01\n" +
	"\x1aApiResponseProductDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x01(\v2#.pb.product.ProductResponseDeleteAtR\x04data\"x\n" +
	"\x13ApiResponsesProduct\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x03(\v2\x1b.pb.product.ProductResponseR\x04data\"L\n" +
	"\x18ApiResponseProductDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x15ApiResponseProductAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc9\x01\n" +
	"$ApiResponsePaginationProductDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.pb.product.ProductResponseDeleteAtR\x04data\x126\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x16.pb.api.PaginationMetaR\n" +
	"pagination\"\xb9\x01\n" +
	"\x1cApiResponsePaginationProduct\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x03(\v2\x1b.pb.product.ProductResponseR\x04data\x126\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x16.pb.api.PaginationMetaR\n" +
	"pagination2\xd6\x04\n" +
	"\x13ProductQueryService\x12V\n" +
	"\aFindAll\x12!.pb.product.FindAllProductRequest\x1a(.pb.product.ApiResponsePaginationProduct\x12e\n" +
	"\x0eFindByMerchant\x12).pb.product.FindAllProductMerchantRequest\x1a(.pb.product.ApiResponsePaginationProduct\x12e\n" +
	"\x0eFindByCategory\x12).pb.product.FindAllProductCategoryRequest\x1a(.pb.product.ApiResponsePaginationProduct\x12N\n" +
	"\bFindById\x12\".pb.product.FindByIdProductRequest\x1a\x1e.pb.product.ApiResponseProduct\x12c\n" +
	"\fFindByActive\x12!.pb.product.FindAllProductRequest\x1a0.pb.product.ApiResponsePaginationProductDeleteAt\x12d\n" +
	"\rFindByTrashed\x12!.pb.product.FindAllProductRequest\x1a0.pb.product.ApiResponsePaginationProductDeleteAtB?Z=github.com/MamangRust/monolith-graphql-pointofsale-pb/productb\x06proto3"

var (
	file_product_query_proto_rawDescOnce sync.Once
	file_product_query_proto_rawDescData []byte
)

func file_product_query_proto_rawDescGZIP() []byte {
	file_product_query_proto_rawDescOnce.Do(func() {
		file_product_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_query_proto_rawDesc), len(file_product_query_proto_rawDesc)))
	})
	return file_product_query_proto_rawDescData
}

var file_product_query_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_product_query_proto_goTypes = []any{
	(*FindAllProductRequest)(nil),                // 0: pb.product.FindAllProductRequest
	(*FindAllProductMerchantRequest)(nil),        // 1: pb.product.FindAllProductMerchantRequest
	(*FindAllProductCategoryRequest)(nil),        // 2: pb.product.FindAllProductCategoryRequest
	(*FindByIdProductRequest)(nil),               // 3: pb.product.FindByIdProductRequest
	(*ProductResponse)(nil),                      // 4: pb.product.ProductResponse
	(*ProductResponseDeleteAt)(nil),              // 5: pb.product.ProductResponseDeleteAt
	(*ApiResponseProduct)(nil),                   // 6: pb.product.ApiResponseProduct
	(*ApiResponseProductDeleteAt)(nil),           // 7: pb.product.ApiResponseProductDeleteAt
	(*ApiResponsesProduct)(nil),                  // 8: pb.product.ApiResponsesProduct
	(*ApiResponseProductDelete)(nil),             // 9: pb.product.ApiResponseProductDelete
	(*ApiResponseProductAll)(nil),                // 10: pb.product.ApiResponseProductAll
	(*ApiResponsePaginationProductDeleteAt)(nil), // 11: pb.product.ApiResponsePaginationProductDeleteAt
	(*ApiResponsePaginationProduct)(nil),         // 12: pb.product.ApiResponsePaginationProduct
	(*wrapperspb.StringValue)(nil),               // 13: google.protobuf.StringValue
	(*api.PaginationMeta)(nil),                   // 14: pb.api.PaginationMeta
}
var file_product_query_proto_depIdxs = []int32{
	13, // 0: pb.product.ProductResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	4,  // 1: pb.product.ApiResponseProduct.data:type_name -> pb.product.ProductResponse
	5,  // 2: pb.product.ApiResponseProductDeleteAt.data:type_name -> pb.product.ProductResponseDeleteAt
	4,  // 3: pb.product.ApiResponsesProduct.data:type_name -> pb.product.ProductResponse
	5,  // 4: pb.product.ApiResponsePaginationProductDeleteAt.data:type_name -> pb.product.ProductResponseDeleteAt
	14, // 5: pb.product.ApiResponsePaginationProductDeleteAt.pagination:type_name -> pb.api.PaginationMeta
	4,  // 6: pb.product.ApiResponsePaginationProduct.data:type_name -> pb.product.ProductResponse
	14, // 7: pb.product.ApiResponsePaginationProduct.pagination:type_name -> pb.api.PaginationMeta
	0,  // 8: pb.product.ProductQueryService.FindAll:input_type -> pb.product.FindAllProductRequest
	1,  // 9: pb.product.ProductQueryService.FindByMerchant:input_type -> pb.product.FindAllProductMerchantRequest
	2,  // 10: pb.product.ProductQueryService.FindByCategory:input_type -> pb.product.FindAllProductCategoryRequest
	3,  // 11: pb.product.ProductQueryService.FindById:input_type -> pb.product.FindByIdProductRequest
	0,  // 12: pb.product.ProductQueryService.FindByActive:input_type -> pb.product.FindAllProductRequest
	0,  // 13: pb.product.ProductQueryService.FindByTrashed:input_type -> pb.product.FindAllProductRequest
	12, // 14: pb.product.ProductQueryService.FindAll:output_type -> pb.product.ApiResponsePaginationProduct
	12, // 15: pb.product.ProductQueryService.FindByMerchant:output_type -> pb.product.ApiResponsePaginationProduct
	12, // 16: pb.product.ProductQueryService.FindByCategory:output_type -> pb.product.ApiResponsePaginationProduct
	6,  // 17: pb.product.ProductQueryService.FindById:output_type -> pb.product.ApiResponseProduct
	11, // 18: pb.product.ProductQueryService.FindByActive:output_type -> pb.product.ApiResponsePaginationProductDeleteAt
	11, // 19: pb.product.ProductQueryService.FindByTrashed:output_type -> pb.product.ApiResponsePaginationProductDeleteAt
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_product_query_proto_init() }
func file_product_query_proto_init() {
	if File_product_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_query_proto_rawDesc), len(file_product_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_query_proto_goTypes,
		DependencyIndexes: file_product_query_proto_depIdxs,
		MessageInfos:      file_product_query_proto_msgTypes,
	}.Build()
	File_product_query_proto = out.File
	file_product_query_proto_goTypes = nil
	file_product_query_proto_depIdxs = nil
}
