// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: transaction/command.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CashierId     int32                  `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentStatus string                 `protobuf:"bytes,5,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_transaction_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateTransactionRequest) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *CreateTransactionRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

type UpdateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int32                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CashierId     int32                  `protobuf:"varint,3,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount        int32                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentStatus string                 `protobuf:"bytes,6,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_transaction_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateTransactionRequest) GetTransactionId() int32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *UpdateTransactionRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateTransactionRequest) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

var File_transaction_command_proto protoreflect.FileDescriptor

const file_transaction_command_proto_rawDesc = "" +
	"\n" +
	"\x19transaction/command.proto\x12\x0epb.transaction\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17transaction/query.proto\"\xba\x01\n" +
	"\x18CreateTransactionRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x05R\tcashierId\x12%\n" +
	"\x0epayment_method\x18\x03 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12%\n" +
	"\x0epayment_status\x18\x05 \x01(\tR\rpaymentStatus\"\xe1\x01\n" +
	"\x18UpdateTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x05R\rtransactionId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x03 \x01(\x05R\tcashierId\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x05R\x06amount\x12%\n" +
	"\x0epayment_status\x18\x06 \x01(\tR\rpaymentStatus2\xef\x05\n" +
	"\x19TransactionCommandService\x12Z\n" +
	"\x06Create\x12(.pb.transaction.CreateTransactionRequest\x1a&.pb.transaction.ApiResponseTransaction\x12Z\n" +
	"\x06Update\x12(.pb.transaction.UpdateTransactionRequest\x1a&.pb.transaction.ApiResponseTransaction\x12p\n" +
	"\x12TrashedTransaction\x12*.pb.transaction.FindByIdTransactionRequest\x1a..pb.transaction.ApiResponseTransactionDeleteAt\x12p\n" +
	"\x12RestoreTransaction\x12*.pb.transaction.FindByIdTransactionRequest\x1a..pb.transaction.ApiResponseTransactionDeleteAt\x12v\n" +
	"\x1aDeleteTransactionPermanent\x12*.pb.transaction.FindByIdTransactionRequest\x1a,.pb.transaction.ApiResponseTransactionDelete\x12Z\n" +
	"\x15RestoreAllTransaction\x12\x16.google.protobuf.Empty\x1a).pb.transaction.ApiResponseTransactionAll\x12b\n" +
	"\x1dDeleteAllTransactionPermanent\x12\x16.google.protobuf.Empty\x1a).pb.transaction.ApiResponseTransactionAllBCZAgithub.com/MamangRust/monolith-graphql-pointofsale-pb/transactionb\x06proto3"

var (
	file_transaction_command_proto_rawDescOnce sync.Once
	file_transaction_command_proto_rawDescData []byte
)

func file_transaction_command_proto_rawDescGZIP() []byte {
	file_transaction_command_proto_rawDescOnce.Do(func() {
		file_transaction_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_command_proto_rawDesc), len(file_transaction_command_proto_rawDesc)))
	})
	return file_transaction_command_proto_rawDescData
}

var file_transaction_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transaction_command_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil),       // 0: pb.transaction.CreateTransactionRequest
	(*UpdateTransactionRequest)(nil),       // 1: pb.transaction.UpdateTransactionRequest
	(*FindByIdTransactionRequest)(nil),     // 2: pb.transaction.FindByIdTransactionRequest
	(*emptypb.Empty)(nil),                  // 3: google.protobuf.Empty
	(*ApiResponseTransaction)(nil),         // 4: pb.transaction.ApiResponseTransaction
	(*ApiResponseTransactionDeleteAt)(nil), // 5: pb.transaction.ApiResponseTransactionDeleteAt
	(*ApiResponseTransactionDelete)(nil),   // 6: pb.transaction.ApiResponseTransactionDelete
	(*ApiResponseTransactionAll)(nil),      // 7: pb.transaction.ApiResponseTransactionAll
}
var file_transaction_command_proto_depIdxs = []int32{
	0, // 0: pb.transaction.TransactionCommandService.Create:input_type -> pb.transaction.CreateTransactionRequest
	1, // 1: pb.transaction.TransactionCommandService.Update:input_type -> pb.transaction.UpdateTransactionRequest
	2, // 2: pb.transaction.TransactionCommandService.TrashedTransaction:input_type -> pb.transaction.FindByIdTransactionRequest
	2, // 3: pb.transaction.TransactionCommandService.RestoreTransaction:input_type -> pb.transaction.FindByIdTransactionRequest
	2, // 4: pb.transaction.TransactionCommandService.DeleteTransactionPermanent:input_type -> pb.transaction.FindByIdTransactionRequest
	3, // 5: pb.transaction.TransactionCommandService.RestoreAllTransaction:input_type -> google.protobuf.Empty
	3, // 6: pb.transaction.TransactionCommandService.DeleteAllTransactionPermanent:input_type -> google.protobuf.Empty
	4, // 7: pb.transaction.TransactionCommandService.Create:output_type -> pb.transaction.ApiResponseTransaction
	4, // 8: pb.transaction.TransactionCommandService.Update:output_type -> pb.transaction.ApiResponseTransaction
	5, // 9: pb.transaction.TransactionCommandService.TrashedTransaction:output_type -> pb.transaction.ApiResponseTransactionDeleteAt
	5, // 10: pb.transaction.TransactionCommandService.RestoreTransaction:output_type -> pb.transaction.ApiResponseTransactionDeleteAt
	6, // 11: pb.transaction.TransactionCommandService.DeleteTransactionPermanent:output_type -> pb.transaction.ApiResponseTransactionDelete
	7, // 12: pb.transaction.TransactionCommandService.RestoreAllTransaction:output_type -> pb.transaction.ApiResponseTransactionAll
	7, // 13: pb.transaction.TransactionCommandService.DeleteAllTransactionPermanent:output_type -> pb.transaction.ApiResponseTransactionAll
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_command_proto_init() }
func file_transaction_command_proto_init() {
	if File_transaction_command_proto != nil {
		return
	}
	file_transaction_query_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_command_proto_rawDesc), len(file_transaction_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_command_proto_goTypes,
		DependencyIndexes: file_transaction_command_proto_depIdxs,
		MessageInfos:      file_transaction_command_proto_msgTypes,
	}.Build()
	File_transaction_command_proto = out.File
	file_transaction_command_proto_goTypes = nil
	file_transaction_command_proto_depIdxs = nil
}
