// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: transaction/query.proto

package transaction

import (
	api "github.com/MamangRust/monolith-graphql-pointofsale-pb/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllTransactionRequest) Reset() {
	*x = FindAllTransactionRequest{}
	mi := &file_transaction_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTransactionRequest) ProtoMessage() {}

func (x *FindAllTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTransactionRequest.ProtoReflect.Descriptor instead.
func (*FindAllTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllTransactionRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllTransactionRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllTransactionRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindAllTransactionMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllTransactionMerchantRequest) Reset() {
	*x = FindAllTransactionMerchantRequest{}
	mi := &file_transaction_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllTransactionMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTransactionMerchantRequest) ProtoMessage() {}

func (x *FindAllTransactionMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTransactionMerchantRequest.ProtoReflect.Descriptor instead.
func (*FindAllTransactionMerchantRequest) Descriptor() ([]byte, []int) {
	return file_transaction_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllTransactionMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FindAllTransactionMerchantRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllTransactionMerchantRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllTransactionMerchantRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdTransactionRequest) Reset() {
	*x = FindByIdTransactionRequest{}
	mi := &file_transaction_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdTransactionRequest) ProtoMessage() {}

func (x *FindByIdTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdTransactionRequest.ProtoReflect.Descriptor instead.
func (*FindByIdTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_query_proto_rawDescGZIP(), []int{2}
}

func (x *FindByIdTransactionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MerchantId    int32                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount        int32                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ChangeAmount  int32                  `protobuf:"varint,6,opt,name=change_amount,json=changeAmount,proto3" json:"change_amount,omitempty"`
	PaymentStatus string                 `protobuf:"bytes,7,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_transaction_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_query_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *TransactionResponse) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *TransactionResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResponse) GetChangeAmount() int32 {
	if x != nil {
		return x.ChangeAmount
	}
	return 0
}

func (x *TransactionResponse) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *TransactionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransactionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TransactionResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int32                   `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MerchantId    int32                   `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PaymentMethod string                  `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Amount        int32                   `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ChangeAmount  int32                   `protobuf:"varint,6,opt,name=change_amount,json=changeAmount,proto3" json:"change_amount,omitempty"`
	PaymentStatus string                  `protobuf:"bytes,7,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponseDeleteAt) Reset() {
	*x = TransactionResponseDeleteAt{}
	mi := &file_transaction_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponseDeleteAt) ProtoMessage() {}

func (x *TransactionResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*TransactionResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_transaction_query_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetChangeAmount() int32 {
	if x != nil {
		return x.ChangeAmount
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TransactionResponse   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransaction) Reset() {
	*x = ApiResponseTransaction{}
	mi := &file_transaction_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransaction) ProtoMessage() {}

func (x *ApiResponseTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransaction.ProtoReflect.Descriptor instead.
func (*ApiResponseTransaction) Descriptor() ([]byte, []int) {
	return file_transaction_query_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponseTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransaction) GetData() *TransactionResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionDeleteAt struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        string                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TransactionResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionDeleteAt) Reset() {
	*x = ApiResponseTransactionDeleteAt{}
	mi := &file_transaction_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionDeleteAt) ProtoMessage() {}

func (x *ApiResponseTransactionDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionDeleteAt) Descriptor() ([]byte, []int) {
	return file_transaction_query_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseTransactionDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionDeleteAt) GetData() *TransactionResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesTransaction) Reset() {
	*x = ApiResponsesTransaction{}
	mi := &file_transaction_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesTransaction) ProtoMessage() {}

func (x *ApiResponsesTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesTransaction.ProtoReflect.Descriptor instead.
func (*ApiResponsesTransaction) Descriptor() ([]byte, []int) {
	return file_transaction_query_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponsesTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesTransaction) GetData() []*TransactionResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionDelete) Reset() {
	*x = ApiResponseTransactionDelete{}
	mi := &file_transaction_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionDelete) ProtoMessage() {}

func (x *ApiResponseTransactionDelete) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionDelete) Descriptor() ([]byte, []int) {
	return file_transaction_query_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponseTransactionDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseTransactionAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionAll) Reset() {
	*x = ApiResponseTransactionAll{}
	mi := &file_transaction_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionAll) ProtoMessage() {}

func (x *ApiResponseTransactionAll) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionAll.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionAll) Descriptor() ([]byte, []int) {
	return file_transaction_query_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponseTransactionAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationTransactionDeleteAt struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Status        string                         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *api.PaginationMeta            `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationTransactionDeleteAt) Reset() {
	*x = ApiResponsePaginationTransactionDeleteAt{}
	mi := &file_transaction_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationTransactionDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationTransactionDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationTransactionDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationTransactionDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationTransactionDeleteAt) Descriptor() ([]byte, []int) {
	return file_transaction_query_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponsePaginationTransactionDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationTransactionDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationTransactionDeleteAt) GetData() []*TransactionResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationTransactionDeleteAt) GetPagination() *api.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *api.PaginationMeta    `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationTransaction) Reset() {
	*x = ApiResponsePaginationTransaction{}
	mi := &file_transaction_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationTransaction) ProtoMessage() {}

func (x *ApiResponsePaginationTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationTransaction.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationTransaction) Descriptor() ([]byte, []int) {
	return file_transaction_query_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponsePaginationTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationTransaction) GetData() []*TransactionResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationTransaction) GetPagination() *api.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_transaction_query_proto protoreflect.FileDescriptor

const file_transaction_query_proto_rawDesc = "" +
	"\n" +
	"\x17transaction/query.proto\x12\x0epb.transaction\x1a\rapi/api.proto\x1a\x1egoogle/protobuf/wrappers.proto\"d\n" +
	"\x19FindAllTransactionRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x8d\x01\n" +
	"!FindAllTransactionMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\",\n" +
	"\x1aFindByIdTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xaa\x02\n" +
	"\x13TransactionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x05R\n" +
	"merchantId\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x05R\x06amount\x12#\n" +
	"\rchange_amount\x18\x06 \x01(\x05R\fchangeAmount\x12%\n" +
	"\x0epayment_status\x18\a \x01(\tR\rpaymentStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xef\x02\n" +
	"\x1bTransactionResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x05R\n" +
	"merchantId\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x05R\x06amount\x12#\n" +
	"\rchange_amount\x18\x06 \x01(\x05R\fchangeAmount\x12%\n" +
	"\x0epayment_status\x18\a \x01(\tR\rpaymentStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"\x83\x01\n" +
	"\x16ApiResponseTransaction\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x01(\v2#.pb.transaction.TransactionResponseR\x04data\"\x93\x01\n" +
	"\x1eApiResponseTransactionDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\x04data\x18\x03 \x01(\v2+.pb.transaction.TransactionResponseDeleteAtR\x04data\"\x84\x01\n" +
	"\x17ApiResponsesTransaction\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.pb.transaction.TransactionResponseR\x04data\"P\n" +
	"\x1cApiResponseTransactionDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x19ApiResponseTransactionAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd5\x01\n" +
	"(ApiResponsePaginationTransactionDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\x04data\x18\x03 \x03(\v2+.pb.transaction.TransactionResponseDeleteAtR\x04data\x126\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x16.pb.api.PaginationMetaR\n" +
	"pagination\"\xc5\x01\n" +
	" ApiResponsePaginationTransaction\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.pb.transaction.TransactionResponseR\x04data\x126\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x16.pb.api.PaginationMetaR\n" +
	"pagination2\xc3\x04\n" +
	"\x17TransactionQueryService\x12f\n" +
	"\aFindAll\x12).pb.transaction.FindAllTransactionRequest\x1a0.pb.transaction.ApiResponsePaginationTransaction\x12u\n" +
	"\x0eFindByMerchant\x121.pb.transaction.FindAllTransactionMerchantRequest\x1a0.pb.transaction.ApiResponsePaginationTransaction\x12^\n" +
	"\bFindById\x12*.pb.transaction.FindByIdTransactionRequest\x1a&.pb.transaction.ApiResponseTransaction\x12s\n" +
	"\fFindByActive\x12).pb.transaction.FindAllTransactionRequest\x1a8.pb.transaction.ApiResponsePaginationTransactionDeleteAt\x12t\n" +
	"\rFindByTrashed\x12).pb.transaction.FindAllTransactionRequest\x1a8.pb.transaction.ApiResponsePaginationTransactionDeleteAtBCZAgithub.com/MamangRust/monolith-graphql-pointofsale-pb/transactionb\x06proto3"

var (
	file_transaction_query_proto_rawDescOnce sync.Once
	file_transaction_query_proto_rawDescData []byte
)

func file_transaction_query_proto_rawDescGZIP() []byte {
	file_transaction_query_proto_rawDescOnce.Do(func() {
		file_transaction_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_query_proto_rawDesc), len(file_transaction_query_proto_rawDesc)))
	})
	return file_transaction_query_proto_rawDescData
}

var file_transaction_query_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_transaction_query_proto_goTypes = []any{
	(*FindAllTransactionRequest)(nil),                // 0: pb.transaction.FindAllTransactionRequest
	(*FindAllTransactionMerchantRequest)(nil),        // 1: pb.transaction.FindAllTransactionMerchantRequest
	(*FindByIdTransactionRequest)(nil),               // 2: pb.transaction.FindByIdTransactionRequest
	(*TransactionResponse)(nil),                      // 3: pb.transaction.TransactionResponse
	(*TransactionResponseDeleteAt)(nil),              // 4: pb.transaction.TransactionResponseDeleteAt
	(*ApiResponseTransaction)(nil),                   // 5: pb.transaction.ApiResponseTransaction
	(*ApiResponseTransactionDeleteAt)(nil),           // 6: pb.transaction.ApiResponseTransactionDeleteAt
	(*ApiResponsesTransaction)(nil),                  // 7: pb.transaction.ApiResponsesTransaction
	(*ApiResponseTransactionDelete)(nil),             // 8: pb.transaction.ApiResponseTransactionDelete
	(*ApiResponseTransactionAll)(nil),                // 9: pb.transaction.ApiResponseTransactionAll
	(*ApiResponsePaginationTransactionDeleteAt)(nil), // 10: pb.transaction.ApiResponsePaginationTransactionDeleteAt
	(*ApiResponsePaginationTransaction)(nil),         // 11: pb.transaction.ApiResponsePaginationTransaction
	(*wrapperspb.StringValue)(nil),                   // 12: google.protobuf.StringValue
	(*api.PaginationMeta)(nil),                       // 13: pb.api.PaginationMeta
}
var file_transaction_query_proto_depIdxs = []int32{
	12, // 0: pb.transaction.TransactionResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	3,  // 1: pb.transaction.ApiResponseTransaction.data:type_name -> pb.transaction.TransactionResponse
	4,  // 2: pb.transaction.ApiResponseTransactionDeleteAt.data:type_name -> pb.transaction.TransactionResponseDeleteAt
	3,  // 3: pb.transaction.ApiResponsesTransaction.data:type_name -> pb.transaction.TransactionResponse
	4,  // 4: pb.transaction.ApiResponsePaginationTransactionDeleteAt.data:type_name -> pb.transaction.TransactionResponseDeleteAt
	13, // 5: pb.transaction.ApiResponsePaginationTransactionDeleteAt.pagination:type_name -> pb.api.PaginationMeta
	3,  // 6: pb.transaction.ApiResponsePaginationTransaction.data:type_name -> pb.transaction.TransactionResponse
	13, // 7: pb.transaction.ApiResponsePaginationTransaction.pagination:type_name -> pb.api.PaginationMeta
	0,  // 8: pb.transaction.TransactionQueryService.FindAll:input_type -> pb.transaction.FindAllTransactionRequest
	1,  // 9: pb.transaction.TransactionQueryService.FindByMerchant:input_type -> pb.transaction.FindAllTransactionMerchantRequest
	2,  // 10: pb.transaction.TransactionQueryService.FindById:input_type -> pb.transaction.FindByIdTransactionRequest
	0,  // 11: pb.transaction.TransactionQueryService.FindByActive:input_type -> pb.transaction.FindAllTransactionRequest
	0,  // 12: pb.transaction.TransactionQueryService.FindByTrashed:input_type -> pb.transaction.FindAllTransactionRequest
	11, // 13: pb.transaction.TransactionQueryService.FindAll:output_type -> pb.transaction.ApiResponsePaginationTransaction
	11, // 14: pb.transaction.TransactionQueryService.FindByMerchant:output_type -> pb.transaction.ApiResponsePaginationTransaction
	5,  // 15: pb.transaction.TransactionQueryService.FindById:output_type -> pb.transaction.ApiResponseTransaction
	10, // 16: pb.transaction.TransactionQueryService.FindByActive:output_type -> pb.transaction.ApiResponsePaginationTransactionDeleteAt
	10, // 17: pb.transaction.TransactionQueryService.FindByTrashed:output_type -> pb.transaction.ApiResponsePaginationTransactionDeleteAt
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_transaction_query_proto_init() }
func file_transaction_query_proto_init() {
	if File_transaction_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_query_proto_rawDesc), len(file_transaction_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_query_proto_goTypes,
		DependencyIndexes: file_transaction_query_proto_depIdxs,
		MessageInfos:      file_transaction_query_proto_msgTypes,
	}.Build()
	File_transaction_query_proto = out.File
	file_transaction_query_proto_goTypes = nil
	file_transaction_query_proto_depIdxs = nil
}
