// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cashier/cashier_stats.proto

package cashier

import (
	_ "github.com/MamangRust/monolith-graphql-pointofsale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_cashier_cashier_stats_proto protoreflect.FileDescriptor

const file_cashier_cashier_stats_proto_rawDesc = "" +
	"\n" +
	"\x1bcashier/cashier_stats.proto\x12\n" +
	"pb.cashier\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1ccashier/cashier_common.proto2\xb3\n" +
	"\n" +
	"\x13CashierStatsService\x12o\n" +
	"\x15FindMonthlyTotalSales\x12#.pb.cashier.FindYearMonthTotalSales\x1a/.pb.cashier.ApiResponseCashierMonthlyTotalSales\"\x00\x12h\n" +
	"\x14FindYearlyTotalSales\x12\x1e.pb.cashier.FindYearTotalSales\x1a..pb.cashier.ApiResponseCashierYearlyTotalSales\"\x00\x12w\n" +
	"\x19FindMonthlyTotalSalesById\x12'.pb.cashier.FindYearMonthTotalSalesById\x1a/.pb.cashier.ApiResponseCashierMonthlyTotalSales\"\x00\x12p\n" +
	"\x18FindYearlyTotalSalesById\x12\".pb.cashier.FindYearTotalSalesById\x1a..pb.cashier.ApiResponseCashierYearlyTotalSales\"\x00\x12\x83\x01\n" +
	"\x1fFindMonthlyTotalSalesByMerchant\x12-.pb.cashier.FindYearMonthTotalSalesByMerchant\x1a/.pb.cashier.ApiResponseCashierMonthlyTotalSales\"\x00\x12|\n" +
	"\x1eFindYearlyTotalSalesByMerchant\x12(.pb.cashier.FindYearTotalSalesByMerchant\x1a..pb.cashier.ApiResponseCashierYearlyTotalSales\"\x00\x12Y\n" +
	"\x0eFindMonthSales\x12\x1b.pb.cashier.FindYearCashier\x1a(.pb.cashier.ApiResponseCashierMonthSales\"\x00\x12W\n" +
	"\rFindYearSales\x12\x1b.pb.cashier.FindYearCashier\x1a'.pb.cashier.ApiResponseCashierYearSales\"\x00\x12m\n" +
	"\x18FindMonthSalesByMerchant\x12%.pb.cashier.FindYearCashierByMerchant\x1a(.pb.cashier.ApiResponseCashierMonthSales\"\x00\x12k\n" +
	"\x17FindYearSalesByMerchant\x12%.pb.cashier.FindYearCashierByMerchant\x1a'.pb.cashier.ApiResponseCashierYearSales\"\x00\x12a\n" +
	"\x12FindMonthSalesById\x12\x1f.pb.cashier.FindYearCashierById\x1a(.pb.cashier.ApiResponseCashierMonthSales\"\x00\x12_\n" +
	"\x11FindYearSalesById\x12\x1f.pb.cashier.FindYearCashierById\x1a'.pb.cashier.ApiResponseCashierYearSales\"\x00B?Z=github.com/MamangRust/monolith-graphql-pointofsale-pb/cashierb\x06proto3"

var file_cashier_cashier_stats_proto_goTypes = []any{
	(*FindYearMonthTotalSales)(nil),             // 0: pb.cashier.FindYearMonthTotalSales
	(*FindYearTotalSales)(nil),                  // 1: pb.cashier.FindYearTotalSales
	(*FindYearMonthTotalSalesById)(nil),         // 2: pb.cashier.FindYearMonthTotalSalesById
	(*FindYearTotalSalesById)(nil),              // 3: pb.cashier.FindYearTotalSalesById
	(*FindYearMonthTotalSalesByMerchant)(nil),   // 4: pb.cashier.FindYearMonthTotalSalesByMerchant
	(*FindYearTotalSalesByMerchant)(nil),        // 5: pb.cashier.FindYearTotalSalesByMerchant
	(*FindYearCashier)(nil),                     // 6: pb.cashier.FindYearCashier
	(*FindYearCashierByMerchant)(nil),           // 7: pb.cashier.FindYearCashierByMerchant
	(*FindYearCashierById)(nil),                 // 8: pb.cashier.FindYearCashierById
	(*ApiResponseCashierMonthlyTotalSales)(nil), // 9: pb.cashier.ApiResponseCashierMonthlyTotalSales
	(*ApiResponseCashierYearlyTotalSales)(nil),  // 10: pb.cashier.ApiResponseCashierYearlyTotalSales
	(*ApiResponseCashierMonthSales)(nil),        // 11: pb.cashier.ApiResponseCashierMonthSales
	(*ApiResponseCashierYearSales)(nil),         // 12: pb.cashier.ApiResponseCashierYearSales
}
var file_cashier_cashier_stats_proto_depIdxs = []int32{
	0,  // 0: pb.cashier.CashierStatsService.FindMonthlyTotalSales:input_type -> pb.cashier.FindYearMonthTotalSales
	1,  // 1: pb.cashier.CashierStatsService.FindYearlyTotalSales:input_type -> pb.cashier.FindYearTotalSales
	2,  // 2: pb.cashier.CashierStatsService.FindMonthlyTotalSalesById:input_type -> pb.cashier.FindYearMonthTotalSalesById
	3,  // 3: pb.cashier.CashierStatsService.FindYearlyTotalSalesById:input_type -> pb.cashier.FindYearTotalSalesById
	4,  // 4: pb.cashier.CashierStatsService.FindMonthlyTotalSalesByMerchant:input_type -> pb.cashier.FindYearMonthTotalSalesByMerchant
	5,  // 5: pb.cashier.CashierStatsService.FindYearlyTotalSalesByMerchant:input_type -> pb.cashier.FindYearTotalSalesByMerchant
	6,  // 6: pb.cashier.CashierStatsService.FindMonthSales:input_type -> pb.cashier.FindYearCashier
	6,  // 7: pb.cashier.CashierStatsService.FindYearSales:input_type -> pb.cashier.FindYearCashier
	7,  // 8: pb.cashier.CashierStatsService.FindMonthSalesByMerchant:input_type -> pb.cashier.FindYearCashierByMerchant
	7,  // 9: pb.cashier.CashierStatsService.FindYearSalesByMerchant:input_type -> pb.cashier.FindYearCashierByMerchant
	8,  // 10: pb.cashier.CashierStatsService.FindMonthSalesById:input_type -> pb.cashier.FindYearCashierById
	8,  // 11: pb.cashier.CashierStatsService.FindYearSalesById:input_type -> pb.cashier.FindYearCashierById
	9,  // 12: pb.cashier.CashierStatsService.FindMonthlyTotalSales:output_type -> pb.cashier.ApiResponseCashierMonthlyTotalSales
	10, // 13: pb.cashier.CashierStatsService.FindYearlyTotalSales:output_type -> pb.cashier.ApiResponseCashierYearlyTotalSales
	9,  // 14: pb.cashier.CashierStatsService.FindMonthlyTotalSalesById:output_type -> pb.cashier.ApiResponseCashierMonthlyTotalSales
	10, // 15: pb.cashier.CashierStatsService.FindYearlyTotalSalesById:output_type -> pb.cashier.ApiResponseCashierYearlyTotalSales
	9,  // 16: pb.cashier.CashierStatsService.FindMonthlyTotalSalesByMerchant:output_type -> pb.cashier.ApiResponseCashierMonthlyTotalSales
	10, // 17: pb.cashier.CashierStatsService.FindYearlyTotalSalesByMerchant:output_type -> pb.cashier.ApiResponseCashierYearlyTotalSales
	11, // 18: pb.cashier.CashierStatsService.FindMonthSales:output_type -> pb.cashier.ApiResponseCashierMonthSales
	12, // 19: pb.cashier.CashierStatsService.FindYearSales:output_type -> pb.cashier.ApiResponseCashierYearSales
	11, // 20: pb.cashier.CashierStatsService.FindMonthSalesByMerchant:output_type -> pb.cashier.ApiResponseCashierMonthSales
	12, // 21: pb.cashier.CashierStatsService.FindYearSalesByMerchant:output_type -> pb.cashier.ApiResponseCashierYearSales
	11, // 22: pb.cashier.CashierStatsService.FindMonthSalesById:output_type -> pb.cashier.ApiResponseCashierMonthSales
	12, // 23: pb.cashier.CashierStatsService.FindYearSalesById:output_type -> pb.cashier.ApiResponseCashierYearSales
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_cashier_cashier_stats_proto_init() }
func file_cashier_cashier_stats_proto_init() {
	if File_cashier_cashier_stats_proto != nil {
		return
	}
	file_cashier_cashier_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cashier_cashier_stats_proto_rawDesc), len(file_cashier_cashier_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cashier_cashier_stats_proto_goTypes,
		DependencyIndexes: file_cashier_cashier_stats_proto_depIdxs,
	}.Build()
	File_cashier_cashier_stats_proto = out.File
	file_cashier_cashier_stats_proto_goTypes = nil
	file_cashier_cashier_stats_proto_depIdxs = nil
}
