// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: cashier/command.proto

package cashier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCashierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCashierRequest) Reset() {
	*x = CreateCashierRequest{}
	mi := &file_cashier_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCashierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCashierRequest) ProtoMessage() {}

func (x *CreateCashierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCashierRequest.ProtoReflect.Descriptor instead.
func (*CreateCashierRequest) Descriptor() ([]byte, []int) {
	return file_cashier_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCashierRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateCashierRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCashierRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCashierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CashierId     int32                  `protobuf:"varint,1,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCashierRequest) Reset() {
	*x = UpdateCashierRequest{}
	mi := &file_cashier_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCashierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCashierRequest) ProtoMessage() {}

func (x *UpdateCashierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCashierRequest.ProtoReflect.Descriptor instead.
func (*UpdateCashierRequest) Descriptor() ([]byte, []int) {
	return file_cashier_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCashierRequest) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *UpdateCashierRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_cashier_command_proto protoreflect.FileDescriptor

const file_cashier_command_proto_rawDesc = "" +
	"\n" +
	"\x15cashier/command.proto\x12\n" +
	"pb.cashier\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13cashier/query.proto\"d\n" +
	"\x14CreateCashierRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"I\n" +
	"\x14UpdateCashierRequest\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x01 \x01(\x05R\tcashierId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\x85\x05\n" +
	"\x15CashierCommandService\x12Q\n" +
	"\rCreateCashier\x12 .pb.cashier.CreateCashierRequest\x1a\x1e.pb.cashier.ApiResponseCashier\x12Q\n" +
	"\rUpdateCashier\x12 .pb.cashier.UpdateCashierRequest\x1a\x1e.pb.cashier.ApiResponseCashier\x12\\\n" +
	"\x0eTrashedCashier\x12\".pb.cashier.FindByIdCashierRequest\x1a&.pb.cashier.ApiResponseCashierDeleteAt\x12\\\n" +
	"\x0eRestoreCashier\x12\".pb.cashier.FindByIdCashierRequest\x1a&.pb.cashier.ApiResponseCashierDeleteAt\x12b\n" +
	"\x16DeleteCashierPermanent\x12\".pb.cashier.FindByIdCashierRequest\x1a$.pb.cashier.ApiResponseCashierDelete\x12N\n" +
	"\x11RestoreAllCashier\x12\x16.google.protobuf.Empty\x1a!.pb.cashier.ApiResponseCashierAll\x12V\n" +
	"\x19DeleteAllCashierPermanent\x12\x16.google.protobuf.Empty\x1a!.pb.cashier.ApiResponseCashierAllB?Z=github.com/MamangRust/monolith-graphql-pointofsale-pb/cashierb\x06proto3"

var (
	file_cashier_command_proto_rawDescOnce sync.Once
	file_cashier_command_proto_rawDescData []byte
)

func file_cashier_command_proto_rawDescGZIP() []byte {
	file_cashier_command_proto_rawDescOnce.Do(func() {
		file_cashier_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cashier_command_proto_rawDesc), len(file_cashier_command_proto_rawDesc)))
	})
	return file_cashier_command_proto_rawDescData
}

var file_cashier_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cashier_command_proto_goTypes = []any{
	(*CreateCashierRequest)(nil),       // 0: pb.cashier.CreateCashierRequest
	(*UpdateCashierRequest)(nil),       // 1: pb.cashier.UpdateCashierRequest
	(*FindByIdCashierRequest)(nil),     // 2: pb.cashier.FindByIdCashierRequest
	(*emptypb.Empty)(nil),              // 3: google.protobuf.Empty
	(*ApiResponseCashier)(nil),         // 4: pb.cashier.ApiResponseCashier
	(*ApiResponseCashierDeleteAt)(nil), // 5: pb.cashier.ApiResponseCashierDeleteAt
	(*ApiResponseCashierDelete)(nil),   // 6: pb.cashier.ApiResponseCashierDelete
	(*ApiResponseCashierAll)(nil),      // 7: pb.cashier.ApiResponseCashierAll
}
var file_cashier_command_proto_depIdxs = []int32{
	0, // 0: pb.cashier.CashierCommandService.CreateCashier:input_type -> pb.cashier.CreateCashierRequest
	1, // 1: pb.cashier.CashierCommandService.UpdateCashier:input_type -> pb.cashier.UpdateCashierRequest
	2, // 2: pb.cashier.CashierCommandService.TrashedCashier:input_type -> pb.cashier.FindByIdCashierRequest
	2, // 3: pb.cashier.CashierCommandService.RestoreCashier:input_type -> pb.cashier.FindByIdCashierRequest
	2, // 4: pb.cashier.CashierCommandService.DeleteCashierPermanent:input_type -> pb.cashier.FindByIdCashierRequest
	3, // 5: pb.cashier.CashierCommandService.RestoreAllCashier:input_type -> google.protobuf.Empty
	3, // 6: pb.cashier.CashierCommandService.DeleteAllCashierPermanent:input_type -> google.protobuf.Empty
	4, // 7: pb.cashier.CashierCommandService.CreateCashier:output_type -> pb.cashier.ApiResponseCashier
	4, // 8: pb.cashier.CashierCommandService.UpdateCashier:output_type -> pb.cashier.ApiResponseCashier
	5, // 9: pb.cashier.CashierCommandService.TrashedCashier:output_type -> pb.cashier.ApiResponseCashierDeleteAt
	5, // 10: pb.cashier.CashierCommandService.RestoreCashier:output_type -> pb.cashier.ApiResponseCashierDeleteAt
	6, // 11: pb.cashier.CashierCommandService.DeleteCashierPermanent:output_type -> pb.cashier.ApiResponseCashierDelete
	7, // 12: pb.cashier.CashierCommandService.RestoreAllCashier:output_type -> pb.cashier.ApiResponseCashierAll
	7, // 13: pb.cashier.CashierCommandService.DeleteAllCashierPermanent:output_type -> pb.cashier.ApiResponseCashierAll
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cashier_command_proto_init() }
func file_cashier_command_proto_init() {
	if File_cashier_command_proto != nil {
		return
	}
	file_cashier_query_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cashier_command_proto_rawDesc), len(file_cashier_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cashier_command_proto_goTypes,
		DependencyIndexes: file_cashier_command_proto_depIdxs,
		MessageInfos:      file_cashier_command_proto_msgTypes,
	}.Build()
	File_cashier_command_proto = out.File
	file_cashier_command_proto_goTypes = nil
	file_cashier_command_proto_depIdxs = nil
}
