// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: cashier/query.proto

package cashier

import (
	api "github.com/MamangRust/monolith-graphql-pointofsale-pb/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllCashierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllCashierRequest) Reset() {
	*x = FindAllCashierRequest{}
	mi := &file_cashier_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllCashierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllCashierRequest) ProtoMessage() {}

func (x *FindAllCashierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllCashierRequest.ProtoReflect.Descriptor instead.
func (*FindAllCashierRequest) Descriptor() ([]byte, []int) {
	return file_cashier_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllCashierRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllCashierRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllCashierRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByMerchantCashierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByMerchantCashierRequest) Reset() {
	*x = FindByMerchantCashierRequest{}
	mi := &file_cashier_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByMerchantCashierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByMerchantCashierRequest) ProtoMessage() {}

func (x *FindByMerchantCashierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByMerchantCashierRequest.ProtoReflect.Descriptor instead.
func (*FindByMerchantCashierRequest) Descriptor() ([]byte, []int) {
	return file_cashier_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindByMerchantCashierRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FindByMerchantCashierRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindByMerchantCashierRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindByMerchantCashierRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdCashierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdCashierRequest) Reset() {
	*x = FindByIdCashierRequest{}
	mi := &file_cashier_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdCashierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdCashierRequest) ProtoMessage() {}

func (x *FindByIdCashierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdCashierRequest.ProtoReflect.Descriptor instead.
func (*FindByIdCashierRequest) Descriptor() ([]byte, []int) {
	return file_cashier_query_proto_rawDescGZIP(), []int{2}
}

func (x *FindByIdCashierRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CashierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierResponse) Reset() {
	*x = CashierResponse{}
	mi := &file_cashier_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierResponse) ProtoMessage() {}

func (x *CashierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierResponse.ProtoReflect.Descriptor instead.
func (*CashierResponse) Descriptor() ([]byte, []int) {
	return file_cashier_query_proto_rawDescGZIP(), []int{3}
}

func (x *CashierResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CashierResponse) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CashierResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CashierResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CashierResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CashierResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    int32                   `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierResponseDeleteAt) Reset() {
	*x = CashierResponseDeleteAt{}
	mi := &file_cashier_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierResponseDeleteAt) ProtoMessage() {}

func (x *CashierResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*CashierResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_cashier_query_proto_rawDescGZIP(), []int{4}
}

func (x *CashierResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CashierResponseDeleteAt) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CashierResponseDeleteAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CashierResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CashierResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CashierResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseCashier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CashierResponse       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashier) Reset() {
	*x = ApiResponseCashier{}
	mi := &file_cashier_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashier) ProtoMessage() {}

func (x *ApiResponseCashier) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashier.ProtoReflect.Descriptor instead.
func (*ApiResponseCashier) Descriptor() ([]byte, []int) {
	return file_cashier_query_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponseCashier) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashier) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashier) GetData() *CashierResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCashierDeleteAt struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CashierResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierDeleteAt) Reset() {
	*x = ApiResponseCashierDeleteAt{}
	mi := &file_cashier_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierDeleteAt) ProtoMessage() {}

func (x *ApiResponseCashierDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierDeleteAt) Descriptor() ([]byte, []int) {
	return file_cashier_query_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseCashierDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashierDeleteAt) GetData() *CashierResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesCashier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponse     `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesCashier) Reset() {
	*x = ApiResponsesCashier{}
	mi := &file_cashier_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesCashier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesCashier) ProtoMessage() {}

func (x *ApiResponsesCashier) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesCashier.ProtoReflect.Descriptor instead.
func (*ApiResponsesCashier) Descriptor() ([]byte, []int) {
	return file_cashier_query_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponsesCashier) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesCashier) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesCashier) GetData() []*CashierResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCashierDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierDelete) Reset() {
	*x = ApiResponseCashierDelete{}
	mi := &file_cashier_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierDelete) ProtoMessage() {}

func (x *ApiResponseCashierDelete) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierDelete) Descriptor() ([]byte, []int) {
	return file_cashier_query_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponseCashierDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseCashierAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierAll) Reset() {
	*x = ApiResponseCashierAll{}
	mi := &file_cashier_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierAll) ProtoMessage() {}

func (x *ApiResponseCashierAll) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierAll.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierAll) Descriptor() ([]byte, []int) {
	return file_cashier_query_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponseCashierAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationCashierDeleteAt struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        string                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *api.PaginationMeta        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationCashierDeleteAt) Reset() {
	*x = ApiResponsePaginationCashierDeleteAt{}
	mi := &file_cashier_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationCashierDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationCashierDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationCashierDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationCashierDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationCashierDeleteAt) Descriptor() ([]byte, []int) {
	return file_cashier_query_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponsePaginationCashierDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationCashierDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationCashierDeleteAt) GetData() []*CashierResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationCashierDeleteAt) GetPagination() *api.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationCashier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponse     `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *api.PaginationMeta    `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationCashier) Reset() {
	*x = ApiResponsePaginationCashier{}
	mi := &file_cashier_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationCashier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationCashier) ProtoMessage() {}

func (x *ApiResponsePaginationCashier) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationCashier.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationCashier) Descriptor() ([]byte, []int) {
	return file_cashier_query_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponsePaginationCashier) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationCashier) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationCashier) GetData() []*CashierResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationCashier) GetPagination() *api.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_cashier_query_proto protoreflect.FileDescriptor

const file_cashier_query_proto_rawDesc = "" +
	"\n" +
	"\x13cashier/query.proto\x12\n" +
	"pb.cashier\x1a\rapi/api.proto\x1a\x1egoogle/protobuf/wrappers.proto\"`\n" +
	"\x15FindAllCashierRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x88\x01\n" +
	"\x1cFindByMerchantCashierRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"(\n" +
	"\x16FindByIdCashierRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x94\x01\n" +
	"\x0fCashierResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"\xd9\x01\n" +
	"\x17CashierResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"w\n" +
	"\x12ApiResponseCashier\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.pb.cashier.CashierResponseR\x04data\"\x87\x01\n" +
	"\x1aApiResponseCashierDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x01(\v2#.pb.cashier.CashierResponseDeleteAtR\x04data\"x\n" +
	"\x13ApiResponsesCashier\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x03(\v2\x1b.pb.cashier.CashierResponseR\x04data\"L\n" +
	"\x18ApiResponseCashierDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x15ApiResponseCashierAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc9\x01\n" +
	"$ApiResponsePaginationCashierDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.pb.cashier.CashierResponseDeleteAtR\x04data\x126\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x16.pb.api.PaginationMetaR\n" +
	"pagination\"\xb9\x01\n" +
	"\x1cApiResponsePaginationCashier\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x03(\v2\x1b.pb.cashier.CashierResponseR\x04data\x126\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x16.pb.api.PaginationMetaR\n" +
	"pagination2\xee\x03\n" +
	"\x13CashierQueryService\x12V\n" +
	"\aFindAll\x12!.pb.cashier.FindAllCashierRequest\x1a(.pb.cashier.ApiResponsePaginationCashier\x12N\n" +
	"\bFindById\x12\".pb.cashier.FindByIdCashierRequest\x1a\x1e.pb.cashier.ApiResponseCashier\x12c\n" +
	"\fFindByActive\x12!.pb.cashier.FindAllCashierRequest\x1a0.pb.cashier.ApiResponsePaginationCashierDeleteAt\x12d\n" +
	"\rFindByTrashed\x12!.pb.cashier.FindAllCashierRequest\x1a0.pb.cashier.ApiResponsePaginationCashierDeleteAt\x12d\n" +
	"\x0eFindByMerchant\x12(.pb.cashier.FindByMerchantCashierRequest\x1a(.pb.cashier.ApiResponsePaginationCashierB?Z=github.com/MamangRust/monolith-graphql-pointofsale-pb/cashierb\x06proto3"

var (
	file_cashier_query_proto_rawDescOnce sync.Once
	file_cashier_query_proto_rawDescData []byte
)

func file_cashier_query_proto_rawDescGZIP() []byte {
	file_cashier_query_proto_rawDescOnce.Do(func() {
		file_cashier_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cashier_query_proto_rawDesc), len(file_cashier_query_proto_rawDesc)))
	})
	return file_cashier_query_proto_rawDescData
}

var file_cashier_query_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_cashier_query_proto_goTypes = []any{
	(*FindAllCashierRequest)(nil),                // 0: pb.cashier.FindAllCashierRequest
	(*FindByMerchantCashierRequest)(nil),         // 1: pb.cashier.FindByMerchantCashierRequest
	(*FindByIdCashierRequest)(nil),               // 2: pb.cashier.FindByIdCashierRequest
	(*CashierResponse)(nil),                      // 3: pb.cashier.CashierResponse
	(*CashierResponseDeleteAt)(nil),              // 4: pb.cashier.CashierResponseDeleteAt
	(*ApiResponseCashier)(nil),                   // 5: pb.cashier.ApiResponseCashier
	(*ApiResponseCashierDeleteAt)(nil),           // 6: pb.cashier.ApiResponseCashierDeleteAt
	(*ApiResponsesCashier)(nil),                  // 7: pb.cashier.ApiResponsesCashier
	(*ApiResponseCashierDelete)(nil),             // 8: pb.cashier.ApiResponseCashierDelete
	(*ApiResponseCashierAll)(nil),                // 9: pb.cashier.ApiResponseCashierAll
	(*ApiResponsePaginationCashierDeleteAt)(nil), // 10: pb.cashier.ApiResponsePaginationCashierDeleteAt
	(*ApiResponsePaginationCashier)(nil),         // 11: pb.cashier.ApiResponsePaginationCashier
	(*wrapperspb.StringValue)(nil),               // 12: google.protobuf.StringValue
	(*api.PaginationMeta)(nil),                   // 13: pb.api.PaginationMeta
}
var file_cashier_query_proto_depIdxs = []int32{
	12, // 0: pb.cashier.CashierResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	3,  // 1: pb.cashier.ApiResponseCashier.data:type_name -> pb.cashier.CashierResponse
	4,  // 2: pb.cashier.ApiResponseCashierDeleteAt.data:type_name -> pb.cashier.CashierResponseDeleteAt
	3,  // 3: pb.cashier.ApiResponsesCashier.data:type_name -> pb.cashier.CashierResponse
	4,  // 4: pb.cashier.ApiResponsePaginationCashierDeleteAt.data:type_name -> pb.cashier.CashierResponseDeleteAt
	13, // 5: pb.cashier.ApiResponsePaginationCashierDeleteAt.pagination:type_name -> pb.api.PaginationMeta
	3,  // 6: pb.cashier.ApiResponsePaginationCashier.data:type_name -> pb.cashier.CashierResponse
	13, // 7: pb.cashier.ApiResponsePaginationCashier.pagination:type_name -> pb.api.PaginationMeta
	0,  // 8: pb.cashier.CashierQueryService.FindAll:input_type -> pb.cashier.FindAllCashierRequest
	2,  // 9: pb.cashier.CashierQueryService.FindById:input_type -> pb.cashier.FindByIdCashierRequest
	0,  // 10: pb.cashier.CashierQueryService.FindByActive:input_type -> pb.cashier.FindAllCashierRequest
	0,  // 11: pb.cashier.CashierQueryService.FindByTrashed:input_type -> pb.cashier.FindAllCashierRequest
	1,  // 12: pb.cashier.CashierQueryService.FindByMerchant:input_type -> pb.cashier.FindByMerchantCashierRequest
	11, // 13: pb.cashier.CashierQueryService.FindAll:output_type -> pb.cashier.ApiResponsePaginationCashier
	5,  // 14: pb.cashier.CashierQueryService.FindById:output_type -> pb.cashier.ApiResponseCashier
	10, // 15: pb.cashier.CashierQueryService.FindByActive:output_type -> pb.cashier.ApiResponsePaginationCashierDeleteAt
	10, // 16: pb.cashier.CashierQueryService.FindByTrashed:output_type -> pb.cashier.ApiResponsePaginationCashierDeleteAt
	11, // 17: pb.cashier.CashierQueryService.FindByMerchant:output_type -> pb.cashier.ApiResponsePaginationCashier
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_cashier_query_proto_init() }
func file_cashier_query_proto_init() {
	if File_cashier_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cashier_query_proto_rawDesc), len(file_cashier_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cashier_query_proto_goTypes,
		DependencyIndexes: file_cashier_query_proto_depIdxs,
		MessageInfos:      file_cashier_query_proto_msgTypes,
	}.Build()
	File_cashier_query_proto = out.File
	file_cashier_query_proto_goTypes = nil
	file_cashier_query_proto_depIdxs = nil
}
