// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: cashier/stats.proto

package cashier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindYearCashier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearCashier) Reset() {
	*x = FindYearCashier{}
	mi := &file_cashier_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearCashier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearCashier) ProtoMessage() {}

func (x *FindYearCashier) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearCashier.ProtoReflect.Descriptor instead.
func (*FindYearCashier) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{0}
}

func (x *FindYearCashier) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearCashierByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearCashierByMerchant) Reset() {
	*x = FindYearCashierByMerchant{}
	mi := &file_cashier_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearCashierByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearCashierByMerchant) ProtoMessage() {}

func (x *FindYearCashierByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearCashierByMerchant.ProtoReflect.Descriptor instead.
func (*FindYearCashierByMerchant) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{1}
}

func (x *FindYearCashierByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FindYearCashierByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearCashierById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CashierId     int32                  `protobuf:"varint,1,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearCashierById) Reset() {
	*x = FindYearCashierById{}
	mi := &file_cashier_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearCashierById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearCashierById) ProtoMessage() {}

func (x *FindYearCashierById) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearCashierById.ProtoReflect.Descriptor instead.
func (*FindYearCashierById) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{2}
}

func (x *FindYearCashierById) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *FindYearCashierById) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearMonthTotalSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearMonthTotalSales) Reset() {
	*x = FindYearMonthTotalSales{}
	mi := &file_cashier_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearMonthTotalSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearMonthTotalSales) ProtoMessage() {}

func (x *FindYearMonthTotalSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearMonthTotalSales.ProtoReflect.Descriptor instead.
func (*FindYearMonthTotalSales) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{3}
}

func (x *FindYearMonthTotalSales) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearMonthTotalSales) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type FindYearTotalSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTotalSales) Reset() {
	*x = FindYearTotalSales{}
	mi := &file_cashier_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTotalSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTotalSales) ProtoMessage() {}

func (x *FindYearTotalSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTotalSales.ProtoReflect.Descriptor instead.
func (*FindYearTotalSales) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{4}
}

func (x *FindYearTotalSales) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearMonthTotalSalesById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	CashierId     int32                  `protobuf:"varint,3,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearMonthTotalSalesById) Reset() {
	*x = FindYearMonthTotalSalesById{}
	mi := &file_cashier_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearMonthTotalSalesById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearMonthTotalSalesById) ProtoMessage() {}

func (x *FindYearMonthTotalSalesById) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearMonthTotalSalesById.ProtoReflect.Descriptor instead.
func (*FindYearMonthTotalSalesById) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{5}
}

func (x *FindYearMonthTotalSalesById) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearMonthTotalSalesById) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *FindYearMonthTotalSalesById) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

type FindYearTotalSalesById struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	CashierId     int32                  `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTotalSalesById) Reset() {
	*x = FindYearTotalSalesById{}
	mi := &file_cashier_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTotalSalesById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTotalSalesById) ProtoMessage() {}

func (x *FindYearTotalSalesById) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTotalSalesById.ProtoReflect.Descriptor instead.
func (*FindYearTotalSalesById) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{6}
}

func (x *FindYearTotalSalesById) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearTotalSalesById) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

type FindYearMonthTotalSalesByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	MerchantId    int32                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearMonthTotalSalesByMerchant) Reset() {
	*x = FindYearMonthTotalSalesByMerchant{}
	mi := &file_cashier_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearMonthTotalSalesByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearMonthTotalSalesByMerchant) ProtoMessage() {}

func (x *FindYearMonthTotalSalesByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearMonthTotalSalesByMerchant.ProtoReflect.Descriptor instead.
func (*FindYearMonthTotalSalesByMerchant) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{7}
}

func (x *FindYearMonthTotalSalesByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearMonthTotalSalesByMerchant) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *FindYearMonthTotalSalesByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type FindYearTotalSalesByMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	MerchantId    int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTotalSalesByMerchant) Reset() {
	*x = FindYearTotalSalesByMerchant{}
	mi := &file_cashier_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTotalSalesByMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTotalSalesByMerchant) ProtoMessage() {}

func (x *FindYearTotalSalesByMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTotalSalesByMerchant.ProtoReflect.Descriptor instead.
func (*FindYearTotalSalesByMerchant) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{8}
}

func (x *FindYearTotalSalesByMerchant) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearTotalSalesByMerchant) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type CashierResponseMonthSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	CashierId     int32                  `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	CashierName   string                 `protobuf:"bytes,3,opt,name=cashier_name,json=cashierName,proto3" json:"cashier_name,omitempty"`
	OrderCount    int32                  `protobuf:"varint,4,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	TotalSales    int32                  `protobuf:"varint,5,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierResponseMonthSales) Reset() {
	*x = CashierResponseMonthSales{}
	mi := &file_cashier_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierResponseMonthSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierResponseMonthSales) ProtoMessage() {}

func (x *CashierResponseMonthSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierResponseMonthSales.ProtoReflect.Descriptor instead.
func (*CashierResponseMonthSales) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{9}
}

func (x *CashierResponseMonthSales) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *CashierResponseMonthSales) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *CashierResponseMonthSales) GetCashierName() string {
	if x != nil {
		return x.CashierName
	}
	return ""
}

func (x *CashierResponseMonthSales) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *CashierResponseMonthSales) GetTotalSales() int32 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

type CashierResponseYearSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	CashierId     int32                  `protobuf:"varint,2,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	CashierName   string                 `protobuf:"bytes,3,opt,name=cashier_name,json=cashierName,proto3" json:"cashier_name,omitempty"`
	OrderCount    int32                  `protobuf:"varint,4,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	TotalSales    int32                  `protobuf:"varint,5,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierResponseYearSales) Reset() {
	*x = CashierResponseYearSales{}
	mi := &file_cashier_stats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierResponseYearSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierResponseYearSales) ProtoMessage() {}

func (x *CashierResponseYearSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierResponseYearSales.ProtoReflect.Descriptor instead.
func (*CashierResponseYearSales) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{10}
}

func (x *CashierResponseYearSales) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *CashierResponseYearSales) GetCashierId() int32 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *CashierResponseYearSales) GetCashierName() string {
	if x != nil {
		return x.CashierName
	}
	return ""
}

func (x *CashierResponseYearSales) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *CashierResponseYearSales) GetTotalSales() int32 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

type CashierResponseMonthTotalSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	TotalSales    int32                  `protobuf:"varint,6,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierResponseMonthTotalSales) Reset() {
	*x = CashierResponseMonthTotalSales{}
	mi := &file_cashier_stats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierResponseMonthTotalSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierResponseMonthTotalSales) ProtoMessage() {}

func (x *CashierResponseMonthTotalSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierResponseMonthTotalSales.ProtoReflect.Descriptor instead.
func (*CashierResponseMonthTotalSales) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{11}
}

func (x *CashierResponseMonthTotalSales) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *CashierResponseMonthTotalSales) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *CashierResponseMonthTotalSales) GetTotalSales() int32 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

type CashierResponseYearTotalSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalSales    int32                  `protobuf:"varint,2,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashierResponseYearTotalSales) Reset() {
	*x = CashierResponseYearTotalSales{}
	mi := &file_cashier_stats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashierResponseYearTotalSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashierResponseYearTotalSales) ProtoMessage() {}

func (x *CashierResponseYearTotalSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashierResponseYearTotalSales.ProtoReflect.Descriptor instead.
func (*CashierResponseYearTotalSales) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{12}
}

func (x *CashierResponseYearTotalSales) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *CashierResponseYearTotalSales) GetTotalSales() int32 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

type ApiResponseCashierMonthSales struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        string                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponseMonthSales `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierMonthSales) Reset() {
	*x = ApiResponseCashierMonthSales{}
	mi := &file_cashier_stats_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierMonthSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierMonthSales) ProtoMessage() {}

func (x *ApiResponseCashierMonthSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierMonthSales.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierMonthSales) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{13}
}

func (x *ApiResponseCashierMonthSales) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierMonthSales) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashierMonthSales) GetData() []*CashierResponseMonthSales {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCashierYearSales struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponseYearSales `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierYearSales) Reset() {
	*x = ApiResponseCashierYearSales{}
	mi := &file_cashier_stats_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierYearSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierYearSales) ProtoMessage() {}

func (x *ApiResponseCashierYearSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierYearSales.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierYearSales) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{14}
}

func (x *ApiResponseCashierYearSales) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierYearSales) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashierYearSales) GetData() []*CashierResponseYearSales {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCashierMonthlyTotalSales struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponseMonthTotalSales `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierMonthlyTotalSales) Reset() {
	*x = ApiResponseCashierMonthlyTotalSales{}
	mi := &file_cashier_stats_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierMonthlyTotalSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierMonthlyTotalSales) ProtoMessage() {}

func (x *ApiResponseCashierMonthlyTotalSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierMonthlyTotalSales.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierMonthlyTotalSales) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{15}
}

func (x *ApiResponseCashierMonthlyTotalSales) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierMonthlyTotalSales) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashierMonthlyTotalSales) GetData() []*CashierResponseMonthTotalSales {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCashierYearlyTotalSales struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        string                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CashierResponseYearTotalSales `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCashierYearlyTotalSales) Reset() {
	*x = ApiResponseCashierYearlyTotalSales{}
	mi := &file_cashier_stats_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCashierYearlyTotalSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCashierYearlyTotalSales) ProtoMessage() {}

func (x *ApiResponseCashierYearlyTotalSales) ProtoReflect() protoreflect.Message {
	mi := &file_cashier_stats_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCashierYearlyTotalSales.ProtoReflect.Descriptor instead.
func (*ApiResponseCashierYearlyTotalSales) Descriptor() ([]byte, []int) {
	return file_cashier_stats_proto_rawDescGZIP(), []int{16}
}

func (x *ApiResponseCashierYearlyTotalSales) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCashierYearlyTotalSales) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCashierYearlyTotalSales) GetData() []*CashierResponseYearTotalSales {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_cashier_stats_proto protoreflect.FileDescriptor

const file_cashier_stats_proto_rawDesc = "" +
	"\n" +
	"\x13cashier/stats.proto\x12\n" +
	"pb.cashier\"%\n" +
	"\x0fFindYearCashier\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"P\n" +
	"\x19FindYearCashierByMerchant\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"H\n" +
	"\x13FindYearCashierById\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x01 \x01(\x05R\tcashierId\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"C\n" +
	"\x17FindYearMonthTotalSales\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"(\n" +
	"\x12FindYearTotalSales\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"f\n" +
	"\x1bFindYearMonthTotalSalesById\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x03 \x01(\x05R\tcashierId\"K\n" +
	"\x16FindYearTotalSalesById\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x05R\tcashierId\"n\n" +
	"!FindYearMonthTotalSalesByMerchant\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x05R\n" +
	"merchantId\"S\n" +
	"\x1cFindYearTotalSalesByMerchant\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\"\xb5\x01\n" +
	"\x19CashierResponseMonthSales\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x05R\tcashierId\x12!\n" +
	"\fcashier_name\x18\x03 \x01(\tR\vcashierName\x12\x1f\n" +
	"\vorder_count\x18\x04 \x01(\x05R\n" +
	"orderCount\x12\x1f\n" +
	"\vtotal_sales\x18\x05 \x01(\x05R\n" +
	"totalSales\"\xb2\x01\n" +
	"\x18CashierResponseYearSales\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x02 \x01(\x05R\tcashierId\x12!\n" +
	"\fcashier_name\x18\x03 \x01(\tR\vcashierName\x12\x1f\n" +
	"\vorder_count\x18\x04 \x01(\x05R\n" +
	"orderCount\x12\x1f\n" +
	"\vtotal_sales\x18\x05 \x01(\x05R\n" +
	"totalSales\"k\n" +
	"\x1eCashierResponseMonthTotalSales\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12\x1f\n" +
	"\vtotal_sales\x18\x06 \x01(\x05R\n" +
	"totalSales\"T\n" +
	"\x1dCashierResponseYearTotalSales\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x1f\n" +
	"\vtotal_sales\x18\x02 \x01(\x05R\n" +
	"totalSales\"\x8b\x01\n" +
	"\x1cApiResponseCashierMonthSales\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x03(\v2%.pb.cashier.CashierResponseMonthSalesR\x04data\"\x89\x01\n" +
	"\x1bApiResponseCashierYearSales\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\x04data\x18\x03 \x03(\v2$.pb.cashier.CashierResponseYearSalesR\x04data\"\x97\x01\n" +
	"#ApiResponseCashierMonthlyTotalSales\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x04data\x18\x03 \x03(\v2*.pb.cashier.CashierResponseMonthTotalSalesR\x04data\"\x95\x01\n" +
	"\"ApiResponseCashierYearlyTotalSales\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\x04data\x18\x03 \x03(\v2).pb.cashier.CashierResponseYearTotalSalesR\x04data2\x9b\n" +
	"\n" +
	"\x13CashierStatsService\x12m\n" +
	"\x15FindMonthlyTotalSales\x12#.pb.cashier.FindYearMonthTotalSales\x1a/.pb.cashier.ApiResponseCashierMonthlyTotalSales\x12f\n" +
	"\x14FindYearlyTotalSales\x12\x1e.pb.cashier.FindYearTotalSales\x1a..pb.cashier.ApiResponseCashierYearlyTotalSales\x12u\n" +
	"\x19FindMonthlyTotalSalesById\x12'.pb.cashier.FindYearMonthTotalSalesById\x1a/.pb.cashier.ApiResponseCashierMonthlyTotalSales\x12n\n" +
	"\x18FindYearlyTotalSalesById\x12\".pb.cashier.FindYearTotalSalesById\x1a..pb.cashier.ApiResponseCashierYearlyTotalSales\x12\x81\x01\n" +
	"\x1fFindMonthlyTotalSalesByMerchant\x12-.pb.cashier.FindYearMonthTotalSalesByMerchant\x1a/.pb.cashier.ApiResponseCashierMonthlyTotalSales\x12z\n" +
	"\x1eFindYearlyTotalSalesByMerchant\x12(.pb.cashier.FindYearTotalSalesByMerchant\x1a..pb.cashier.ApiResponseCashierYearlyTotalSales\x12W\n" +
	"\x0eFindMonthSales\x12\x1b.pb.cashier.FindYearCashier\x1a(.pb.cashier.ApiResponseCashierMonthSales\x12U\n" +
	"\rFindYearSales\x12\x1b.pb.cashier.FindYearCashier\x1a'.pb.cashier.ApiResponseCashierYearSales\x12k\n" +
	"\x18FindMonthSalesByMerchant\x12%.pb.cashier.FindYearCashierByMerchant\x1a(.pb.cashier.ApiResponseCashierMonthSales\x12i\n" +
	"\x17FindYearSalesByMerchant\x12%.pb.cashier.FindYearCashierByMerchant\x1a'.pb.cashier.ApiResponseCashierYearSales\x12_\n" +
	"\x12FindMonthSalesById\x12\x1f.pb.cashier.FindYearCashierById\x1a(.pb.cashier.ApiResponseCashierMonthSales\x12]\n" +
	"\x11FindYearSalesById\x12\x1f.pb.cashier.FindYearCashierById\x1a'.pb.cashier.ApiResponseCashierYearSalesB?Z=github.com/MamangRust/monolith-graphql-pointofsale-pb/cashierb\x06proto3"

var (
	file_cashier_stats_proto_rawDescOnce sync.Once
	file_cashier_stats_proto_rawDescData []byte
)

func file_cashier_stats_proto_rawDescGZIP() []byte {
	file_cashier_stats_proto_rawDescOnce.Do(func() {
		file_cashier_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cashier_stats_proto_rawDesc), len(file_cashier_stats_proto_rawDesc)))
	})
	return file_cashier_stats_proto_rawDescData
}

var file_cashier_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_cashier_stats_proto_goTypes = []any{
	(*FindYearCashier)(nil),                     // 0: pb.cashier.FindYearCashier
	(*FindYearCashierByMerchant)(nil),           // 1: pb.cashier.FindYearCashierByMerchant
	(*FindYearCashierById)(nil),                 // 2: pb.cashier.FindYearCashierById
	(*FindYearMonthTotalSales)(nil),             // 3: pb.cashier.FindYearMonthTotalSales
	(*FindYearTotalSales)(nil),                  // 4: pb.cashier.FindYearTotalSales
	(*FindYearMonthTotalSalesById)(nil),         // 5: pb.cashier.FindYearMonthTotalSalesById
	(*FindYearTotalSalesById)(nil),              // 6: pb.cashier.FindYearTotalSalesById
	(*FindYearMonthTotalSalesByMerchant)(nil),   // 7: pb.cashier.FindYearMonthTotalSalesByMerchant
	(*FindYearTotalSalesByMerchant)(nil),        // 8: pb.cashier.FindYearTotalSalesByMerchant
	(*CashierResponseMonthSales)(nil),           // 9: pb.cashier.CashierResponseMonthSales
	(*CashierResponseYearSales)(nil),            // 10: pb.cashier.CashierResponseYearSales
	(*CashierResponseMonthTotalSales)(nil),      // 11: pb.cashier.CashierResponseMonthTotalSales
	(*CashierResponseYearTotalSales)(nil),       // 12: pb.cashier.CashierResponseYearTotalSales
	(*ApiResponseCashierMonthSales)(nil),        // 13: pb.cashier.ApiResponseCashierMonthSales
	(*ApiResponseCashierYearSales)(nil),         // 14: pb.cashier.ApiResponseCashierYearSales
	(*ApiResponseCashierMonthlyTotalSales)(nil), // 15: pb.cashier.ApiResponseCashierMonthlyTotalSales
	(*ApiResponseCashierYearlyTotalSales)(nil),  // 16: pb.cashier.ApiResponseCashierYearlyTotalSales
}
var file_cashier_stats_proto_depIdxs = []int32{
	9,  // 0: pb.cashier.ApiResponseCashierMonthSales.data:type_name -> pb.cashier.CashierResponseMonthSales
	10, // 1: pb.cashier.ApiResponseCashierYearSales.data:type_name -> pb.cashier.CashierResponseYearSales
	11, // 2: pb.cashier.ApiResponseCashierMonthlyTotalSales.data:type_name -> pb.cashier.CashierResponseMonthTotalSales
	12, // 3: pb.cashier.ApiResponseCashierYearlyTotalSales.data:type_name -> pb.cashier.CashierResponseYearTotalSales
	3,  // 4: pb.cashier.CashierStatsService.FindMonthlyTotalSales:input_type -> pb.cashier.FindYearMonthTotalSales
	4,  // 5: pb.cashier.CashierStatsService.FindYearlyTotalSales:input_type -> pb.cashier.FindYearTotalSales
	5,  // 6: pb.cashier.CashierStatsService.FindMonthlyTotalSalesById:input_type -> pb.cashier.FindYearMonthTotalSalesById
	6,  // 7: pb.cashier.CashierStatsService.FindYearlyTotalSalesById:input_type -> pb.cashier.FindYearTotalSalesById
	7,  // 8: pb.cashier.CashierStatsService.FindMonthlyTotalSalesByMerchant:input_type -> pb.cashier.FindYearMonthTotalSalesByMerchant
	8,  // 9: pb.cashier.CashierStatsService.FindYearlyTotalSalesByMerchant:input_type -> pb.cashier.FindYearTotalSalesByMerchant
	0,  // 10: pb.cashier.CashierStatsService.FindMonthSales:input_type -> pb.cashier.FindYearCashier
	0,  // 11: pb.cashier.CashierStatsService.FindYearSales:input_type -> pb.cashier.FindYearCashier
	1,  // 12: pb.cashier.CashierStatsService.FindMonthSalesByMerchant:input_type -> pb.cashier.FindYearCashierByMerchant
	1,  // 13: pb.cashier.CashierStatsService.FindYearSalesByMerchant:input_type -> pb.cashier.FindYearCashierByMerchant
	2,  // 14: pb.cashier.CashierStatsService.FindMonthSalesById:input_type -> pb.cashier.FindYearCashierById
	2,  // 15: pb.cashier.CashierStatsService.FindYearSalesById:input_type -> pb.cashier.FindYearCashierById
	15, // 16: pb.cashier.CashierStatsService.FindMonthlyTotalSales:output_type -> pb.cashier.ApiResponseCashierMonthlyTotalSales
	16, // 17: pb.cashier.CashierStatsService.FindYearlyTotalSales:output_type -> pb.cashier.ApiResponseCashierYearlyTotalSales
	15, // 18: pb.cashier.CashierStatsService.FindMonthlyTotalSalesById:output_type -> pb.cashier.ApiResponseCashierMonthlyTotalSales
	16, // 19: pb.cashier.CashierStatsService.FindYearlyTotalSalesById:output_type -> pb.cashier.ApiResponseCashierYearlyTotalSales
	15, // 20: pb.cashier.CashierStatsService.FindMonthlyTotalSalesByMerchant:output_type -> pb.cashier.ApiResponseCashierMonthlyTotalSales
	16, // 21: pb.cashier.CashierStatsService.FindYearlyTotalSalesByMerchant:output_type -> pb.cashier.ApiResponseCashierYearlyTotalSales
	13, // 22: pb.cashier.CashierStatsService.FindMonthSales:output_type -> pb.cashier.ApiResponseCashierMonthSales
	14, // 23: pb.cashier.CashierStatsService.FindYearSales:output_type -> pb.cashier.ApiResponseCashierYearSales
	13, // 24: pb.cashier.CashierStatsService.FindMonthSalesByMerchant:output_type -> pb.cashier.ApiResponseCashierMonthSales
	14, // 25: pb.cashier.CashierStatsService.FindYearSalesByMerchant:output_type -> pb.cashier.ApiResponseCashierYearSales
	13, // 26: pb.cashier.CashierStatsService.FindMonthSalesById:output_type -> pb.cashier.ApiResponseCashierMonthSales
	14, // 27: pb.cashier.CashierStatsService.FindYearSalesById:output_type -> pb.cashier.ApiResponseCashierYearSales
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_cashier_stats_proto_init() }
func file_cashier_stats_proto_init() {
	if File_cashier_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cashier_stats_proto_rawDesc), len(file_cashier_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cashier_stats_proto_goTypes,
		DependencyIndexes: file_cashier_stats_proto_depIdxs,
		MessageInfos:      file_cashier_stats_proto_msgTypes,
	}.Build()
	File_cashier_stats_proto = out.File
	file_cashier_stats_proto_goTypes = nil
	file_cashier_stats_proto_depIdxs = nil
}
