package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	errors "github.com/MamangRust/monolith-graphql-pointofsale-shared/errors"

	"github.com/MamangRust/monolith-graphql-pointofsale-apigateway/internal/model"
	pb "github.com/MamangRust/monolith-graphql-pointofsale-pb/user"
	"github.com/MamangRust/monolith-graphql-pointofsale-shared/domain/requests"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.APIResponseUserResponse, error) {
	return ResolverHandle(r.ResolverHandle, "CreateUser", ctx, func(ctx context.Context) (*model.APIResponseUserResponse, error) {
		req := &requests.CreateUserRequest{
			FirstName:       input.Firstname,
			LastName:        input.Lastname,
			Email:           input.Email,
			Password:        input.Password,
			ConfirmPassword: input.ConfirmPassword,
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.CreateUserRequest{
			Firstname:       req.FirstName,
			Lastname:        req.LastName,
			Email:           req.Email,
			Password:        req.Password,
			ConfirmPassword: req.ConfirmPassword,
		}

		user, err := r.UserGraphql.UserClient.UserCommandClient.Create(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "CreateUser")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUser(user)
		return so, nil
	})
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.APIResponseUserResponse, error) {
	return ResolverHandle(r.ResolverHandle, "UpdateUser", ctx, func(ctx context.Context) (*model.APIResponseUserResponse, error) {
		id := int(input.ID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid user ID")
		}

		var firstName, lastName, email, password, confirmPassword string
		if input.Firstname != nil {
			firstName = *input.Firstname
		}
		if input.Lastname != nil {
			lastName = *input.Lastname
		}
		if input.Email != nil {
			email = *input.Email
		}
		if input.Password != nil {
			password = *input.Password
		}
		if input.ConfirmPassword != nil {
			confirmPassword = *input.ConfirmPassword
		}

		req := &requests.UpdateUserRequest{
			UserID:          &id,
			FirstName:       firstName,
			LastName:        lastName,
			Email:           email,
			Password:        password,
			ConfirmPassword: confirmPassword,
		}

		if err := req.Validate(); err != nil {
			validations := r.parseValidationErrors(err)
			return nil, errors.NewValidationError(validations)
		}

		reqPb := &pb.UpdateUserRequest{
			Id:              int32(*req.UserID),
			Firstname:       req.FirstName,
			Lastname:        req.LastName,
			Email:           req.Email,
			Password:        req.Password,
			ConfirmPassword: req.ConfirmPassword,
		}

		user, err := r.UserGraphql.UserClient.UserCommandClient.Update(ctx, reqPb)
		if err != nil {
			return nil, r.handleGraphQLError(err, "UpdateUser")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUser(user)

		r.UserGraphql.Cache.DeleteUserCache(ctx, id)

		return so, nil
	})
}

// TrashedUser is the resolver for the trashedUser field.
func (r *mutationResolver) TrashedUser(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserResponseDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "TrashedUser", ctx, func(ctx context.Context) (*model.APIResponseUserResponseDeleteAt, error) {
		id := int32(input.ID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid user ID")
		}

		user, err := r.UserGraphql.UserClient.UserCommandClient.TrashedUser(ctx, &pb.FindByIdUserRequest{Id: id})
		if err != nil {
			return nil, r.handleGraphQLError(err, "TrashedUser")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUserDeleteAt(user)

		r.UserGraphql.Cache.DeleteUserCache(ctx, int(id))

		return so, nil
	})
}

// RestoreUser is the resolver for the restoreUser field.
func (r *mutationResolver) RestoreUser(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserResponseDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreUser", ctx, func(ctx context.Context) (*model.APIResponseUserResponseDeleteAt, error) {
		id := int32(input.ID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid user ID")
		}

		user, err := r.UserGraphql.UserClient.UserCommandClient.RestoreUser(ctx, &pb.FindByIdUserRequest{Id: id})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreUser")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUserDeleteAt(user)

		r.UserGraphql.Cache.DeleteUserCache(ctx, int(id))

		return so, nil
	})
}

// DeleteUserPermanent is the resolver for the deleteUserPermanent field.
func (r *mutationResolver) DeleteUserPermanent(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserDelete, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteUserPermanent", ctx, func(ctx context.Context) (*model.APIResponseUserDelete, error) {
		id := int32(input.ID)
		if id == 0 {
			return nil, errors.NewBadRequestError("invalid user ID")
		}

		res, err := r.UserGraphql.UserClient.UserCommandClient.DeleteUserPermanent(ctx, &pb.FindByIdUserRequest{Id: id})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteUserPermanent")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUserDelete(res)

		r.UserGraphql.Cache.DeleteUserCache(ctx, int(id))

		return so, nil
	})
}

// RestoreAllUser is the resolver for the restoreAllUser field.
func (r *mutationResolver) RestoreAllUser(ctx context.Context) (*model.APIResponseUserAll, error) {
	return ResolverHandle(r.ResolverHandle, "RestoreAllUser", ctx, func(ctx context.Context) (*model.APIResponseUserAll, error) {
		res, err := r.UserGraphql.UserClient.UserCommandClient.RestoreAllUser(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "RestoreAllUser")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUserAll(res)
		return so, nil
	})
}

// DeleteAllUserPermanent is the resolver for the deleteAllUserPermanent field.
func (r *mutationResolver) DeleteAllUserPermanent(ctx context.Context) (*model.APIResponseUserAll, error) {
	return ResolverHandle(r.ResolverHandle, "DeleteAllUserPermanent", ctx, func(ctx context.Context) (*model.APIResponseUserAll, error) {
		res, err := r.UserGraphql.UserClient.UserCommandClient.DeleteAllUserPermanent(ctx, &emptypb.Empty{})
		if err != nil {
			return nil, r.handleGraphQLError(err, "DeleteAllUserPermanent")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponseUserAll(res)
		return so, nil
	})
}

// FindAllUsers is the resolver for the findAllUsers field.
func (r *queryResolver) FindAllUsers(ctx context.Context, input *model.FindAllUserInput) (*model.APIResponsePaginationUser, error) {
	return ResolverHandle(r.ResolverHandle, "FindAllUsers", ctx, func(ctx context.Context) (*model.APIResponsePaginationUser, error) {
		var page, pageSize int32
		var search string
		if input != nil {
			if input.Page != nil {
				page = int32(*input.Page)
			}
			if input.PageSize != nil {
				pageSize = int32(*input.PageSize)
			}
			if input.Search != nil {
				search = safeString(input.Search)
			}
		}

		res, err := r.UserGraphql.UserClient.UserQueryClient.FindAll(ctx, &pb.FindAllUserRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindAllUsers")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponsePaginationUser(res)
		return so, nil
	})
}

// FindByIDUser is the resolver for the findByIdUser field.
func (r *queryResolver) FindByIDUser(ctx context.Context, input model.FindByIDUserInput) (*model.APIResponseUserResponse, error) {
	id := int(input.ID)
	if id == 0 {
		return nil, fmt.Errorf("invalid user ID")
	}

	cachedData, found := r.UserGraphql.Cache.GetCachedUserCache(ctx, id)
	if found {
		return cachedData, nil
	}

	user, errResp := r.UserGraphql.UserClient.UserQueryClient.FindById(ctx, &pb.FindByIdUserRequest{
		Id: int32(id),
	})
	if errResp != nil {
		return nil, r.handleGraphQLError(errResp, "FindByIdUser")
	}

	so := r.UserGraphql.Mapping.ToGraphqlResponseUser(user)

	r.UserGraphql.Cache.SetCachedUserCache(ctx, so)

	return so, nil
}

// FindByActiveUsers is the resolver for the findByActiveUsers field.
func (r *queryResolver) FindByActiveUsers(ctx context.Context, input *model.FindAllUserInput) (*model.APIResponsePaginationUserDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByActiveUsers", ctx, func(ctx context.Context) (*model.APIResponsePaginationUserDeleteAt, error) {
		var page, pageSize int32
		var search string
		if input != nil {
			if input.Page != nil {
				page = int32(*input.Page)
			}
			if input.PageSize != nil {
				pageSize = int32(*input.PageSize)
			}
			if input.Search != nil {
				search = safeString(input.Search)
			}
		}

		res, err := r.UserGraphql.UserClient.UserQueryClient.FindByActive(ctx, &pb.FindAllUserRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByActiveUsers")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponsePaginationUserDeleteAt(res)
		return so, nil
	})
}

// FindByTrashedUsers is the resolver for the findByTrashedUsers field.
func (r *queryResolver) FindByTrashedUsers(ctx context.Context, input *model.FindAllUserInput) (*model.APIResponsePaginationUserDeleteAt, error) {
	return ResolverHandle(r.ResolverHandle, "FindByTrashedUsers", ctx, func(ctx context.Context) (*model.APIResponsePaginationUserDeleteAt, error) {
		var page, pageSize int32
		var search string
		if input != nil {
			if input.Page != nil {
				page = int32(*input.Page)
			}
			if input.PageSize != nil {
				pageSize = int32(*input.PageSize)
			}
			if input.Search != nil {
				search = safeString(input.Search)
			}
		}

		res, err := r.UserGraphql.UserClient.UserCommandClient.FindByTrashed(ctx, &pb.FindAllUserRequest{
			Page:     page,
			PageSize: pageSize,
			Search:   search,
		})
		if err != nil {
			return nil, r.handleGraphQLError(err, "FindByTrashedUsers")
		}

		so := r.UserGraphql.Mapping.ToGraphqlResponsePaginationUserDeleteAt(res)
		return so, nil
	})
}
