// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: user/user_common.proto

package user

import (
	common "github.com/MamangRust/monolith-graphql-pointofsale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllUserRequest) Reset() {
	*x = FindAllUserRequest{}
	mi := &file_user_user_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllUserRequest) ProtoMessage() {}

func (x *FindAllUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllUserRequest.ProtoReflect.Descriptor instead.
func (*FindAllUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllUserRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllUserRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdUserRequest) Reset() {
	*x = FindByIdUserRequest{}
	mi := &file_user_user_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdUserRequest) ProtoMessage() {}

func (x *FindByIdUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdUserRequest.ProtoReflect.Descriptor instead.
func (*FindByIdUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{1}
}

func (x *FindByIdUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Firstname       string                 `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname        string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,5,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_user_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *CreateUserRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type UpdateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname       string                 `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname        string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,6,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_user_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *UpdateUserRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname     string                 `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_user_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{4}
}

func (x *UserResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponse) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *UserResponse) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UserResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname     string                  `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                  `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email         string                  `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponseDeleteAt) Reset() {
	*x = UserResponseDeleteAt{}
	mi := &file_user_user_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponseDeleteAt) ProtoMessage() {}

func (x *UserResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*UserResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{5}
}

func (x *UserResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponseDeleteAt) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *UserResponseDeleteAt) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *UserResponseDeleteAt) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserResponse          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseUser) Reset() {
	*x = ApiResponseUser{}
	mi := &file_user_user_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseUser) ProtoMessage() {}

func (x *ApiResponseUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseUser.ProtoReflect.Descriptor instead.
func (*ApiResponseUser) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseUser) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseUser) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseUser) GetData() *UserResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseUserDeleteAt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserResponseDeleteAt  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseUserDeleteAt) Reset() {
	*x = ApiResponseUserDeleteAt{}
	mi := &file_user_user_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseUserDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseUserDeleteAt) ProtoMessage() {}

func (x *ApiResponseUserDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseUserDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseUserDeleteAt) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponseUserDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseUserDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseUserDeleteAt) GetData() *UserResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*UserResponse        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesUser) Reset() {
	*x = ApiResponsesUser{}
	mi := &file_user_user_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesUser) ProtoMessage() {}

func (x *ApiResponsesUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesUser.ProtoReflect.Descriptor instead.
func (*ApiResponsesUser) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponsesUser) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesUser) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesUser) GetData() []*UserResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseUserDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseUserDelete) Reset() {
	*x = ApiResponseUserDelete{}
	mi := &file_user_user_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseUserDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseUserDelete) ProtoMessage() {}

func (x *ApiResponseUserDelete) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseUserDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseUserDelete) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponseUserDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseUserDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseUserAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseUserAll) Reset() {
	*x = ApiResponseUserAll{}
	mi := &file_user_user_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseUserAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseUserAll) ProtoMessage() {}

func (x *ApiResponseUserAll) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseUserAll.ProtoReflect.Descriptor instead.
func (*ApiResponseUserAll) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponseUserAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseUserAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationUserDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*UserResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMeta  `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationUserDeleteAt) Reset() {
	*x = ApiResponsePaginationUserDeleteAt{}
	mi := &file_user_user_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationUserDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationUserDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationUserDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationUserDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationUserDeleteAt) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponsePaginationUserDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationUserDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationUserDeleteAt) GetData() []*UserResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationUserDeleteAt) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*UserResponse        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMeta `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationUser) Reset() {
	*x = ApiResponsePaginationUser{}
	mi := &file_user_user_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationUser) ProtoMessage() {}

func (x *ApiResponsePaginationUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationUser.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationUser) Descriptor() ([]byte, []int) {
	return file_user_user_common_proto_rawDescGZIP(), []int{12}
}

func (x *ApiResponsePaginationUser) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationUser) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationUser) GetData() []*UserResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationUser) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_user_user_common_proto protoreflect.FileDescriptor

const file_user_user_common_proto_rawDesc = "" +
	"\n" +
	"\x16user/user_common.proto\x12\apb.user\x1a\x10common/api.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"]\n" +
	"\x12FindAllUserRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"%\n" +
	"\x13FindByIdUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xaa\x01\n" +
	"\x11CreateUserRequest\x12\x1c\n" +
	"\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\x05 \x01(\tR\x0fconfirmPassword\"\xba\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\x06 \x01(\tR\x0fconfirmPassword\"\xac\x01\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xf1\x01\n" +
	"\x14UserResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"n\n" +
	"\x0fApiResponseUser\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.pb.user.UserResponseR\x04data\"~\n" +
	"\x17ApiResponseUserDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x01(\v2\x1d.pb.user.UserResponseDeleteAtR\x04data\"o\n" +
	"\x10ApiResponsesUser\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.pb.user.UserResponseR\x04data\"I\n" +
	"\x15ApiResponseUserDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x12ApiResponseUserAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc3\x01\n" +
	"!ApiResponsePaginationUserDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.user.UserResponseDeleteAtR\x04data\x129\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\n" +
	"pagination\"\xb3\x01\n" +
	"\x19ApiResponsePaginationUser\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.pb.user.UserResponseR\x04data\x129\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\n" +
	"paginationB<Z:github.com/MamangRust/monolith-graphql-pointofsale-pb/userb\x06proto3"

var (
	file_user_user_common_proto_rawDescOnce sync.Once
	file_user_user_common_proto_rawDescData []byte
)

func file_user_user_common_proto_rawDescGZIP() []byte {
	file_user_user_common_proto_rawDescOnce.Do(func() {
		file_user_user_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_common_proto_rawDesc), len(file_user_user_common_proto_rawDesc)))
	})
	return file_user_user_common_proto_rawDescData
}

var file_user_user_common_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_user_user_common_proto_goTypes = []any{
	(*FindAllUserRequest)(nil),                // 0: pb.user.FindAllUserRequest
	(*FindByIdUserRequest)(nil),               // 1: pb.user.FindByIdUserRequest
	(*CreateUserRequest)(nil),                 // 2: pb.user.CreateUserRequest
	(*UpdateUserRequest)(nil),                 // 3: pb.user.UpdateUserRequest
	(*UserResponse)(nil),                      // 4: pb.user.UserResponse
	(*UserResponseDeleteAt)(nil),              // 5: pb.user.UserResponseDeleteAt
	(*ApiResponseUser)(nil),                   // 6: pb.user.ApiResponseUser
	(*ApiResponseUserDeleteAt)(nil),           // 7: pb.user.ApiResponseUserDeleteAt
	(*ApiResponsesUser)(nil),                  // 8: pb.user.ApiResponsesUser
	(*ApiResponseUserDelete)(nil),             // 9: pb.user.ApiResponseUserDelete
	(*ApiResponseUserAll)(nil),                // 10: pb.user.ApiResponseUserAll
	(*ApiResponsePaginationUserDeleteAt)(nil), // 11: pb.user.ApiResponsePaginationUserDeleteAt
	(*ApiResponsePaginationUser)(nil),         // 12: pb.user.ApiResponsePaginationUser
	(*wrapperspb.StringValue)(nil),            // 13: google.protobuf.StringValue
	(*common.PaginationMeta)(nil),             // 14: pb.common.PaginationMeta
}
var file_user_user_common_proto_depIdxs = []int32{
	13, // 0: pb.user.UserResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	4,  // 1: pb.user.ApiResponseUser.data:type_name -> pb.user.UserResponse
	5,  // 2: pb.user.ApiResponseUserDeleteAt.data:type_name -> pb.user.UserResponseDeleteAt
	4,  // 3: pb.user.ApiResponsesUser.data:type_name -> pb.user.UserResponse
	5,  // 4: pb.user.ApiResponsePaginationUserDeleteAt.data:type_name -> pb.user.UserResponseDeleteAt
	14, // 5: pb.user.ApiResponsePaginationUserDeleteAt.pagination:type_name -> pb.common.PaginationMeta
	4,  // 6: pb.user.ApiResponsePaginationUser.data:type_name -> pb.user.UserResponse
	14, // 7: pb.user.ApiResponsePaginationUser.pagination:type_name -> pb.common.PaginationMeta
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_user_user_common_proto_init() }
func file_user_user_common_proto_init() {
	if File_user_user_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_common_proto_rawDesc), len(file_user_user_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_user_common_proto_goTypes,
		DependencyIndexes: file_user_user_common_proto_depIdxs,
		MessageInfos:      file_user_user_common_proto_msgTypes,
	}.Build()
	File_user_user_common_proto = out.File
	file_user_user_common_proto_goTypes = nil
	file_user_user_common_proto_depIdxs = nil
}
