syntax = "proto3";

package pb.order;

option go_package = "github.com/MamangRust/monolith-graphql-pointofsale-pb/order";

import "api/api.proto";
import "google/protobuf/wrappers.proto";

message FindAllOrderRequest {
  int32 page = 1;
  int32 page_size = 2;
  string search = 3;
}

message FindAllOrderMerchantRequest {
  int32 page = 1;
  int32 page_size = 2;
  string search = 3;
  int32 merchant_id = 4;
}

message FindByIdOrderRequest {
  int32 id = 1;
}

message OrderResponse {
  int32 id = 1;
  int32 merchant_id = 2;
  int32 cashier_id = 3;
  int32 total_price = 4;
  string created_at = 5;
  string updated_at = 6;
}

message OrderResponseDeleteAt {
  int32 id = 1;
  int32 merchant_id = 2;
  int32 cashier_id = 3;
  int32 total_price = 4;
  string created_at = 5;
  string updated_at = 6;
  google.protobuf.StringValue deleted_at = 7;
}

message ApiResponseOrder {
  string status = 1;
  string message = 2;
  OrderResponse data = 3;
}

message ApiResponseOrderDeleteAt {
  string status = 1;
  string message = 2;
  OrderResponseDeleteAt data = 3;
}

message ApiResponsesOrder {
  string status = 1;
  string message = 2;
  repeated OrderResponse data = 3;
}

message ApiResponseOrderDelete {
  string status = 1;
  string message = 2;
}

message ApiResponseOrderAll {
  string status = 1;
  string message = 2;
}

message ApiResponsePaginationOrderDeleteAt {
  string status = 1;
  string message = 2;
  repeated OrderResponseDeleteAt data = 3;
  pb.api.PaginationMeta pagination = 4;
}

message ApiResponsePaginationOrder {
  string status = 1;
  string message = 2;
  repeated OrderResponse data = 3;
  pb.api.PaginationMeta pagination = 4;
}

service OrderQueryService {
  rpc FindAll(FindAllOrderRequest) returns (ApiResponsePaginationOrder);
  rpc FindByMerchant(FindAllOrderMerchantRequest) returns (ApiResponsePaginationOrder);
  rpc FindById(FindByIdOrderRequest) returns (ApiResponseOrder);
  rpc FindByActive(FindAllOrderRequest) returns (ApiResponsePaginationOrderDeleteAt);
  rpc FindByTrashed(FindAllOrderRequest) returns (ApiResponsePaginationOrderDeleteAt);
}
