// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: merchant/merchant_command.proto

package merchant

import (
	_ "github.com/MamangRust/monolith-graphql-pointofsale-pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_merchant_merchant_command_proto protoreflect.FileDescriptor

const file_merchant_merchant_command_proto_rawDesc = "" +
	"\n" +
	"\x1fmerchant/merchant_command.proto\x12\vpb.merchant\x1a\x10common/api.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1emerchant/merchant_common.proto2\xe3\x06\n" +
	"\x16MerchantCommandService\x12j\n" +
	"\rFindByTrashed\x12#.pb.merchant.FindAllMerchantRequest\x1a2.pb.merchant.ApiResponsePaginationMerchantDeleteAt\"\x00\x12N\n" +
	"\x06Create\x12\".pb.merchant.CreateMerchantRequest\x1a .pb.merchant.ApiResponseMerchant\x12N\n" +
	"\x06Update\x12\".pb.merchant.UpdateMerchantRequest\x1a .pb.merchant.ApiResponseMerchant\x12d\n" +
	"\x14UpdateMerchantStatus\x12(.pb.merchant.UpdateMerchantStatusRequest\x1a .pb.merchant.ApiResponseMerchant\"\x00\x12a\n" +
	"\x0fTrashedMerchant\x12$.pb.merchant.FindByIdMerchantRequest\x1a(.pb.merchant.ApiResponseMerchantDeleteAt\x12Y\n" +
	"\x0fRestoreMerchant\x12$.pb.merchant.FindByIdMerchantRequest\x1a .pb.merchant.ApiResponseMerchant\x12g\n" +
	"\x17DeleteMerchantPermanent\x12$.pb.merchant.FindByIdMerchantRequest\x1a&.pb.merchant.ApiResponseMerchantDelete\x12S\n" +
	"\x12RestoreAllMerchant\x12\x16.google.protobuf.Empty\x1a#.pb.merchant.ApiResponseMerchantAll\"\x00\x12[\n" +
	"\x1aDeleteAllMerchantPermanent\x12\x16.google.protobuf.Empty\x1a#.pb.merchant.ApiResponseMerchantAll\"\x00B@Z>github.com/MamangRust/monolith-graphql-pointofsale-pb/merchantb\x06proto3"

var file_merchant_merchant_command_proto_goTypes = []any{
	(*FindAllMerchantRequest)(nil),                // 0: pb.merchant.FindAllMerchantRequest
	(*CreateMerchantRequest)(nil),                 // 1: pb.merchant.CreateMerchantRequest
	(*UpdateMerchantRequest)(nil),                 // 2: pb.merchant.UpdateMerchantRequest
	(*UpdateMerchantStatusRequest)(nil),           // 3: pb.merchant.UpdateMerchantStatusRequest
	(*FindByIdMerchantRequest)(nil),               // 4: pb.merchant.FindByIdMerchantRequest
	(*emptypb.Empty)(nil),                         // 5: google.protobuf.Empty
	(*ApiResponsePaginationMerchantDeleteAt)(nil), // 6: pb.merchant.ApiResponsePaginationMerchantDeleteAt
	(*ApiResponseMerchant)(nil),                   // 7: pb.merchant.ApiResponseMerchant
	(*ApiResponseMerchantDeleteAt)(nil),           // 8: pb.merchant.ApiResponseMerchantDeleteAt
	(*ApiResponseMerchantDelete)(nil),             // 9: pb.merchant.ApiResponseMerchantDelete
	(*ApiResponseMerchantAll)(nil),                // 10: pb.merchant.ApiResponseMerchantAll
}
var file_merchant_merchant_command_proto_depIdxs = []int32{
	0,  // 0: pb.merchant.MerchantCommandService.FindByTrashed:input_type -> pb.merchant.FindAllMerchantRequest
	1,  // 1: pb.merchant.MerchantCommandService.Create:input_type -> pb.merchant.CreateMerchantRequest
	2,  // 2: pb.merchant.MerchantCommandService.Update:input_type -> pb.merchant.UpdateMerchantRequest
	3,  // 3: pb.merchant.MerchantCommandService.UpdateMerchantStatus:input_type -> pb.merchant.UpdateMerchantStatusRequest
	4,  // 4: pb.merchant.MerchantCommandService.TrashedMerchant:input_type -> pb.merchant.FindByIdMerchantRequest
	4,  // 5: pb.merchant.MerchantCommandService.RestoreMerchant:input_type -> pb.merchant.FindByIdMerchantRequest
	4,  // 6: pb.merchant.MerchantCommandService.DeleteMerchantPermanent:input_type -> pb.merchant.FindByIdMerchantRequest
	5,  // 7: pb.merchant.MerchantCommandService.RestoreAllMerchant:input_type -> google.protobuf.Empty
	5,  // 8: pb.merchant.MerchantCommandService.DeleteAllMerchantPermanent:input_type -> google.protobuf.Empty
	6,  // 9: pb.merchant.MerchantCommandService.FindByTrashed:output_type -> pb.merchant.ApiResponsePaginationMerchantDeleteAt
	7,  // 10: pb.merchant.MerchantCommandService.Create:output_type -> pb.merchant.ApiResponseMerchant
	7,  // 11: pb.merchant.MerchantCommandService.Update:output_type -> pb.merchant.ApiResponseMerchant
	7,  // 12: pb.merchant.MerchantCommandService.UpdateMerchantStatus:output_type -> pb.merchant.ApiResponseMerchant
	8,  // 13: pb.merchant.MerchantCommandService.TrashedMerchant:output_type -> pb.merchant.ApiResponseMerchantDeleteAt
	7,  // 14: pb.merchant.MerchantCommandService.RestoreMerchant:output_type -> pb.merchant.ApiResponseMerchant
	9,  // 15: pb.merchant.MerchantCommandService.DeleteMerchantPermanent:output_type -> pb.merchant.ApiResponseMerchantDelete
	10, // 16: pb.merchant.MerchantCommandService.RestoreAllMerchant:output_type -> pb.merchant.ApiResponseMerchantAll
	10, // 17: pb.merchant.MerchantCommandService.DeleteAllMerchantPermanent:output_type -> pb.merchant.ApiResponseMerchantAll
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_merchant_merchant_command_proto_init() }
func file_merchant_merchant_command_proto_init() {
	if File_merchant_merchant_command_proto != nil {
		return
	}
	file_merchant_merchant_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_merchant_command_proto_rawDesc), len(file_merchant_merchant_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_merchant_command_proto_goTypes,
		DependencyIndexes: file_merchant_merchant_command_proto_depIdxs,
	}.Build()
	File_merchant_merchant_command_proto = out.File
	file_merchant_merchant_command_proto_goTypes = nil
	file_merchant_merchant_command_proto_depIdxs = nil
}
