// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: merchant/query.proto

package merchant

import (
	api "github.com/MamangRust/monolith-graphql-pointofsale-pb/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllMerchantRequest) Reset() {
	*x = FindAllMerchantRequest{}
	mi := &file_merchant_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllMerchantRequest) ProtoMessage() {}

func (x *FindAllMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllMerchantRequest.ProtoReflect.Descriptor instead.
func (*FindAllMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllMerchantRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllMerchantRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllMerchantRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdMerchantRequest) Reset() {
	*x = FindByIdMerchantRequest{}
	mi := &file_merchant_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdMerchantRequest) ProtoMessage() {}

func (x *FindByIdMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdMerchantRequest.ProtoReflect.Descriptor instead.
func (*FindByIdMerchantRequest) Descriptor() ([]byte, []int) {
	return file_merchant_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindByIdMerchantRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,6,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	ContactPhone  string                 `protobuf:"bytes,7,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantResponse) Reset() {
	*x = MerchantResponse{}
	mi := &file_merchant_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantResponse) ProtoMessage() {}

func (x *MerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantResponse.ProtoReflect.Descriptor instead.
func (*MerchantResponse) Descriptor() ([]byte, []int) {
	return file_merchant_query_proto_rawDescGZIP(), []int{2}
}

func (x *MerchantResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MerchantResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MerchantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MerchantResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MerchantResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MerchantResponse) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *MerchantResponse) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *MerchantResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MerchantResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MerchantResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MerchantResponseDeleteAt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,6,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	ContactPhone  string                 `protobuf:"bytes,7,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantResponseDeleteAt) Reset() {
	*x = MerchantResponseDeleteAt{}
	mi := &file_merchant_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantResponseDeleteAt) ProtoMessage() {}

func (x *MerchantResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*MerchantResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_merchant_query_proto_rawDescGZIP(), []int{3}
}

func (x *MerchantResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MerchantResponseDeleteAt) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MerchantResponseDeleteAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MerchantResponseDeleteAt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MerchantResponseDeleteAt) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MerchantResponseDeleteAt) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *MerchantResponseDeleteAt) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *MerchantResponseDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MerchantResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MerchantResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MerchantResponseDeleteAt) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type ApiResponseMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *MerchantResponse      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchant) Reset() {
	*x = ApiResponseMerchant{}
	mi := &file_merchant_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchant) ProtoMessage() {}

func (x *ApiResponseMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchant.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchant) Descriptor() ([]byte, []int) {
	return file_merchant_query_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponseMerchant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchant) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchant) GetData() *MerchantResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseMerchantDeleteAt struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        string                    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *MerchantResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantDeleteAt) Reset() {
	*x = ApiResponseMerchantDeleteAt{}
	mi := &file_merchant_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantDeleteAt) ProtoMessage() {}

func (x *ApiResponseMerchantDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantDeleteAt) Descriptor() ([]byte, []int) {
	return file_merchant_query_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponseMerchantDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantDeleteAt) GetData() *MerchantResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantResponse    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesMerchant) Reset() {
	*x = ApiResponsesMerchant{}
	mi := &file_merchant_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesMerchant) ProtoMessage() {}

func (x *ApiResponsesMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesMerchant.ProtoReflect.Descriptor instead.
func (*ApiResponsesMerchant) Descriptor() ([]byte, []int) {
	return file_merchant_query_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponsesMerchant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesMerchant) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesMerchant) GetData() []*MerchantResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseMerchantDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantDelete) Reset() {
	*x = ApiResponseMerchantDelete{}
	mi := &file_merchant_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantDelete) ProtoMessage() {}

func (x *ApiResponseMerchantDelete) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantDelete) Descriptor() ([]byte, []int) {
	return file_merchant_query_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponseMerchantDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseMerchantAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantAll) Reset() {
	*x = ApiResponseMerchantAll{}
	mi := &file_merchant_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantAll) ProtoMessage() {}

func (x *ApiResponseMerchantAll) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantAll.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantAll) Descriptor() ([]byte, []int) {
	return file_merchant_query_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponseMerchantAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationMerchantDeleteAt struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *api.PaginationMeta         `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchantDeleteAt) Reset() {
	*x = ApiResponsePaginationMerchantDeleteAt{}
	mi := &file_merchant_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchantDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchantDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationMerchantDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchantDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchantDeleteAt) Descriptor() ([]byte, []int) {
	return file_merchant_query_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponsePaginationMerchantDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDeleteAt) GetData() []*MerchantResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchantDeleteAt) GetPagination() *api.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationMerchant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantResponse    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *api.PaginationMeta    `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchant) Reset() {
	*x = ApiResponsePaginationMerchant{}
	mi := &file_merchant_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchant) ProtoMessage() {}

func (x *ApiResponsePaginationMerchant) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchant.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchant) Descriptor() ([]byte, []int) {
	return file_merchant_query_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponsePaginationMerchant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchant) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchant) GetData() []*MerchantResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchant) GetPagination() *api.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_merchant_query_proto protoreflect.FileDescriptor

const file_merchant_query_proto_rawDesc = "" +
	"\n" +
	"\x14merchant/query.proto\x12\vpb.merchant\x1a\rapi/api.proto\"a\n" +
	"\x16FindAllMerchantRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\")\n" +
	"\x17FindByIdMerchantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xab\x02\n" +
	"\x10MerchantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12#\n" +
	"\rcontact_email\x18\x06 \x01(\tR\fcontactEmail\x12#\n" +
	"\rcontact_phone\x18\a \x01(\tR\fcontactPhone\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xd2\x02\n" +
	"\x18MerchantResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12#\n" +
	"\rcontact_email\x18\x06 \x01(\tR\fcontactEmail\x12#\n" +
	"\rcontact_phone\x18\a \x01(\tR\fcontactPhone\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\v \x01(\tR\tdeletedAt\"z\n" +
	"\x13ApiResponseMerchant\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x01(\v2\x1d.pb.merchant.MerchantResponseR\x04data\"\x8a\x01\n" +
	"\x1bApiResponseMerchantDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x01(\v2%.pb.merchant.MerchantResponseDeleteAtR\x04data\"{\n" +
	"\x14ApiResponsesMerchant\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.merchant.MerchantResponseR\x04data\"M\n" +
	"\x19ApiResponseMerchantDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x16ApiResponseMerchantAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcc\x01\n" +
	"%ApiResponsePaginationMerchantDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\x04data\x18\x03 \x03(\v2%.pb.merchant.MerchantResponseDeleteAtR\x04data\x126\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x16.pb.api.PaginationMetaR\n" +
	"pagination\"\xbc\x01\n" +
	"\x1dApiResponsePaginationMerchant\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.merchant.MerchantResponseR\x04data\x126\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x16.pb.api.PaginationMetaR\n" +
	"pagination2\x99\x03\n" +
	"\x14MerchantQueryService\x12Z\n" +
	"\aFindAll\x12#.pb.merchant.FindAllMerchantRequest\x1a*.pb.merchant.ApiResponsePaginationMerchant\x12R\n" +
	"\bFindById\x12$.pb.merchant.FindByIdMerchantRequest\x1a .pb.merchant.ApiResponseMerchant\x12g\n" +
	"\fFindByActive\x12#.pb.merchant.FindAllMerchantRequest\x1a2.pb.merchant.ApiResponsePaginationMerchantDeleteAt\x12h\n" +
	"\rFindByTrashed\x12#.pb.merchant.FindAllMerchantRequest\x1a2.pb.merchant.ApiResponsePaginationMerchantDeleteAtB@Z>github.com/MamangRust/monolith-graphql-pointofsale-pb/merchantb\x06proto3"

var (
	file_merchant_query_proto_rawDescOnce sync.Once
	file_merchant_query_proto_rawDescData []byte
)

func file_merchant_query_proto_rawDescGZIP() []byte {
	file_merchant_query_proto_rawDescOnce.Do(func() {
		file_merchant_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_query_proto_rawDesc), len(file_merchant_query_proto_rawDesc)))
	})
	return file_merchant_query_proto_rawDescData
}

var file_merchant_query_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_merchant_query_proto_goTypes = []any{
	(*FindAllMerchantRequest)(nil),                // 0: pb.merchant.FindAllMerchantRequest
	(*FindByIdMerchantRequest)(nil),               // 1: pb.merchant.FindByIdMerchantRequest
	(*MerchantResponse)(nil),                      // 2: pb.merchant.MerchantResponse
	(*MerchantResponseDeleteAt)(nil),              // 3: pb.merchant.MerchantResponseDeleteAt
	(*ApiResponseMerchant)(nil),                   // 4: pb.merchant.ApiResponseMerchant
	(*ApiResponseMerchantDeleteAt)(nil),           // 5: pb.merchant.ApiResponseMerchantDeleteAt
	(*ApiResponsesMerchant)(nil),                  // 6: pb.merchant.ApiResponsesMerchant
	(*ApiResponseMerchantDelete)(nil),             // 7: pb.merchant.ApiResponseMerchantDelete
	(*ApiResponseMerchantAll)(nil),                // 8: pb.merchant.ApiResponseMerchantAll
	(*ApiResponsePaginationMerchantDeleteAt)(nil), // 9: pb.merchant.ApiResponsePaginationMerchantDeleteAt
	(*ApiResponsePaginationMerchant)(nil),         // 10: pb.merchant.ApiResponsePaginationMerchant
	(*api.PaginationMeta)(nil),                    // 11: pb.api.PaginationMeta
}
var file_merchant_query_proto_depIdxs = []int32{
	2,  // 0: pb.merchant.ApiResponseMerchant.data:type_name -> pb.merchant.MerchantResponse
	3,  // 1: pb.merchant.ApiResponseMerchantDeleteAt.data:type_name -> pb.merchant.MerchantResponseDeleteAt
	2,  // 2: pb.merchant.ApiResponsesMerchant.data:type_name -> pb.merchant.MerchantResponse
	3,  // 3: pb.merchant.ApiResponsePaginationMerchantDeleteAt.data:type_name -> pb.merchant.MerchantResponseDeleteAt
	11, // 4: pb.merchant.ApiResponsePaginationMerchantDeleteAt.pagination:type_name -> pb.api.PaginationMeta
	2,  // 5: pb.merchant.ApiResponsePaginationMerchant.data:type_name -> pb.merchant.MerchantResponse
	11, // 6: pb.merchant.ApiResponsePaginationMerchant.pagination:type_name -> pb.api.PaginationMeta
	0,  // 7: pb.merchant.MerchantQueryService.FindAll:input_type -> pb.merchant.FindAllMerchantRequest
	1,  // 8: pb.merchant.MerchantQueryService.FindById:input_type -> pb.merchant.FindByIdMerchantRequest
	0,  // 9: pb.merchant.MerchantQueryService.FindByActive:input_type -> pb.merchant.FindAllMerchantRequest
	0,  // 10: pb.merchant.MerchantQueryService.FindByTrashed:input_type -> pb.merchant.FindAllMerchantRequest
	10, // 11: pb.merchant.MerchantQueryService.FindAll:output_type -> pb.merchant.ApiResponsePaginationMerchant
	4,  // 12: pb.merchant.MerchantQueryService.FindById:output_type -> pb.merchant.ApiResponseMerchant
	9,  // 13: pb.merchant.MerchantQueryService.FindByActive:output_type -> pb.merchant.ApiResponsePaginationMerchantDeleteAt
	9,  // 14: pb.merchant.MerchantQueryService.FindByTrashed:output_type -> pb.merchant.ApiResponsePaginationMerchantDeleteAt
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_merchant_query_proto_init() }
func file_merchant_query_proto_init() {
	if File_merchant_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_query_proto_rawDesc), len(file_merchant_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_query_proto_goTypes,
		DependencyIndexes: file_merchant_query_proto_depIdxs,
		MessageInfos:      file_merchant_query_proto_msgTypes,
	}.Build()
	File_merchant_query_proto = out.File
	file_merchant_query_proto_goTypes = nil
	file_merchant_query_proto_depIdxs = nil
}
