syntax = "proto3";

package pb.transaction;

import "common/api.proto";
import "google/protobuf/empty.proto";
import "transaction/transaction_common.proto";

option go_package = "github.com/MamangRust/monolith-graphql-pointofsale-pb/transaction";

service TransactionStatsService {
    rpc FindMonthStatusSuccess(FindMonthlyTransactionStatus) returns(ApiResponseTransactionMonthAmountSuccess);
    rpc FindYearStatusSuccess(FindYearlyTransactionStatus) returns(ApiResponseTransactionYearAmountSuccess);
    rpc FindMonthStatusFailed(FindMonthlyTransactionStatus) returns(ApiResponseTransactionMonthAmountFailed);
    rpc FindYearStatusFailed(FindYearlyTransactionStatus) returns(ApiResponseTransactionYearAmountFailed);
    rpc FindMonthStatusSuccessByMerchant(FindMonthlyTransactionStatusByMerchant) returns(ApiResponseTransactionMonthAmountSuccess);
    rpc FindYearStatusSuccessByMerchant(FindYearlyTransactionStatusByMerchant) returns(ApiResponseTransactionYearAmountSuccess);
    rpc FindMonthStatusFailedByMerchant(FindMonthlyTransactionStatusByMerchant) returns(ApiResponseTransactionMonthAmountFailed);
    rpc FindYearStatusFailedByMerchant(FindYearlyTransactionStatusByMerchant) returns(ApiResponseTransactionYearAmountFailed);
    rpc FindMonthMethodSuccess(MonthTransactionMethod) returns(ApiResponseTransactionMonthPaymentMethod);
    rpc FindYearMethodSuccess(YearTransactionMethod) returns(ApiResponseTransactionYearPaymentmethod);
    rpc FindMonthMethodByMerchantSuccess(MonthTransactionMethodByMerchant) returns(ApiResponseTransactionMonthPaymentMethod);
    rpc FindYearMethodByMerchantSuccess(YearTransactionMethodByMerchant) returns(ApiResponseTransactionYearPaymentmethod);
    rpc FindMonthMethodFailed(MonthTransactionMethod) returns(ApiResponseTransactionMonthPaymentMethod);
    rpc FindYearMethodFailed(YearTransactionMethod) returns(ApiResponseTransactionYearPaymentmethod);
    rpc FindMonthMethodByMerchantFailed(MonthTransactionMethodByMerchant) returns(ApiResponseTransactionMonthPaymentMethod);
    rpc FindYearMethodByMerchantFailed(YearTransactionMethodByMerchant) returns(ApiResponseTransactionYearPaymentmethod);
}
